-- Function: gpInsertUpdate_SaleExternal_Fora_Load()
!!!удален!!!

DROP FUNCTION IF EXISTS gpInsertUpdate_SaleExternal_Fora_Load
 (TDateTime, Integer, TVarChar, TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,TVarChar,
  TVarChar);

CREATE OR REPLACE FUNCTION gpInsertUpdate_SaleExternal_Fora_Load(
    IN inOperDate              TDateTime , --
    IN inRetailId              Integer   , --
    IN inArticle               TVarChar  , -- 
    IN inGoodsName             TVarChar  , -- 
IN inP1    TVarChar,
IN inP2    TVarChar,
IN inP3    TVarChar,
IN inP4    TVarChar,
IN inP5    TVarChar,
IN inP6    TVarChar,
IN inP7    TVarChar,
IN inP8    TVarChar,
IN inP9    TVarChar,
IN inP10    TVarChar,
IN inP11    TVarChar,
IN inP12    TVarChar,
IN inP13    TVarChar,
IN inP14    TVarChar,
IN inP15    TVarChar,
IN inP16    TVarChar,
IN inP17    TVarChar,
IN inP18    TVarChar,
IN inP19    TVarChar,
IN inP20    TVarChar,
IN inP21    TVarChar,
IN inP22    TVarChar,
IN inP23    TVarChar,
IN inP24    TVarChar,
IN inP25    TVarChar,
IN inP26    TVarChar,
IN inP27    TVarChar,
IN inP28    TVarChar,
IN inP29    TVarChar,
IN inP30    TVarChar,
IN inP31    TVarChar,
IN inP32    TVarChar,
IN inP33    TVarChar,
IN inP34    TVarChar,
IN inP35    TVarChar,
IN inP36    TVarChar,
IN inP37    TVarChar,
IN inP38    TVarChar,
IN inP39    TVarChar,
IN inP40    TVarChar,
IN inP41    TVarChar,
IN inP42    TVarChar,
IN inP43    TVarChar,
IN inP44    TVarChar,
IN inP45    TVarChar,
IN inP46    TVarChar,
IN inP47    TVarChar,
IN inP48    TVarChar,
IN inP49    TVarChar,
IN inP50    TVarChar,
IN inP51    TVarChar,
IN inP52    TVarChar,
IN inP53    TVarChar,
IN inP54    TVarChar,
IN inP55    TVarChar,
IN inP56    TVarChar,
IN inP57    TVarChar,
IN inP58    TVarChar,
IN inP59    TVarChar,
IN inP60    TVarChar,
IN inP61    TVarChar,
IN inP62    TVarChar,
IN inP63    TVarChar,
IN inP64    TVarChar,
IN inP65    TVarChar,
IN inP66    TVarChar,
IN inP67    TVarChar,
IN inP68    TVarChar,
IN inP69    TVarChar,
IN inP70    TVarChar,
IN inP71    TVarChar,
IN inP72    TVarChar,
IN inP73    TVarChar,
IN inP74    TVarChar,
IN inP75    TVarChar,
IN inP76    TVarChar,
IN inP77    TVarChar,
IN inP78    TVarChar,
IN inP79    TVarChar,
IN inP80    TVarChar,
IN inP81    TVarChar,
IN inP82    TVarChar,
IN inP83    TVarChar,
IN inP84    TVarChar,
IN inP85    TVarChar,
IN inP86    TVarChar,
IN inP87    TVarChar,
IN inP88    TVarChar,
IN inP89    TVarChar,
IN inP90    TVarChar,
IN inP91    TVarChar,
IN inP92    TVarChar,
IN inP93    TVarChar,
IN inP94    TVarChar,
IN inP95    TVarChar,
IN inP96    TVarChar,
IN inP97    TVarChar,
IN inP98    TVarChar,
IN inP99    TVarChar,
IN inP100    TVarChar,
IN inP101    TVarChar,
IN inP102    TVarChar,
IN inP103    TVarChar,
IN inP104    TVarChar,
IN inP105    TVarChar,
IN inP106    TVarChar,
IN inP107    TVarChar,
IN inP108    TVarChar,
IN inP109    TVarChar,
IN inP110    TVarChar,
IN inP111    TVarChar,
IN inP112    TVarChar,
IN inP113    TVarChar,
IN inP114    TVarChar,
IN inP115    TVarChar,
IN inP116    TVarChar,
IN inP117    TVarChar,
IN inP118    TVarChar,
IN inP119    TVarChar,
IN inP120    TVarChar,
IN inP121    TVarChar,
IN inP122    TVarChar,
IN inP123    TVarChar,
IN inP124    TVarChar,
IN inP125    TVarChar,
IN inP126    TVarChar,
IN inP127    TVarChar,
IN inP128    TVarChar,
IN inP129    TVarChar,
IN inP130    TVarChar,
IN inP131    TVarChar,
IN inP132    TVarChar,
IN inP133    TVarChar,
IN inP134    TVarChar,
IN inP135    TVarChar,
IN inP136    TVarChar,
IN inP137    TVarChar,
IN inP138    TVarChar,
IN inP139    TVarChar,
IN inP140    TVarChar,
IN inP141    TVarChar,
IN inP142    TVarChar,
IN inP143    TVarChar,
IN inP144    TVarChar,
IN inP145    TVarChar,
IN inP146    TVarChar,
IN inP147    TVarChar,
IN inP148    TVarChar,
IN inP149    TVarChar,
IN inP150    TVarChar,
IN inP151    TVarChar,
IN inP152    TVarChar,
IN inP153    TVarChar,
IN inP154    TVarChar,
IN inP155    TVarChar,
IN inP156    TVarChar,
IN inP157    TVarChar,
IN inP158    TVarChar,
IN inP159    TVarChar,
IN inP160    TVarChar,
IN inP161    TVarChar,
IN inP162    TVarChar,
IN inP163    TVarChar,
IN inP164    TVarChar,
IN inP165    TVarChar,
IN inP166    TVarChar,
IN inP167    TVarChar,
IN inP168    TVarChar,
IN inP169    TVarChar,
IN inP170    TVarChar,
IN inP171    TVarChar,
IN inP172    TVarChar,
IN inP173    TVarChar,
IN inP174    TVarChar,
IN inP175    TVarChar,
IN inP176    TVarChar,
IN inP177    TVarChar,
IN inP178    TVarChar,
IN inP179    TVarChar,
IN inP180    TVarChar,
IN inP181    TVarChar,
IN inP182    TVarChar,
IN inP183    TVarChar,
IN inP184    TVarChar,
IN inP185    TVarChar,
IN inP186    TVarChar,
IN inP187    TVarChar,
IN inP188    TVarChar,
IN inP189    TVarChar,
IN inP190    TVarChar,
IN inP191    TVarChar,
IN inP192    TVarChar,
IN inP193    TVarChar,
IN inP194    TVarChar,
IN inP195    TVarChar,
IN inP196    TVarChar,
IN inP197    TVarChar,
IN inP198    TVarChar,
IN inP199    TVarChar,
IN inP200    TVarChar,
IN inP201    TVarChar,
IN inP202    TVarChar,
IN inP203    TVarChar,
IN inP204    TVarChar,
IN inP205    TVarChar,
IN inP206    TVarChar,
IN inP207    TVarChar,
IN inP208    TVarChar,
IN inP209    TVarChar,
IN inP210    TVarChar,
IN inP211    TVarChar,
IN inP212    TVarChar,
IN inP213    TVarChar,
IN inP214    TVarChar,
IN inP215    TVarChar,
IN inP216    TVarChar,
IN inP217    TVarChar,
IN inP218    TVarChar,
IN inP219    TVarChar,
IN inP220    TVarChar,
IN inP221    TVarChar,
IN inP222    TVarChar,
IN inP223    TVarChar,
IN inP224    TVarChar,
IN inP225    TVarChar,
IN inP226    TVarChar,
IN inP227    TVarChar,
IN inP228    TVarChar,
IN inP229    TVarChar,
IN inP230    TVarChar,
IN inP231    TVarChar,
IN inP232    TVarChar,
IN inP233    TVarChar,
IN inP234    TVarChar,
IN inP235    TVarChar,
IN inP236    TVarChar,
IN inP237    TVarChar,
IN inP238    TVarChar,
IN inP239    TVarChar,
IN inP240    TVarChar,
IN inP241    TVarChar,
IN inP242    TVarChar,
IN inP243    TVarChar,
IN inP244    TVarChar,
IN inP245    TVarChar,
IN inP246    TVarChar,
IN inP247    TVarChar,
IN inP248    TVarChar,
IN inP249    TVarChar,
IN inP250    TVarChar,
IN inP251    TVarChar,
IN inP252    TVarChar,
IN inP253    TVarChar,
IN inP254    TVarChar,
IN inP255    TVarChar,
IN inP256    TVarChar,
IN inP257    TVarChar,
IN inP258    TVarChar,
IN inP259    TVarChar,
IN inP260    TVarChar,
IN inP261    TVarChar,
IN inP262    TVarChar,
IN inP263    TVarChar,
IN inP264    TVarChar,
IN inP265    TVarChar,
IN inP266    TVarChar,
IN inP267    TVarChar,
IN inP268    TVarChar,
IN inP269    TVarChar,
IN inP270    TVarChar,
IN inP271    TVarChar,
IN inP272    TVarChar,
IN inP273    TVarChar,
IN inP274    TVarChar,
IN inP275    TVarChar,
IN inP276    TVarChar,
IN inP277    TVarChar,
IN inP278    TVarChar,
IN inP279    TVarChar,
IN inP280    TVarChar,
IN inP281    TVarChar,
IN inP282    TVarChar,
IN inP283    TVarChar,
IN inP284    TVarChar,
IN inP285    TVarChar,
IN inP286    TVarChar,
IN inP287    TVarChar,
IN inP288    TVarChar,
IN inP289    TVarChar,
IN inP290    TVarChar,
IN inP291    TVarChar,
IN inP292    TVarChar,
IN inP293    TVarChar,
IN inP294    TVarChar,
IN inP295    TVarChar,
IN inP296    TVarChar,
IN inP297    TVarChar,
IN inP298    TVarChar,
IN inP299    TVarChar,
IN inP300    TVarChar,
IN inP301    TVarChar,
IN inP302    TVarChar,
IN inP303    TVarChar,
IN inP304    TVarChar,
IN inP305    TVarChar,
IN inP306    TVarChar,
IN inP307    TVarChar,
IN inP308    TVarChar,
IN inP309    TVarChar,
IN inP310    TVarChar,
IN inP311    TVarChar,
IN inP312    TVarChar,
IN inP313    TVarChar,
IN inP314    TVarChar,
IN inP315    TVarChar,
IN inP316    TVarChar,
IN inP317    TVarChar,
IN inP318    TVarChar,
IN inP319    TVarChar,
IN inP320    TVarChar,
IN inP321    TVarChar,
IN inP322    TVarChar,
IN inP323    TVarChar,
IN inP324    TVarChar,
IN inP325    TVarChar,
IN inP326    TVarChar,
IN inP327    TVarChar,
IN inP328    TVarChar,
IN inP329    TVarChar,
IN inP330    TVarChar,
IN inP331    TVarChar,
IN inP332    TVarChar,
IN inP333    TVarChar,
IN inP334    TVarChar,
IN inP335    TVarChar,
IN inP336    TVarChar,
IN inP337    TVarChar,
IN inP338    TVarChar,
IN inP339    TVarChar,
IN inP340    TVarChar,
IN inP341    TVarChar,
IN inP342    TVarChar,
IN inP343    TVarChar,
IN inP344    TVarChar,
IN inP345    TVarChar,
IN inP346    TVarChar,
IN inP347    TVarChar,
IN inP348    TVarChar,
IN inP349    TVarChar,
IN inP350    TVarChar,
IN inP351    TVarChar,
IN inP352    TVarChar,
IN inP353    TVarChar,
IN inP354    TVarChar,
IN inP355    TVarChar,
IN inP356    TVarChar,
IN inP357    TVarChar,
IN inP358    TVarChar,
IN inP359    TVarChar,
IN inP360    TVarChar,
IN inP361    TVarChar,
IN inP362    TVarChar,
IN inP363    TVarChar,
IN inP364    TVarChar,
IN inP365    TVarChar,
IN inP366    TVarChar,
IN inP367    TVarChar,
IN inP368    TVarChar,
IN inP369    TVarChar,
IN inP370    TVarChar,
IN inP371    TVarChar,
IN inP372    TVarChar,
IN inP373    TVarChar,
IN inP374    TVarChar,
IN inP375    TVarChar,
IN inP376    TVarChar,
IN inP377    TVarChar,
IN inP378    TVarChar,
IN inP379    TVarChar,
IN inP380    TVarChar,
IN inP381    TVarChar,
IN inP382    TVarChar,
IN inP383    TVarChar,
IN inP384    TVarChar,
IN inP385    TVarChar,
IN inP386    TVarChar,
IN inP387    TVarChar,
IN inP388    TVarChar,
IN inP389    TVarChar,
IN inP390    TVarChar,
IN inP391    TVarChar,
IN inP392    TVarChar,
IN inP393    TVarChar,
IN inP394    TVarChar,
IN inP395    TVarChar,
IN inP396    TVarChar,
IN inP397    TVarChar,
IN inP398    TVarChar,
IN inP399    TVarChar,
IN inP400    TVarChar,

    IN inSession               TVarChar    -- сессия пользователя
)
RETURNS VOID
AS
$BODY$
   DECLARE vbUserId            Integer;
   DECLARE vbPartnerExternalId Integer;
   DECLARE vbGoodsPropertyId   Integer;
   DECLARE vbGoodsPropertyValueId Integer;
   DECLARE vbGoodsId           Integer;
   DECLARE vbGoodsKindId       Integer;
   DECLARE vbMovementId        Integer;
   DECLARE vbId                Integer;
BEGIN
     -- проверка прав пользователя на вызов процедуры
     vbUserId:= lpCheckRight (inSession, zc_Enum_Process_InsertUpdate_Movement_SaleExternal());
/*
     -- итоговые строки пропускаем
     IF COALESCE (inPartnerExternalName,'') = ''
     THEN
         RETURN;
     END IF;
     
     -- проверка
     IF COALESCE (inRetailId,0) = 0
     THEN
         RAISE EXCEPTION 'Ошибка.Торговая сеть не выбрана';
     END IF;

     --ищем PartnerExternal
     vbPartnerExternalId := (SELECT Object_PartnerExternal.Id 
                             FROM Object AS Object_PartnerExternal
                                  INNER JOIN ObjectString AS ObjectString_ObjectCode
                                                          ON ObjectString_ObjectCode.ObjectId = Object_PartnerExternal.Id 
                                                         AND ObjectString_ObjectCode.DescId = zc_ObjectString_PartnerExternal_ObjectCode()
                                                         AND ObjectString_ObjectCode.ValueData = inPartnerExternalCode
                                  LEFT JOIN ObjectLink AS ObjectLink_Retail
                                                       ON ObjectLink_Retail.ObjectId = Object_PartnerExternal.Id 
                                                      AND ObjectLink_Retail.DescId = zc_ObjectLink_PartnerExternal_Retail()
                             WHERE Object_PartnerExternal.DescId = zc_Object_PartnerExternal()
                               AND (ObjectLink_Retail.ChildObjectId = inRetailId OR COALESCE(ObjectLink_Retail.ChildObjectId,0) = 0)
                             );
     
     --если не найден
     IF COALESCE (vbPartnerExternalId,0) = 0
     THEN
         RAISE EXCEPTION 'Ошибка.Контрагент внешний - (<%>) <%> не найден.', inPartnerExternalCode, inPartnerExternalName;
         /*vbPartnerExternalId :=  lpInsertUpdate_Object_PartnerExternal (ioId         := 0
                                                                      , inCode       := lfGet_ObjectCode(0, zc_Object_PartnerExternal())
                                                                      , inName       := inPartnerExternalName
                                                                      , inObjectCode := inPartnerExternalCode
                                                                      , inPartnerId  := 0 -- inPartnerId
                                                                      , inContractId := 0 -- inContractId
                                                                      , inRetailId   := inRetailId
                                                                      , inUserId     := vbUserId
                                                                      );
                                                                      */
     ELSE
         --если элемент найден пересохраним только параметр торг. сеть
         PERFORM lpInsertUpdate_ObjectLink(zc_ObjectLink_PartnerExternal_Retail(), vbPartnerExternalId, inRetailId);
     END IF;

     --находим Классификатор свойств товаров, по связи с partner , далее juridical, далее GoodsProperty
     vbGoodsPropertyId := (SELECT ObjectLink_Juridical_GoodsProperty.ChildObjectId
                           FROM ObjectLink AS ObjectLink_Partner
                                LEFT JOIN ObjectLink AS ObjectLink_Partner_Juridical
                                                     ON ObjectLink_Partner_Juridical.ObjectId = ObjectLink_Partner.ChildObjectId
                                                    AND ObjectLink_Partner_Juridical.DescId = zc_ObjectLink_Partner_Juridical()
                                LEFT JOIN ObjectLink AS ObjectLink_Juridical_GoodsProperty
                                                     ON ObjectLink_Juridical_GoodsProperty.ObjectId = ObjectLink_Partner_Juridical.ChildObjectId
                                                    AND ObjectLink_Juridical_GoodsProperty.DescId = zc_ObjectLink_Juridical_GoodsProperty()
                           WHERE ObjectLink_Partner.ObjectId = vbPartnerExternalId 
                             AND ObjectLink_Partner.DescId = zc_ObjectLink_PartnerExternal_Partner()
                           );

     -- пробуем найти документ 
     vbMovementId := (SELECT Movement.Id
                      FROM Movement
                           INNER JOIN MovementLinkObject AS MovementLinkObject_From
                                                         ON MovementLinkObject_From.MovementId = Movement.Id
                                                        AND MovementLinkObject_From.DescId = zc_MovementLinkObject_From()
                                                        AND MovementLinkObject_From.ObjectId = vbPartnerExternalId
                           INNER JOIN MovementLinkObject AS MovementLinkObject_GoodsProperty
                                                         ON MovementLinkObject_GoodsProperty.MovementId = Movement.Id
                                                        AND MovementLinkObject_GoodsProperty.DescId = zc_MovementLinkObject_GoodsProperty()
                                                        AND MovementLinkObject_GoodsProperty.ObjectId = vbGoodsPropertyId
                      WHERE Movement.DescId = zc_Movement_SaleExternal()
                        AND Movement.StatusId = zc_Enum_Status_UnComplete()
                        AND Movement.OperDate =  DATE_TRUNC ('MONTH', inOperDate)
                      );

     -- если не нашли создаем
     IF COALESCE (vbMovementId,0) = 0
     THEN
         -- сохранили <Документ>
         vbMovementId:= lpInsertUpdate_Movement_SaleExternal (ioId               := 0
                                                            , inInvNumber        := CAST (NEXTVAL ('movement_SaleExternal_seq') AS TVarChar)
                                                            , inOperDate         := inOperDate
                                                            , inFromId           := vbPartnerExternalId
                                                            , inGoodsPropertyId  := vbGoodsPropertyId
                                                            , inComment          := 'Загрузка' :: TVarChar
                                                            , inUserId           := vbUserId
                                                             )AS tmp;
     END IF;

     --создаем строки
     --находим GoodsId по Артикулу
     SELECT ObjectLink_GoodsPropertyValue_Goods.ChildObjectId     AS GoodsId
          , ObjectLink_GoodsPropertyValue_GoodsKind.ChildObjectId AS GoodsKindId
          , ObjectLink_GoodsPropertyValue_GoodsProperty.ObjectId  AS GoodsPropertyValueId
   INTO vbGoodsId, vbGoodsKindId, vbGoodsPropertyValueId
     FROM ObjectLink AS ObjectLink_GoodsPropertyValue_GoodsProperty
          INNER JOIN ObjectString AS ObjectString_ArticleExternal
                                  ON ObjectString_ArticleExternal.ObjectId = ObjectLink_GoodsPropertyValue_GoodsProperty.ObjectId
                                 AND ObjectString_ArticleExternal.DescId = zc_ObjectString_GoodsPropertyValue_ArticleExternal()
                                 AND ObjectString_ArticleExternal.ValueData = inArticle
          INNER JOIN ObjectLink AS ObjectLink_GoodsPropertyValue_Goods
                                ON ObjectLink_GoodsPropertyValue_Goods.ObjectId = ObjectLink_GoodsPropertyValue_GoodsProperty.ObjectId
                               AND ObjectLink_GoodsPropertyValue_Goods.DescId = zc_ObjectLink_GoodsPropertyValue_Goods()
          INNER JOIN ObjectLink AS ObjectLink_GoodsPropertyValue_GoodsKind
                               ON ObjectLink_GoodsPropertyValue_GoodsKind.ObjectId = ObjectLink_GoodsPropertyValue_GoodsProperty.ObjectId
                              AND ObjectLink_GoodsPropertyValue_GoodsKind.DescId = zc_ObjectLink_GoodsPropertyValue_GoodsKind()
     WHERE ObjectLink_GoodsPropertyValue_GoodsProperty.ChildObjectId = vbGoodsPropertyId
       AND ObjectLink_GoodsPropertyValue_GoodsProperty.DescId = zc_ObjectLink_GoodsPropertyValue_GoodsProperty()
     ;

     -- сохраняем св-во  zc_ObjectString_GoodsPropertyValue_NameExternal
     PERFORM lpInsertUpdate_ObjectString(zc_ObjectString_GoodsPropertyValue_NameExternal(), vbGoodsPropertyValueId, inGoodsName);

     -- найти если такой товар уже записан
     vbId := (SELECT MovementItem.Id
              FROM MovementItem
                   INNER JOIN MovementItemLinkObject AS MILinkObject_GoodsKind
                                                     ON MILinkObject_GoodsKind.MovementItemId = MovementItem.Id
                                                    AND MILinkObject_GoodsKind.DescId = zc_MILinkObject_GoodsKind()
                                                    AND MILinkObject_GoodsKind.ObjectId = vbGoodsKindId
              WHERE MovementItem.MovementId = vbMovementId
                AND MovementItem.DescId = zc_MI_Master()
                AND MovementItem.isErased = FALSE
                AND MovementItem.ObjectId = vbGoodsId
              LIMIT 1
             );

     -- сохранили <Элемент документа>
     PERFORM lpInsertUpdate_MovementItem_SaleExternal (ioId           := COALESCE (vbId,0) ::Integer
                                                     , inMovementId   := vbMovementId      ::Integer
                                                     , inGoodsId      := vbGoodsId         ::Integer
                                                     , inAmount       := inAmount          ::TFloat --CASE WHEN ObjectLink_Measure.ChildObjectId = zc_Measure_Sh() THEN inAmount ELSE inAmount_kg END ::TFloat
                                                     , inGoodsKindId  := vbGoodsKindId     ::Integer
                                                     , inUserId       := vbUserId          ::Integer
                                                      ) 
     FROM ObjectLink AS ObjectLink_Measure
     WHERE ObjectLink_Measure.ObjectId = vbGoodsId
       AND ObjectLink_Measure.DescId = zc_ObjectLink_Goods_Measure();
*/
END;
$BODY$
  LANGUAGE plpgsql VOLATILE;

/*
 ИСТОРИЯ РАЗРАБОТКИ: ДАТА, АВТОР
               Фелонюк И.В.   Кухтин И.В.   Климентьев К.И.
01.11.20          *
*/

-- тест
--
/*
SELECT * FROM FUNCTION gpInsertUpdate_SaleExternal_Fora_Load(
    '01.11.2020' :: TDateTime
, 0 :: Integer
, 'Артикул' :: TVarChar
, 'Наименование' :: TVarChar  , 
 ' Магазин1'   ::TVarChar, 
 ' Магазин2'   ::TVarChar, 
 ' Магазин3'   ::TVarChar, 
 ' Магазин4'   ::TVarChar, 
 ' Магазин5'   ::TVarChar, 
 ' Магазин6'   ::TVarChar, 
 ' Магазин7'   ::TVarChar, 
 ' Магазин8'   ::TVarChar, 
 ' Магазин9'   ::TVarChar, 
 ' Магазин10'   ::TVarChar, 
 ' Магазин11'   ::TVarChar, 
 ' Магазин12'   ::TVarChar, 
 ' Магазин13'   ::TVarChar, 
 ' Магазин14'   ::TVarChar, 
 ' Магазин15'   ::TVarChar, 
 ' Магазин16'   ::TVarChar, 
 ' Магазин17'   ::TVarChar, 
 ' Магазин18'   ::TVarChar, 
 ' Магазин19'   ::TVarChar, 
 ' Магазин20'   ::TVarChar, 
 ' Магазин21'   ::TVarChar, 
 ' Магазин22'   ::TVarChar, 
 ' Магазин23'   ::TVarChar, 
 ' Магазин24'   ::TVarChar, 
 ' Магазин25'   ::TVarChar, 
 ' Магазин26'   ::TVarChar, 
 ' Магазин27'   ::TVarChar, 
 ' Магазин28'   ::TVarChar, 
 ' Магазин29'   ::TVarChar, 
 ' Магазин30'   ::TVarChar, 
 ' Магазин31'   ::TVarChar, 
 ' Магазин32'   ::TVarChar, 
 ' Магазин33'   ::TVarChar, 
 ' Магазин34'   ::TVarChar, 
 ' Магазин35'   ::TVarChar, 
 ' Магазин36'   ::TVarChar, 
 ' Магазин37'   ::TVarChar, 
 ' Магазин38'   ::TVarChar, 
 ' Магазин39'   ::TVarChar, 
 ' Магазин40'   ::TVarChar, 
 ' Магазин41'   ::TVarChar, 
 ' Магазин42'   ::TVarChar, 
 ' Магазин43'   ::TVarChar, 
 ' Магазин44'   ::TVarChar, 
 ' Магазин45'   ::TVarChar, 
 ' Магазин46'   ::TVarChar, 
 ' Магазин47'   ::TVarChar, 
 ' Магазин48'   ::TVarChar, 
 ' Магазин49'   ::TVarChar, 
 ' Магазин50'   ::TVarChar, 
 ' Магазин51'   ::TVarChar, 
 ' Магазин52'   ::TVarChar, 
 ' Магазин53'   ::TVarChar, 
 ' Магазин54'   ::TVarChar, 
 ' Магазин55'   ::TVarChar, 
 ' Магазин56'   ::TVarChar, 
 ' Магазин57'   ::TVarChar, 
 ' Магазин58'   ::TVarChar, 
 ' Магазин59'   ::TVarChar, 
 ' Магазин60'   ::TVarChar, 
 ' Магазин61'   ::TVarChar, 
 ' Магазин62'   ::TVarChar, 
 ' Магазин63'   ::TVarChar, 
 ' Магазин64'   ::TVarChar, 
 ' Магазин65'   ::TVarChar, 
 ' Магазин66'   ::TVarChar, 
 ' Магазин67'   ::TVarChar, 
 ' Магазин68'   ::TVarChar, 
 ' Магазин69'   ::TVarChar, 
 ' Магазин70'   ::TVarChar, 
 ' Магазин71'   ::TVarChar, 
 ' Магазин72'   ::TVarChar, 
 ' Магазин73'   ::TVarChar, 
 ' Магазин74'   ::TVarChar, 
 ' Магазин75'   ::TVarChar, 
 ' Магазин76'   ::TVarChar, 
 ' Магазин77'   ::TVarChar, 
 ' Магазин78'   ::TVarChar, 
 ' Магазин79'   ::TVarChar, 
 ' Магазин80'   ::TVarChar, 
 ' Магазин81'   ::TVarChar, 
 ' Магазин82'   ::TVarChar, 
 ' Магазин83'   ::TVarChar, 
 ' Магазин84'   ::TVarChar, 
 ' Магазин85'   ::TVarChar, 
 ' Магазин86'   ::TVarChar, 
 ' Магазин87'   ::TVarChar, 
 ' Магазин88'   ::TVarChar, 
 ' Магазин89'   ::TVarChar, 
 ' Магазин90'   ::TVarChar, 
 ' Магазин91'   ::TVarChar, 
 ' Магазин92'   ::TVarChar, 
 ' Магазин93'   ::TVarChar, 
 ' Магазин94'   ::TVarChar, 
 ' Магазин95'   ::TVarChar, 
 ' Магазин96'   ::TVarChar, 
 ' Магазин97'   ::TVarChar, 
 ' Магазин98'   ::TVarChar, 
 ' Магазин99'   ::TVarChar, 
 ' Магазин100'   ::TVarChar, 
 ' Магазин101'   ::TVarChar, 
 ' Магазин102'   ::TVarChar, 
 ' Магазин103'   ::TVarChar, 
 ' Магазин104'   ::TVarChar, 
 ' Магазин105'   ::TVarChar, 
 ' Магазин106'   ::TVarChar, 
 ' Магазин107'   ::TVarChar, 
 ' Магазин108'   ::TVarChar, 
 ' Магазин109'   ::TVarChar, 
 ' Магазин110'   ::TVarChar, 
 ' Магазин111'   ::TVarChar, 
 ' Магазин112'   ::TVarChar, 
 ' Магазин113'   ::TVarChar, 
 ' Магазин114'   ::TVarChar, 
 ' Магазин115'   ::TVarChar, 
 ' Магазин116'   ::TVarChar, 
 ' Магазин117'   ::TVarChar, 
 ' Магазин118'   ::TVarChar, 
 ' Магазин119'   ::TVarChar, 
 ' Магазин120'   ::TVarChar, 
 ' Магазин121'   ::TVarChar, 
 ' Магазин122'   ::TVarChar, 
 ' Магазин123'   ::TVarChar, 
 ' Магазин124'   ::TVarChar, 
 ' Магазин125'   ::TVarChar, 
 ' Магазин126'   ::TVarChar, 
 ' Магазин127'   ::TVarChar, 
 ' Магазин128'   ::TVarChar, 
 ' Магазин129'   ::TVarChar, 
 ' Магазин130'   ::TVarChar, 
 ' Магазин131'   ::TVarChar, 
 ' Магазин132'   ::TVarChar, 
 ' Магазин133'   ::TVarChar, 
 ' Магазин134'   ::TVarChar, 
 ' Магазин135'   ::TVarChar, 
 ' Магазин136'   ::TVarChar, 
 ' Магазин137'   ::TVarChar, 
 ' Магазин138'   ::TVarChar, 
 ' Магазин139'   ::TVarChar, 
 ' Магазин140'   ::TVarChar, 
 ' Магазин141'   ::TVarChar, 
 ' Магазин142'   ::TVarChar, 
 ' Магазин143'   ::TVarChar, 
 ' Магазин144'   ::TVarChar, 
 ' Магазин145'   ::TVarChar, 
 ' Магазин146'   ::TVarChar, 
 ' Магазин147'   ::TVarChar, 
 ' Магазин148'   ::TVarChar, 
 ' Магазин149'   ::TVarChar, 
 ' Магазин150'   ::TVarChar, 
 ' Магазин151'   ::TVarChar, 
 ' Магазин152'   ::TVarChar, 
 ' Магазин153'   ::TVarChar, 
 ' Магазин154'   ::TVarChar, 
 ' Магазин155'   ::TVarChar, 
 ' Магазин156'   ::TVarChar, 
 ' Магазин157'   ::TVarChar, 
 ' Магазин158'   ::TVarChar, 
 ' Магазин159'   ::TVarChar, 
 ' Магазин160'   ::TVarChar, 
 ' Магазин161'   ::TVarChar, 
 ' Магазин162'   ::TVarChar, 
 ' Магазин163'   ::TVarChar, 
 ' Магазин164'   ::TVarChar, 
 ' Магазин165'   ::TVarChar, 
 ' Магазин166'   ::TVarChar, 
 ' Магазин167'   ::TVarChar, 
 ' Магазин168'   ::TVarChar, 
 ' Магазин169'   ::TVarChar, 
 ' Магазин170'   ::TVarChar, 
 ' Магазин171'   ::TVarChar, 
 ' Магазин172'   ::TVarChar, 
 ' Магазин173'   ::TVarChar, 
 ' Магазин174'   ::TVarChar, 
 ' Магазин175'   ::TVarChar, 
 ' Магазин176'   ::TVarChar, 
 ' Магазин177'   ::TVarChar, 
 ' Магазин178'   ::TVarChar, 
 ' Магазин179'   ::TVarChar, 
 ' Магазин180'   ::TVarChar, 
 ' Магазин181'   ::TVarChar, 
 ' Магазин182'   ::TVarChar, 
 ' Магазин183'   ::TVarChar, 
 ' Магазин184'   ::TVarChar, 
 ' Магазин185'   ::TVarChar, 
 ' Магазин186'   ::TVarChar, 
 ' Магазин187'   ::TVarChar, 
 ' Магазин188'   ::TVarChar, 
 ' Магазин189'   ::TVarChar, 
 ' Магазин190'   ::TVarChar, 
 ' Магазин191'   ::TVarChar, 
 ' Магазин192'   ::TVarChar, 
 ' Магазин193'   ::TVarChar, 
 ' Магазин194'   ::TVarChar, 
 ' Магазин195'   ::TVarChar, 
 ' Магазин196'   ::TVarChar, 
 ' Магазин197'   ::TVarChar, 
 ' Магазин198'   ::TVarChar, 
 ' Магазин199'   ::TVarChar, 
 ' Магазин200'   ::TVarChar, 
 ' Магазин201'   ::TVarChar, 
 ' Магазин202'   ::TVarChar, 
 ' Магазин203'   ::TVarChar, 
 ' Магазин204'   ::TVarChar, 
 ' Магазин205'   ::TVarChar, 
 ' Магазин206'   ::TVarChar, 
 ' Магазин207'   ::TVarChar, 
 ' Магазин208'   ::TVarChar, 
 ' Магазин209'   ::TVarChar, 
 ' Магазин210'   ::TVarChar, 
 ' Магазин211'   ::TVarChar, 
 ' Магазин212'   ::TVarChar, 
 ' Магазин213'   ::TVarChar, 
 ' Магазин214'   ::TVarChar, 
 ' Магазин215'   ::TVarChar, 
 ' Магазин216'   ::TVarChar, 
 ' Магазин217'   ::TVarChar, 
 ' Магазин218'   ::TVarChar, 
 ' Магазин219'   ::TVarChar, 
 ' Магазин220'   ::TVarChar, 
 ' Магазин221'   ::TVarChar, 
 ' Магазин222'   ::TVarChar, 
 ' Магазин223'   ::TVarChar, 
 ' Магазин224'   ::TVarChar, 
 ' Магазин225'   ::TVarChar, 
 ' Магазин226'   ::TVarChar, 
 ' Магазин227'   ::TVarChar, 
 ' Магазин228'   ::TVarChar, 
 ' Магазин229'   ::TVarChar, 
 ' Магазин230'   ::TVarChar, 
 ' Магазин231'   ::TVarChar, 
 ' Магазин232'   ::TVarChar, 
 ' Магазин233'   ::TVarChar, 
 ' Магазин234'   ::TVarChar, 
 ' Магазин235'   ::TVarChar, 
 ' Магазин236'   ::TVarChar, 
 ' Магазин237'   ::TVarChar, 
 ' Магазин238'   ::TVarChar, 
 ' Магазин239'   ::TVarChar, 
 ' Магазин240'   ::TVarChar, 
 ' Магазин241'   ::TVarChar, 
 ' Магазин242'   ::TVarChar, 
 ' Магазин243'   ::TVarChar, 
 ' Магазин244'   ::TVarChar, 
 ' Магазин245'   ::TVarChar, 
 ' Магазин246'   ::TVarChar, 
 ' Магазин247'   ::TVarChar, 
 ' Магазин248'   ::TVarChar, 
 ' Магазин249'   ::TVarChar, 
 ' Магазин250'   ::TVarChar, 
 ' Магазин251'   ::TVarChar, 
 ' Магазин252'   ::TVarChar, 
 ' Магазин253'   ::TVarChar, 
 ' Магазин254'   ::TVarChar, 
 ' Магазин255'   ::TVarChar, 
 ' Магазин256'   ::TVarChar, 
 ' Магазин257'   ::TVarChar, 
 ' Магазин258'   ::TVarChar, 
 ' Магазин259'   ::TVarChar, 
 ' Магазин260'   ::TVarChar, 
 ' Магазин261'   ::TVarChar, 
 ' Магазин262'   ::TVarChar, 
 ' Магазин263'   ::TVarChar, 
 ' Магазин264'   ::TVarChar, 
 ' Магазин265'   ::TVarChar, 
 ' Магазин266'   ::TVarChar, 
 ' Магазин267'   ::TVarChar, 
 ' Магазин268'   ::TVarChar, 
 ' Магазин269'   ::TVarChar, 
 ' Магазин270'   ::TVarChar, 
 ' Магазин271'   ::TVarChar, 
 ' Магазин272'   ::TVarChar, 
 ' Магазин273'   ::TVarChar, 
 ' Магазин274'   ::TVarChar, 
 ' Магазин275'   ::TVarChar, 
 ' Магазин276'   ::TVarChar, 
 ' Магазин277'   ::TVarChar, 
 ' Магазин278'   ::TVarChar, 
 ' Магазин279'   ::TVarChar, 
 ' Магазин280'   ::TVarChar, 
 ' Магазин281'   ::TVarChar, 
 ' Магазин282'   ::TVarChar, 
 ' Магазин283'   ::TVarChar, 
 ' Магазин284'   ::TVarChar, 
 ' Магазин285'   ::TVarChar, 
 ' Магазин286'   ::TVarChar, 
 ' Магазин287'   ::TVarChar, 
 ' Магазин288'   ::TVarChar, 
 ' Магазин289'   ::TVarChar, 
 ' Магазин290'   ::TVarChar, 
 ' Магазин291'   ::TVarChar, 
 ' Магазин292'   ::TVarChar, 
 ' Магазин293'   ::TVarChar, 
 ' Магазин294'   ::TVarChar, 
 ' Магазин295'   ::TVarChar, 
 ' Магазин296'   ::TVarChar, 
 ' Магазин297'   ::TVarChar, 
 ' Магазин298'   ::TVarChar, 
 ' Магазин299'   ::TVarChar, 
 ' Магазин300'   ::TVarChar, 
 ' Магазин301'   ::TVarChar, 
 ' Магазин302'   ::TVarChar, 
 ' Магазин303'   ::TVarChar, 
 ' Магазин304'   ::TVarChar, 
 ' Магазин305'   ::TVarChar, 
 ' Магазин306'   ::TVarChar, 
 ' Магазин307'   ::TVarChar, 
 ' Магазин308'   ::TVarChar, 
 ' Магазин309'   ::TVarChar, 
 ' Магазин310'   ::TVarChar, 
 ' Магазин311'   ::TVarChar, 
 ' Магазин312'   ::TVarChar, 
 ' Магазин313'   ::TVarChar, 
 ' Магазин314'   ::TVarChar, 
 ' Магазин315'   ::TVarChar, 
 ' Магазин316'   ::TVarChar, 
 ' Магазин317'   ::TVarChar, 
 ' Магазин318'   ::TVarChar, 
 ' Магазин319'   ::TVarChar, 
 ' Магазин320'   ::TVarChar, 
 ' Магазин321'   ::TVarChar, 
 ' Магазин322'   ::TVarChar, 
 ' Магазин323'   ::TVarChar, 
 ' Магазин324'   ::TVarChar, 
 ' Магазин325'   ::TVarChar, 
 ' Магазин326'   ::TVarChar, 
 ' Магазин327'   ::TVarChar, 
 ' Магазин328'   ::TVarChar, 
 ' Магазин329'   ::TVarChar, 
 ' Магазин330'   ::TVarChar, 
 ' Магазин331'   ::TVarChar, 
 ' Магазин332'   ::TVarChar, 
 ' Магазин333'   ::TVarChar, 
 ' Магазин334'   ::TVarChar, 
 ' Магазин335'   ::TVarChar, 
 ' Магазин336'   ::TVarChar, 
 ' Магазин337'   ::TVarChar, 
 ' Магазин338'   ::TVarChar, 
 ' Магазин339'   ::TVarChar, 
 ' Магазин340'   ::TVarChar, 
 ' Магазин341'   ::TVarChar, 
 ' Магазин342'   ::TVarChar, 
 ' Магазин343'   ::TVarChar, 
 ' Магазин344'   ::TVarChar, 
 ' Магазин345'   ::TVarChar, 
 ' Магазин346'   ::TVarChar, 
 ' Магазин347'   ::TVarChar, 
 ' Магазин348'   ::TVarChar, 
 ' Магазин349'   ::TVarChar, 
 ' Магазин350'   ::TVarChar, 
 ' Магазин351'   ::TVarChar, 
 ' Магазин352'   ::TVarChar, 
 ' Магазин353'   ::TVarChar, 
 ' Магазин354'   ::TVarChar, 
 ' Магазин355'   ::TVarChar, 
 ' Магазин356'   ::TVarChar, 
 ' Магазин357'   ::TVarChar, 
 ' Магазин358'   ::TVarChar, 
 ' Магазин359'   ::TVarChar, 
 ' Магазин360'   ::TVarChar, 
 ' Магазин361'   ::TVarChar, 
 ' Магазин362'   ::TVarChar, 
 ' Магазин363'   ::TVarChar, 
 ' Магазин364'   ::TVarChar, 
 ' Магазин365'   ::TVarChar, 
 ' Магазин366'   ::TVarChar, 
 ' Магазин367'   ::TVarChar, 
 ' Магазин368'   ::TVarChar, 
 ' Магазин369'   ::TVarChar, 
 ' Магазин370'   ::TVarChar, 
 ' Магазин371'   ::TVarChar, 
 ' Магазин372'   ::TVarChar, 
 ' Магазин373'   ::TVarChar, 
 ' Магазин374'   ::TVarChar, 
 ' Магазин375'   ::TVarChar, 
 ' Магазин376'   ::TVarChar, 
 ' Магазин377'   ::TVarChar, 
 ' Магазин378'   ::TVarChar, 
 ' Магазин379'   ::TVarChar, 
 ' Магазин380'   ::TVarChar, 
 ' Магазин381'   ::TVarChar, 
 ' Магазин382'   ::TVarChar, 
 ' Магазин383'   ::TVarChar, 
 ' Магазин384'   ::TVarChar, 
 ' Магазин385'   ::TVarChar, 
 ' Магазин386'   ::TVarChar, 
 ' Магазин387'   ::TVarChar, 
 ' Магазин388'   ::TVarChar, 
 ' Магазин389'   ::TVarChar, 
 ' Магазин390'   ::TVarChar, 
 ' Магазин391'   ::TVarChar, 
 ' Магазин392'   ::TVarChar, 
 ' Магазин393'   ::TVarChar, 
 ' Магазин394'   ::TVarChar, 
 ' Магазин395'   ::TVarChar, 
 ' Магазин396'   ::TVarChar, 
 ' Магазин397'   ::TVarChar, 
 ' Магазин398'   ::TVarChar, 
 ' Магазин399'   ::TVarChar, 
 ' Магазин400'   ::TVarChar
 ,  '5'::TVarChar);

*/