--DELETE 
--FROM ObjectHistoryFloat 
--WHERE ObjectHistoryFloat.objecthistoryid IN (SELECT ID  FROM ObjectHistory
--   WHERE ObjectId not IN (SELECT Id FROM Object)
--)
--;

--DELETE 
--FROM ObjectHistoryString
--WHERE ObjectHistoryString.objecthistoryid IN (SELECT ID  FROM ObjectHistory
--   WHERE ObjectId not IN (SELECT Id FROM Object)
--)
--;
--DELETE 
--FROM ObjectHistoryLink 
--WHERE ObjectHistoryLink.objecthistoryid IN (SELECT ID  FROM ObjectHistory
--   WHERE ObjectId not IN (SELECT Id FROM Object)
--)
--;
--DELETE  FROM ObjectHistory
--WHERE ObjectId not IN (SELECT Id FROM Object)