inherited DialogTareForm: TDialogTareForm
  Caption = #1055#1086#1076#1090#1074#1077#1088#1078#1076#1077#1085#1080#1077
  ClientHeight = 452
  ClientWidth = 560
  OldCreateOrder = True
  Position = poScreenCenter
  OnCloseQuery = FormCloseQuery
  ExplicitWidth = 576
  ExplicitHeight = 491
  PixelsPerInch = 96
  TextHeight = 14
  inherited bbPanel: TPanel
    Top = 411
    Width = 560
    ExplicitTop = 447
    ExplicitWidth = 433
    inherited bbOk: TBitBtn
      Left = 35
      Default = False
      ExplicitLeft = 35
    end
    inherited bbCancel: TBitBtn
      Left = 148
      Default = True
      Kind = bkCustom
      ExplicitLeft = 148
    end
  end
  object infoPanelTareFix: TPanel
    Left = 0
    Top = 0
    Width = 425
    Height = 411
    Align = alLeft
    BevelOuter = bvNone
    TabOrder = 1
    ExplicitHeight = 447
    object infoPanelTare1: TPanel
      Left = 0
      Top = 0
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 0
      ExplicitWidth = 433
      object PanelTare1: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare1: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 1.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare1: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare1: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare1: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare1: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare1'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare0: TPanel
      Left = 0
      Top = 370
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 1
      ExplicitWidth = 433
      object PanelTare0: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare0: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 0.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare0: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 4
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare0: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare0: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare0: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare0'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare2: TPanel
      Left = 0
      Top = 37
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 2
      ExplicitWidth = 433
      object PanelTare2: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare2: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 2.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare2: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare2: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare2: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare2: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare2'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare5: TPanel
      Left = 0
      Top = 148
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 3
      ExplicitWidth = 433
      object PanelTare5: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare5: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 5.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare5: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare5: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare5: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare5: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare5'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare4: TPanel
      Left = 0
      Top = 111
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 4
      ExplicitWidth = 433
      object PanelTare4: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare4: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 4.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare4: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare4: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare4: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare4: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare4'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare3: TPanel
      Left = 0
      Top = 74
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 5
      ExplicitWidth = 433
      object PanelTare3: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare3: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 3.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare3: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare3: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare3: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare3: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare3'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare6: TPanel
      Left = 0
      Top = 185
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 6
      ExplicitWidth = 433
      object PanelTare6: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare6: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 6.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare6: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare6: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare6: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare6: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare6'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare10: TPanel
      Left = 0
      Top = 333
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 7
      ExplicitWidth = 433
      object PanelTare10: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare10: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 10.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 87
        end
        object EditTare10: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare10: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare10: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare10: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare10'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare9: TPanel
      Left = 0
      Top = 296
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 8
      ExplicitWidth = 433
      object PanelTare9: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare9: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 9.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare9: TcxCurrencyEdit
          Left = 5
          Top = 13
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare9: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare9: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare9: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare9'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare8: TPanel
      Left = 0
      Top = 259
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 9
      ExplicitWidth = 433
      object PanelTare8: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare8: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 8.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare8: TcxCurrencyEdit
          Left = 5
          Top = 13
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare8: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare8: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare8: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare8'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare7: TPanel
      Left = 0
      Top = 222
      Width = 425
      Height = 37
      Align = alTop
      TabOrder = 10
      ExplicitWidth = 433
      object PanelTare7: TPanel
        Left = 1
        Top = 1
        Width = 315
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        ExplicitWidth = 323
        object LabelTare7: TLabel
          Left = 0
          Top = 0
          Width = 315
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 7.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 81
        end
        object EditTare7: TcxCurrencyEdit
          Left = 5
          Top = 13
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          TabOrder = 0
          Width = 100
        end
      end
      object infoPanelWeightTare7: TPanel
        Left = 316
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 324
        object LabelWeightTare7: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare7: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare7'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
  end
  object infoPanelPartion: TPanel
    Left = 390
    Top = 0
    Width = 170
    Height = 411
    Align = alRight
    BevelOuter = bvNone
    TabOrder = 2
    ExplicitTop = -6
    object Panel1: TPanel
      Left = 0
      Top = 362
      Width = 170
      Height = 49
      Align = alBottom
      TabOrder = 0
      ExplicitTop = 329
      object Label1: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1042#1077#1089' '#1053#1077#1090#1090#1086' '#1048#1058#1054#1043#1054
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 93
      end
      object PanelWeightGoods_total: TPanel
        Left = 1
        Top = 15
        Width = 168
        Height = 33
        Align = alClient
        BevelOuter = bvNone
        Caption = 'PanelWeightGoods_total'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
      end
    end
    object Panel3: TPanel
      Left = 0
      Top = 313
      Width = 170
      Height = 49
      Align = alBottom
      TabOrder = 1
      ExplicitTop = 280
      object Label2: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1042#1077#1089' '#1090#1072#1088#1099' '#1048#1058#1054#1043#1054
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 89
      end
      object PanelWeightTare_total: TPanel
        Left = 1
        Top = 15
        Width = 168
        Height = 33
        Align = alClient
        BevelOuter = bvNone
        Caption = 'PanelWeightTare_total'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
      end
    end
    object PanelPartionDate: TPanel
      Left = 0
      Top = 0
      Width = 170
      Height = 49
      Align = alTop
      BevelInner = bvRaised
      BevelOuter = bvNone
      TabOrder = 2
      object LabelPartionDate: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = '   '#1055#1072#1088#1090#1080#1103' '#1079#1072
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 62
      end
      object PartionDateEdit: TcxDateEdit
        Left = 23
        Top = 15
        EditValue = 41640d
        ParentFont = False
        Properties.DateButtons = [btnToday]
        Properties.SaveTime = False
        Properties.ShowTime = False
        Style.Font.Charset = RUSSIAN_CHARSET
        Style.Font.Color = clBlack
        Style.Font.Height = -12
        Style.Font.Name = 'Arial'
        Style.Font.Style = [fsBold]
        Style.IsFontAssigned = True
        TabOrder = 0
        Width = 120
      end
    end
    object AssetPanel: TPanel
      Left = 0
      Top = 49
      Width = 170
      Height = 49
      Align = alTop
      Alignment = taLeftJustify
      TabOrder = 3
      object AssetLabel: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1042#1099#1073#1086#1088' '#1071#1095#1077#1081#1082#1072' '#8470
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 95
      end
      object EditPartionCell: TcxButtonEdit
        Left = 4
        Top = 18
        ParentFont = False
        Properties.Buttons = <
          item
            Default = True
            Kind = bkEllipsis
          end>
        Properties.ReadOnly = True
        Style.Font.Charset = RUSSIAN_CHARSET
        Style.Font.Color = clBlack
        Style.Font.Height = -11
        Style.Font.Name = 'Arial'
        Style.Font.Style = [fsBold]
        Style.IsFontAssigned = True
        TabOrder = 0
        Text = 'EditPartionCell'
        Width = 163
      end
    end
  end
end
