inherited DialogTareForm: TDialogTareForm
  Caption = #1055#1086#1076#1090#1074#1077#1088#1078#1076#1077#1085#1080#1077
  ClientHeight = 460
  ClientWidth = 620
  OldCreateOrder = True
  Position = poScreenCenter
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  ExplicitWidth = 636
  ExplicitHeight = 499
  PixelsPerInch = 96
  TextHeight = 14
  inherited bbPanel: TPanel
    Top = 419
    Width = 620
    ExplicitTop = 419
    ExplicitWidth = 620
    inherited bbOk: TBitBtn
      Left = 27
      Default = False
      ExplicitLeft = 27
    end
    inherited bbCancel: TBitBtn
      Left = 148
      Kind = bkCustom
      ExplicitLeft = 148
    end
  end
  object infoPanelTareFix: TPanel
    Left = 0
    Top = 0
    Width = 450
    Height = 419
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object infoPanelTare1: TPanel
      Left = 0
      Top = 0
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 0
      object PanelTare1: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare1: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 1.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare1: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare1KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare1: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare1: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object EditWeightTare1: TcxCurrencyEdit
          Left = 9
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 4
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditWeightTare1KeyDown
          Width = 95
        end
      end
    end
    object infoPanelTare0: TPanel
      Left = 0
      Top = 370
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 1
      object PanelTare0: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare0: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 0.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare0: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 4
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare0KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare0: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare0: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare0: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare0'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare2: TPanel
      Left = 0
      Top = 37
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 2
      object PanelTare2: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare2: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 2.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare2: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare2KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare2: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare2: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object EditWeightTare2: TcxCurrencyEdit
          Left = 9
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 4
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditWeightTare2KeyDown
          Width = 95
        end
      end
    end
    object infoPanelTare5: TPanel
      Left = 0
      Top = 148
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 3
      object PanelTare5: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare5: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 5.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare5: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare5KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare5: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare5: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare5: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare5'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare4: TPanel
      Left = 0
      Top = 111
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 4
      object PanelTare4: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare4: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 4.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare4: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare4KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare4: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare4: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare4: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare4'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare3: TPanel
      Left = 0
      Top = 74
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 5
      object PanelTare3: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare3: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 3.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare3: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare3KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare3: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare3: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare3: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare3'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare6: TPanel
      Left = 0
      Top = 185
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 6
      object PanelTare6: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare6: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 6.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare6: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare6KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare6: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare6: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare6: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare6'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare10: TPanel
      Left = 0
      Top = 333
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 7
      object PanelTare10: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare10: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 10.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 94
        end
        object EditTare10: TcxCurrencyEdit
          Left = 5
          Top = 12
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare10KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare10: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare10: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare10: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare10'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare9: TPanel
      Left = 0
      Top = 296
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 8
      object PanelTare9: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare9: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 9.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare9: TcxCurrencyEdit
          Left = 5
          Top = 13
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare9KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare9: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare9: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare9: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare9'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare8: TPanel
      Left = 0
      Top = 259
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 9
      object PanelTare8: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare8: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 8.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare8: TcxCurrencyEdit
          Left = 5
          Top = 13
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare8KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare8: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare8: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare8: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare8'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
    object infoPanelTare7: TPanel
      Left = 0
      Top = 222
      Width = 450
      Height = 37
      Align = alTop
      TabOrder = 10
      object PanelTare7: TPanel
        Left = 1
        Top = 1
        Width = 340
        Height = 35
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object LabelTare7: TLabel
          Left = 0
          Top = 0
          Width = 340
          Height = 14
          Align = alTop
          Caption = #1050#1086#1083'-'#1074#1086' '#1087#1086' 7.0 '#1082#1075
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ExplicitWidth = 88
        end
        object EditTare7: TcxCurrencyEdit
          Left = 5
          Top = 13
          Properties.Alignment.Horz = taRightJustify
          Properties.Alignment.Vert = taVCenter
          Properties.AssignedValues.DisplayFormat = True
          Properties.DecimalPlaces = 0
          Properties.OnChange = EditTare1PropertiesChange
          TabOrder = 0
          OnEnter = EditTare1Enter
          OnExit = EditTare1Exit
          OnKeyDown = EditTare7KeyDown
          Width = 100
        end
      end
      object infoPanelWeightTare7: TPanel
        Left = 341
        Top = 1
        Width = 108
        Height = 35
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        object LabelWeightTare7: TLabel
          Left = 0
          Top = 0
          Width = 108
          Height = 14
          Align = alTop
          Alignment = taCenter
          Caption = #1042#1077#1089
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = []
          ParentFont = False
          ExplicitWidth = 19
        end
        object PanelWeightTare7: TPanel
          Left = 0
          Top = 14
          Width = 108
          Height = 21
          Align = alClient
          BevelOuter = bvNone
          Caption = 'PanelWeightTare7'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clNavy
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          TabOrder = 0
        end
      end
    end
  end
  object infoPanelPartion: TPanel
    Left = 450
    Top = 0
    Width = 170
    Height = 419
    Align = alRight
    BevelOuter = bvNone
    TabOrder = 2
    object Panel1: TPanel
      Left = 0
      Top = 321
      Width = 170
      Height = 49
      Align = alBottom
      TabOrder = 0
      object Label1: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1042#1077#1089' '#1053#1077#1090#1090#1086' '#1048#1058#1054#1043#1054
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 93
      end
      object PanelWeightGoods_total: TPanel
        Left = 1
        Top = 15
        Width = 168
        Height = 33
        Align = alClient
        BevelOuter = bvNone
        Caption = 'PanelWeightGoods_total'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
      end
    end
    object Panel3: TPanel
      Left = 0
      Top = 272
      Width = 170
      Height = 49
      Align = alBottom
      TabOrder = 1
      object Label2: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1042#1077#1089' '#1090#1072#1088#1099' '#1048#1058#1054#1043#1054
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 89
      end
      object PanelWeightTare_total: TPanel
        Left = 1
        Top = 15
        Width = 168
        Height = 33
        Align = alClient
        BevelOuter = bvNone
        Caption = 'PanelWeightTare_total'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
      end
    end
    object PanelPartionDate: TPanel
      Left = 0
      Top = 0
      Width = 170
      Height = 49
      Align = alTop
      BevelInner = bvRaised
      BevelOuter = bvNone
      TabOrder = 2
      object LabelPartionDate: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = '   '#1055#1072#1088#1090#1080#1103' '#1079#1072
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 62
      end
      object PartionDateEdit: TcxDateEdit
        Left = 23
        Top = 17
        EditValue = 41640d
        ParentFont = False
        Properties.DateButtons = [btnToday]
        Properties.ReadOnly = True
        Properties.SaveTime = False
        Properties.ShowTime = False
        Style.Font.Charset = RUSSIAN_CHARSET
        Style.Font.Color = clBlack
        Style.Font.Height = -12
        Style.Font.Name = 'Arial'
        Style.Font.Style = [fsBold]
        Style.IsFontAssigned = True
        TabOrder = 0
        Width = 120
      end
    end
    object AssetPanel: TPanel
      Left = 0
      Top = 49
      Width = 170
      Height = 49
      Align = alTop
      Alignment = taLeftJustify
      TabOrder = 3
      object AssetLabel: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1042#1099#1073#1086#1088' '#1071#1095#1077#1081#1082#1072' '#8470
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 95
      end
      object EditPartionCell: TcxButtonEdit
        Left = 4
        Top = 21
        ParentFont = False
        Properties.Buttons = <
          item
            Default = True
            Kind = bkEllipsis
          end>
        Properties.ReadOnly = True
        Properties.OnButtonClick = EditPartionCellPropertiesButtonClick
        Style.Font.Charset = RUSSIAN_CHARSET
        Style.Font.Color = clBlack
        Style.Font.Height = -11
        Style.Font.Name = 'Arial'
        Style.Font.Style = [fsBold]
        Style.IsFontAssigned = True
        TabOrder = 0
        Text = 'EditPartionCell'
        OnKeyDown = EditPartionCellKeyDown
        Width = 163
      end
    end
    object Panel2: TPanel
      Left = 0
      Top = 223
      Width = 170
      Height = 49
      Align = alBottom
      TabOrder = 4
      object Label3: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1050#1086#1083'-'#1074#1086' '#1090#1072#1088#1099
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 69
      end
      object PanelCounttTare_total: TPanel
        Left = 1
        Top = 15
        Width = 168
        Height = 33
        Align = alClient
        BevelOuter = bvNone
        Caption = 'PanelCounttTare_total'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
      end
    end
    object Panel4: TPanel
      Left = 0
      Top = 370
      Width = 170
      Height = 49
      Align = alBottom
      TabOrder = 5
      object Label4: TLabel
        Left = 1
        Top = 1
        Width = 168
        Height = 14
        Align = alTop
        Alignment = taCenter
        Caption = #1048#1058#1054#1043#1054' '#1096#1090'.'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clBlue
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        ExplicitWidth = 55
      end
      object PanelShGoods_total: TPanel
        Left = 1
        Top = 15
        Width = 168
        Height = 33
        Align = alClient
        BevelOuter = bvNone
        Caption = 'PanelShGoods_total'
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clNavy
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
      end
    end
  end
  object spSelect: TdsdStoredProc
    DataSet = CDS
    DataSets = <
      item
        DataSet = CDS
      end>
    Params = <>
    PackSize = 1
    Left = 264
    Top = 296
  end
  object CDS: TClientDataSet
    Aggregates = <>
    Params = <>
    Left = 272
    Top = 384
  end
end
