GRANT ALL ON ALL TABLES IN SCHEMA public TO Project_Merlin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO Project_Merlin;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO Project_Merlin;
CREATE EXTENSION tablefunc;
