unit SaleJournal;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, AncestorJournal, cxGraphics, cxControls,
  cxLookAndFeels, cxLookAndFeelPainters, cxPCdxBarPopupMenu, cxStyles,
  cxCustomData, cxFilter, cxData, cxDataStorage, cxEdit, Data.DB, cxDBData,
  cxImageComboBox, cxContainer, Vcl.ComCtrls, dxCore, cxDateUtils,
  dxSkinsdxBarPainter, dsdAddOn, ChoicePeriod, Vcl.Menus, dxBarExtItems, dxBar,
  cxClasses, dsdDB, Datasnap.DBClient, dsdAction, Vcl.ActnList,
  cxPropertiesStore, cxLabel, cxTextEdit, cxMaskEdit, cxDropDownEdit,
  cxCalendar, Vcl.ExtCtrls, cxGridLevel, cxGridCustomTableView, cxGridTableView,
  cxGridDBTableView, cxGridCustomView, cxGrid, cxPC, cxCheckBox, cxCurrencyEdit,
  cxButtonEdit, dsdGuides, frxClass, frxDBSet, dxSkinsCore,
  dxSkinsDefaultPainters, dxSkinscxPCPainter, EDI, dxSkinBlack, dxSkinBlue,
  dxSkinBlueprint, dxSkinCaramel, dxSkinCoffee, dxSkinDarkRoom, dxSkinDarkSide,
  dxSkinDevExpressDarkStyle, dxSkinDevExpressStyle, dxSkinFoggy,
  dxSkinGlassOceans, dxSkinHighContrast, dxSkiniMaginary, dxSkinLilian,
  dxSkinLiquidSky, dxSkinLondonLiquidSky, dxSkinMcSkin, dxSkinMoneyTwins,
  dxSkinOffice2007Black, dxSkinOffice2007Blue, dxSkinOffice2007Green,
  dxSkinOffice2007Pink, dxSkinOffice2007Silver, dxSkinOffice2010Black,
  dxSkinOffice2010Blue, dxSkinOffice2010Silver, dxSkinPumpkin, dxSkinSeven,
  dxSkinSevenClassic, dxSkinSharp, dxSkinSharpPlus, dxSkinSilver,
  dxSkinSpringTime, dxSkinStardust, dxSkinSummer2008, dxSkinTheAsphaltWorld,
  dxSkinValentine, dxSkinVS2010, dxSkinWhiteprint, dxSkinXmas2008Blue,
  dsdInternetAction, MeDOC, dsdCommon;

type
  TSaleJournalForm = class(TAncestorJournalForm)
    OperDatePartner: TcxGridDBColumn;
    FromName: TcxGridDBColumn;
    ToName: TcxGridDBColumn;
    TotalCount: TcxGridDBColumn;
    TotalCountPartner: TcxGridDBColumn;
    TotalSumm: TcxGridDBColumn;
    ChangePercent: TcxGridDBColumn;
    PriceWithVAT: TcxGridDBColumn;
    VATPercent: TcxGridDBColumn;
    TotalSummVAT: TcxGridDBColumn;
    TotalSummMVAT: TcxGridDBColumn;
    TotalSummPVAT: TcxGridDBColumn;
    PaidKindName: TcxGridDBColumn;
    ContractName: TcxGridDBColumn;
    InvNumberOrder: TcxGridDBColumn;
    Checked: TcxGridDBColumn;
    edIsPartnerDate: TcxCheckBox;
    InfoMoneyGroupName: TcxGridDBColumn;
    InfoMoneyDestinationName: TcxGridDBColumn;
    InfoMoneyCode: TcxGridDBColumn;
    InfoMoneyName: TcxGridDBColumn;
    spTax: TdsdStoredProc;
    actTax: TdsdExecStoredProc;
    bbTax: TdxBarButton;
    cxLabel14: TcxLabel;
    edDocumentTaxKind: TcxButtonEdit;
    DocumentTaxKindGuides: TdsdGuides;
    InvNumberPartner_Master: TcxGridDBColumn;
    DocumentTaxKindName: TcxGridDBColumn;
    OKPO_To: TcxGridDBColumn;
    JuridicalName_To: TcxGridDBColumn;
    InvNumberPartner: TcxGridDBColumn;
    TotalCountTare: TcxGridDBColumn;
    TotalCountSh: TcxGridDBColumn;
    TotalCountKg: TcxGridDBColumn;
    PrintHeaderCDS: TClientDataSet;
    PrintItemsCDS: TClientDataSet;
    spSelectPrint: TdsdStoredProc;
    spSelectTax_Client: TdsdStoredProc;
    spSelectTax_Us: TdsdStoredProc;
    spGetReporNameTax: TdsdStoredProc;
    spGetReportName: TdsdStoredProc;
    mactPrint_Sale: TMultiAction;
    mactPrint_Tax_Us: TMultiAction;
    mactPrint_Tax_Client: TMultiAction;
    actPrintTax_Us: TdsdPrintAction;
    actPrintTax_Client: TdsdPrintAction;
    actPrint: TdsdPrintAction;
    actSPPrintSaleProcName: TdsdExecStoredProc;
    actPrint_Tax_ReportName: TdsdExecStoredProc;
    bbPrint: TdxBarButton;
    bbPrintTax_Us: TdxBarButton;
    bbPrintTax_Client: TdxBarButton;
    spGetReporNameBill: TdsdStoredProc;
    actPrint_Account_ReportName: TdsdExecStoredProc;
    actPrint_Account: TdsdPrintAction;
    mactPrint_Account: TMultiAction;
    bbPrint_Bill: TdxBarButton;
    PrintItemsSverkaCDS: TClientDataSet;
    IsError: TcxGridDBColumn;
    actMovementCheck: TdsdOpenForm;
    bbMovementCheck: TdxBarButton;
    IsEDI: TcxGridDBColumn;
    spChecked: TdsdStoredProc;
    bbspChecked: TdxBarButton;
    actChecked: TdsdExecStoredProc;
    CurrencyDocumentName: TcxGridDBColumn;
    CurrencyPartnerName: TcxGridDBColumn;
    RouteName: TcxGridDBColumn;
    actPrint_ExpInvoice: TdsdPrintAction;
    actPrint_ExpPack: TdsdPrintAction;
    bbPrint_Invoice: TdxBarButton;
    bbPrint_Pack: TdxBarButton;
    spSelectPrint_ExpPack: TdsdStoredProc;
    spSelectPrint_Pack: TdsdStoredProc;
    spSelectPrint_Spec: TdsdStoredProc;
    actPrint_Spec: TdsdPrintAction;
    actPrint_Pack: TdsdPrintAction;
    bbPrint_Pack21: TdxBarButton;
    bbPrint_Pack22: TdxBarButton;
    spSelectPrint_ExpInvoice: TdsdStoredProc;
    TotalSummCurrency: TcxGridDBColumn;
    CurrencyValue: TcxGridDBColumn;
    ParValue: TcxGridDBColumn;
    CurrencyPartnerValue: TcxGridDBColumn;
    ParPartnerValue: TcxGridDBColumn;
    bbPrint_Spec: TdxBarButton;
    actPrint_ExpSpec: TdsdPrintAction;
    IsMedoc: TcxGridDBColumn;
    actPrint_TTN: TdsdPrintAction;
    spSelectPrint_TTN: TdsdStoredProc;
    bbTTN: TdxBarButton;
    EdiOrdspr: TcxGridDBColumn;
    EdiInvoice: TcxGridDBColumn;
    EdiDesadv: TcxGridDBColumn;
    actPrint_QualityDoc: TdsdPrintAction;
    spSelectPrint_Quality: TdsdStoredProc;
    bbPrint_Quality: TdxBarButton;
    InvNumber_TransportGoods: TcxGridDBColumn;
    OperDate_TransportGoods: TcxGridDBColumn;
    actDialog_TTN: TdsdOpenForm;
    spGet_TTN: TdsdStoredProc;
    actGet_TTN: TdsdExecStoredProc;
    mactPrint_TTN: TMultiAction;
    PaymentDate: TcxGridDBColumn;
    InsertDate: TcxGridDBColumn;
    EDI: TEDI;
    spUpdateEdiOrdspr: TdsdStoredProc;
    spUpdateEdiInvoice: TdsdStoredProc;
    spUpdateEdiDesadv: TdsdStoredProc;
    actInvoice: TEDIAction;
    actOrdSpr: TEDIAction;
    actDesadv: TEDIAction;
    actUpdateEdiDesadvTrue: TdsdExecStoredProc;
    actUpdateEdiInvoiceTrue: TdsdExecStoredProc;
    actUpdateEdiOrdsprTrue: TdsdExecStoredProc;
    spGetDefaultEDI: TdsdStoredProc;
    actSetDefaults: TdsdExecStoredProc;
    mactInvoice: TMultiAction;
    mactOrdSpr: TMultiAction;
    mactDesadv: TMultiAction;
    bbInvoice: TdxBarButton;
    bbOrdSpr: TdxBarButton;
    bbDesadv: TdxBarButton;
    N13: TMenuItem;
    miInvoice: TMenuItem;
    miOrdSpr: TMenuItem;
    miDesadv: TMenuItem;
    actExecPrint_EDI: TdsdExecStoredProc;
    isEdiOrdspr_partner: TcxGridDBColumn;
    isEdiInvoice_partner: TcxGridDBColumn;
    isEdiDesadv_partner: TcxGridDBColumn;
    Comment: TcxGridDBColumn;
    mactInvoice_Simple: TMultiAction;
    mactInvoice_All: TMultiAction;
    mactOrdSpr_Simple: TMultiAction;
    mactOrdSpr_All: TMultiAction;
    mactDesadv_Simple: TMultiAction;
    mactDesadv_All: TMultiAction;
    spSelectPrint_SaleOrder: TdsdStoredProc;
    actPrintSaleOrder: TdsdPrintAction;
    MovementId_Order: TcxGridDBColumn;
    bbPrintSaleOrder: TdxBarButton;
    spSelectSale_EDI: TdsdStoredProc;
    cxLabel3: TcxLabel;
    edTo: TcxButtonEdit;
    mactUpdateMovementDesc: TMultiAction;
    actUpdateMovementDesc: TdsdExecStoredProc;
    spUpdateMovementDesc: TdsdStoredProc;
    GuidesTo: TdsdGuides;
    bbUpdateMovementDesc: TdxBarButton;
    PersonalName: TcxGridDBColumn;
    RouteGroupName: TcxGridDBColumn;
    InvNumber_Transport: TcxGridDBColumn;
    OperDate_Transport: TcxGridDBColumn;
    CarName: TcxGridDBColumn;
    CarModelName: TcxGridDBColumn;
    PersonalDriverName: TcxGridDBColumn;
    spSelectPrintReturnInDay: TdsdStoredProc;
    actPrintReturnInDay: TdsdPrintAction;
    bbPrintReturnInDay: TdxBarButton;
    actDialog_QualityDoc: TdsdOpenForm;
    mactPrint_QualityDoc: TMultiAction;
    isPromo: TcxGridDBColumn;
    MovementPromo: TcxGridDBColumn;
    spSavePrintState: TdsdStoredProc;
    actSPSavePrintState: TdsdExecStoredProc;
    spElectron: TdsdStoredProc;
    actElectron: TdsdExecStoredProc;
    bbElectron: TdxBarButton;
    spGetReportNameTransport: TdsdStoredProc;
    actPrint_Transport_ReportName: TdsdExecStoredProc;
    actPrint_Transport: TdsdPrintAction;
    mactPrint_Transport: TMultiAction;
    bbPrint_Transport: TdxBarButton;
    ExecuteDialog: TExecuteDialog;
    actShowMessage: TShowMessageAction;
    actOpenReportForm: TdsdOpenForm;
    bbOpenReportForm: TdxBarButton;
    ReestrKindName: TcxGridDBColumn;
    actPrint_Total: TdsdPrintAction;
    mactPrint_Sale_Total: TMultiAction;
    bbPrint_Sale_Total: TdxBarButton;
    spSelectPrint_Total: TdsdStoredProc;
    cxLabel27: TcxLabel;
    edJuridicalBasis: TcxButtonEdit;
    JuridicalBasisGuides: TdsdGuides;
    spGet_UserJuridicalBasis: TdsdStoredProc;
    actRefreshStart: TdsdDataSetRefresh;
    actPrintPack: TdsdPrintAction;
    macPrintPack: TMultiAction;
    macPrintPacklist: TMultiAction;
    bbPrintPacklist: TdxBarButton;
    actPrintPack_Transport: TdsdPrintAction;
    macPrintPack_Transport: TMultiAction;
    macPrintPackList_Transport: TMultiAction;
    bbPackList_Transport: TdxBarButton;
    N14: TMenuItem;
    N15: TMenuItem;
    spSelectPrint_Total_To: TdsdStoredProc;
    bbPrint_Sale_Total_To: TdxBarButton;
    actPrint_Total_To: TdsdPrintAction;
    mactPrint_Sale_Total_To: TMultiAction;
    spInsert_LockUnique: TdsdStoredProc;
    mactPrint_Sale_Total_List: TMultiAction;
    spSelectPrint_Total_List: TdsdStoredProc;
    actPrint_Total_List: TdsdPrintAction;
    actInsert_LockUnique: TdsdExecStoredProc;
    bbPrint_Sale_Total_List: TdxBarButton;
    macInsert_LockUnique: TMultiAction;
    spDelete_LockUnique: TdsdStoredProc;
    actDelete_LockUnique: TdsdExecStoredProc;
    actPrint_Account_List: TdsdPrintAction;
    mactPrint_Account_List: TMultiAction;
    bbPrint_Account_List: TdxBarButton;
    actPrintPackGross: TdsdPrintAction;
    bbPrintPackGross: TdxBarButton;
    actPrintSaleOrderTax: TdsdPrintAction;
    spSelectPrint_SaleOrderTax: TdsdStoredProc;
    bbPrintSaleOrderTax: TdxBarButton;
    bbPrint_PackWeight: TdxBarButton;
    actPrint_PackWeight: TdsdPrintAction;
    spGetReportNameQuality: TdsdStoredProc;
    actPrint_Quality_ReportName: TdsdExecStoredProc;
    spSelectPrint_TTN2: TdsdStoredProc;
    mactPrint_TTN2: TMultiAction;
    actPrint_TTN2: TdsdPrintAction;
    bbPrint_TTN2: TdxBarButton;
    ExportXmlGrid: TcxGrid;
    ExportXmlGridDBTableView: TcxGridDBTableView;
    RowData: TcxGridDBColumn;
    ExportXmlGridLevel: TcxGridLevel;
    spSelect_Export: TdsdStoredProc;
    spUpdate_isMail: TdsdStoredProc;
    spGet_Export_Email: TdsdStoredProc;
    ExportCDS: TClientDataSet;
    ExportDS: TDataSource;
    ExportEmailDS: TDataSource;
    ExportEmailCDS: TClientDataSet;
    actGet_Export_Email: TdsdExecStoredProc;
    actSelect_Export: TdsdExecStoredProc;
    actExport_Grid: TExportGrid;
    actSMTPFile: TdsdSMTPFileAction;
    actUpdate_isMail: TdsdExecStoredProc;
    spGet_Export_FileName: TdsdStoredProc;
    actGet_Export_FileName: TdsdExecStoredProc;
    mactExport: TMultiAction;
    macExportAll: TMultiAction;
    bbExport: TdxBarButton;
    spSelectPrint_two: TdsdStoredProc;
    actPrint_two: TdsdPrintAction;
    mactPrint_QualityDoc_two: TMultiAction;
    bbPrint_QualityDoc_two: TdxBarButton;
    PersonalDriverName_TTN: TcxGridDBColumn;
    PersonalName_4_TTN: TcxGridDBColumn;
    spGetReporNameTTN: TdsdStoredProc;
    actSPPrintTTNProcName: TdsdExecStoredProc;
    spUpdateMI_Sale_PriceIn: TdsdStoredProc;
    actUpdateMI_Sale_PriceIn: TdsdExecStoredProc;
    macUpdateMI_Sale_PriceIn_list: TMultiAction;
    macUpdateMI_Sale_PriceIn: TMultiAction;
    bbUpdateMI_Sale_PriceIn: TdxBarButton;
    isPav: TcxGridDBColumn;
    spUpdateIsMedoc: TdsdStoredProc;
    actUpdateIsMedoc: TdsdExecStoredProc;
    actSelect_Medoc: TdsdExecStoredProc;
    MedocAction: TMedocAction;
    mactMeDoc: TMultiAction;
    bbmactMeDoc: TdxBarButton;
    spGetDirectoryName: TdsdStoredProc;
    actGetDirectory: TdsdExecStoredProc;
    actSelect_Medoc_list: TdsdExecStoredProc;
    MedocListAction: TMedocAction;
    mactMEDOCGrid: TMultiAction;
    mactMedocALL: TMultiAction;
    actRoundAmountPartner: TdsdExecStoredProc;
    macRoundAmountPartner_list: TMultiAction;
    macRoundAmountPartner: TMultiAction;
    spUpdate_MI_AmountPartner_round: TdsdStoredProc;
    ExecuteDialogUpdateAmountPartner: TExecuteDialog;
    bbRoundAmountPartner: TdxBarButton;
    actPrintTEST: TdsdPrintAction;
    bbTEST: TdxBarButton;
    spSelectPrint_test: TdsdStoredProc;
    spGet_Export_FileNameXML: TdsdStoredProc;
    spSelectSale_xml: TdsdStoredProc;
    actGet_Export_FileNameXml: TdsdExecStoredProc;
    actExport_fileXml: TdsdStoredProcExportToFile;
    macExport_XML: TMultiAction;
    bbExport_XML: TdxBarButton;
    spSelectPrintBox: TdsdStoredProc;
    actPrintBox: TdsdPrintAction;
    bbPrintBox: TdxBarButton;
    actFileDirectoryDialog: TFileDialogAction;
    spGet_Export_FileName_2: TdsdStoredProc;
    actGet_Export_FileName_fromMail: TdsdExecStoredProc;
    actExport_file_fromEmail: TdsdStoredProcExportToFile;
    macExportFile_fromMail: TMultiAction;
    macExportFile_fromMail_All: TMultiAction;
    bbExportFile_fromMail_All: TdxBarButton;
    edInvNumberTransport: TcxButtonEdit;
    cxLabel30: TcxLabel;
    GuidesTransport: TdsdGuides;
    spInsertUpdate_TTN_byTransport: TdsdStoredProc;
    spInsertUpdate_Quality_byTransport: TdsdStoredProc;
    actInsertUpdate_Quality_byTransport: TdsdExecStoredProc;
    actInsertUpdate_TTN_byTransport: TdsdExecStoredProc;
    macPrint_Group_list: TMultiAction;
    spGetReporNameTTN_list: TdsdStoredProc;
    spGetReportNameQuality_list: TdsdStoredProc;
    actSPPrintTTNProcName_list: TdsdExecStoredProc;
    actPrint_TTN_copy2_list: TdsdPrintAction;
    spSelectPrint_TTN_list: TdsdStoredProc;
    spSelectPrint_Quality_list: TdsdStoredProc;
    macPrint_TTN_Copy2_list: TMultiAction;
    macPrint_QualityDoc_list: TMultiAction;
    actPrint_Quality_ReportName_list: TdsdExecStoredProc;
    actPrint_QualityDoc_list: TdsdPrintAction;
    bbPrint_Group: TdxBarButton;
    macPrint_Group: TMultiAction;
    mactPrint_Sale_list: TMultiAction;
    actOpenChoicePriceList: TOpenChoiceForm;
    spUpdate_PriceList: TdsdStoredProc;
    actUpdate_PriceList: TdsdExecStoredProc;
    macUpdate_PriceList_list: TMultiAction;
    macUpdate_PriceList: TMultiAction;
    bbUpdate_PriceList: TdxBarButton;
    macPrint_Group_cash: TMultiAction;
    macPrint_Group_list_cash: TMultiAction;
    macPrintPack_2copy: TMultiAction;
    actPrintPack_2copy: TdsdPrintAction;
    bbPrint_Group_cash: TdxBarButton;
    bbsPrint: TdxBarSubItem;
    bbsPrintGroup: TdxBarSubItem;
    bbSeparator: TdxBarSeparator;
    bbsSend: TdxBarSubItem;
    bbsEdit: TdxBarSubItem;
    bbsUnLoad: TdxBarSubItem;
    macPrint_Group_cash_Ret: TMultiAction;
    spUpdatePrintAuto_False: TdsdStoredProc;
    actUpdatePrintAuto_False: TdsdExecStoredProc;
    actPrintReturnInDay_2copy: TdsdPrintAction;
    spUpdatePrintAuto_True: TdsdStoredProc;
    actUpdatePrintAuto_True: TdsdExecStoredProc;
    bbPrint_Group_cash_Ret: TdxBarButton;
    macPrint_Group_list_cash_Ret: TMultiAction;
    macPrint_Sale2_TTN_Quality_list: TMultiAction;
    macPrint_TTN_Copy1_list: TMultiAction;
    macPrint_Sale2_TTN_Quality: TMultiAction;
    macPrint_Sale3_TTN_Quality: TMultiAction;
    actPrintPack_3copy: TdsdPrintAction;
    macPrintPack_3copy: TMultiAction;
    macPrint_Sale3_TTN_Quality_list: TMultiAction;
    bbPrint_Sale2_TTN_Quality: TdxBarButton;
    bbPrint_Sale3_TTN_Quality: TdxBarButton;
    actPrint_TTN_copy1_list: TdsdPrintAction;
    actPrint_TTN_copy3_list: TdsdPrintAction;
    macPrint_TTN_Copy3_list: TMultiAction;
    isTotalSumm_GoodsReal: TcxGridDBColumn;
    spUpdateTotalSumm_GoodsReal: TdsdStoredProc;
    actUpdateTotalSumm_GoodsReal: TdsdExecStoredProc;
    bbUpdateTotalSumm_GoodsReal: TdxBarButton;
    spSelectPrint_TTN_final: TdsdStoredProc;
    actPrint_TTN_final: TdsdPrintAction;
    macPrint_TTN_final: TMultiAction;
    bbPrint_TTN_final: TdxBarButton;
    spSelectPrintBoxTotal: TdsdStoredProc;
    actPrintBoxTotal: TdsdPrintAction;
    bbtPrintBoxTotal: TdxBarButton;
    spSelectPrintBox_PartnerTotal: TdsdStoredProc;
    actPrintBoxTotalPartner: TdsdPrintAction;
    bb: TdxBarButton;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

implementation

{$R *.dfm}
initialization
  RegisterClass(TSaleJournalForm);
end.
