BEGIN
	SELECT * FROM OBJECT WHERE Id =2 OR Id =1 FOR UPDATE ;
	UPDATE OBJECT SET isErased = false WHERE Id =2 ;
	UPDATE OBJECT SET isErased = false WHERE Id =1 ;

commit;

BEGIN
	SELECT * FROM OBJECT WHERE Id =1 or Id =2 FOR UPDATE ;
	UPDATE OBJECT SET isErased = FALSE WHERE Id =1 ;
	UPDATE OBJECT SET isErased = FALSE WHERE Id =2 ;
commit;