
-- farmacy-real - Днепр
CREATE OR REPLACE FUNCTION zc_Area_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (5803492); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

-- farmacy-test - Днепр
-- CREATE OR REPLACE FUNCTION zc_Area_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (3692911); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
