CREATE OR REPLACE FUNCTION zc_Enum_Process()
  RETURNS integer AS
$BODY$BEGIN
  RETURN 1;
END;  $BODY$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION zc_Enum_Role()
  RETURNS integer AS
$BODY$BEGIN
  RETURN 2;
END;  $BODY$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION zc_Enum_Process_User()
  RETURNS integer AS
$BODY$BEGIN
  RETURN 101;
END;  $BODY$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION zc_Enum_Role_Admin()
  RETURNS integer AS
$BODY$BEGIN
  RETURN 201;
END;  $BODY$ LANGUAGE plpgsql;
