GRANT ALL ON ALL TABLES IN SCHEMA public TO project;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO project;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO project;
CREATE EXTENSION tablefunc;
-- CREATE EXTENSION IF NOT EXISTS pgcrypto;