GRANT ALL ON ALL TABLES IN SCHEMA public TO project;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO project;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO project;
CREATE EXTENSION tablefunc;

GRANT ALL ON ALL TABLES IN SCHEMA _replica TO project;
GRANT ALL ON ALL SEQUENCES IN SCHEMA _replica TO project;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA _replica TO project;
GRANT ALL ON SCHEMA _replica TO project;

-- CREATE EXTENSION IF NOT EXISTS pgcrypto;