unit TestImportGroup;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  Authentication, TestFramework, dxSkinOffice2007Green, dxSkinXmas2008Blue, dsdDB, cxLookAndFeels,
  dxSkinDarkSide, cxGridCustomView, cxMaskEdit, dxSkinValentine, dxSkinCoffee,
  dxSkinSilver, dxSkinOffice2007Black, System.Classes, dxSkiniMaginary, cxNavigator,
  dsdAddOn, Vcl.StdActns, dxSkinsdxBarPainter, dxSkinBlueprint,
  cxCustomData, dxSkinDarkRoom, dxBarBuiltInMenu,
  dxSkinSummer2008, System.Variants, cxPropertiesStore,
  dxSkinsDefaultPainters, dxSkinPumpkin, Data.DB, cxData, cxBlobEdit, cxStyles,
  cxGridDBTableView, dxSkinDevExpressStyle, dxSkinSharp, dxBar, dxSkinBlue,
  dxSkinOffice2010Silver, Vcl.Menus, dsdGuides,
  cxDataStorage, dxSkinSevenClassic, ImportGroup,
  dxSkinTheAsphaltWorld, dxSkinSeven, dxSkinBlack, dxSkinLilian, cxGridLevel, cxPC,
  Vcl.Graphics, Vcl.Forms, dxSkinMoneyTwins,
  dxSkinGlassOceans, dxSkinFoggy, dxSkinSpringTime, dxSkinHighContrast, dxBarExtItems,
  dxSkinMcSkin, cxDropDownEdit, cxSplitter, cxGraphics,
  cxFilter, cxGrid, cxClasses, dsdAction, dxSkinLondonLiquidSky, dxSkinsCore,
  cxButtonEdit, ExternalLoad, dxSkinDevExpressDarkStyle,
  dxSkinscxPCPainter, dxSkinOffice2007Pink, cxEdit, Datasnap.DBClient, AncestorDBGrid,
  Vcl.Controls, cxPCdxBarPopupMenu, dxSkinStardust, cxGridCustomTableView,
  dxSkinCaramel, Winapi.Windows, cxControls, Winapi.Messages, dxSkinSharpPlus,
  dxSkinOffice2007Blue, cxLookAndFeelPainters, Vcl.Dialogs,
  dxSkinLiquidSky, dxSkinOffice2010Blue,
  dxSkinOffice2007Silver, dxSkinWhiteprint, Vcl.ActnList, cxLabel,
  dxSkinOffice2010Black, System.SysUtils, cxDBData,
  cxTextEdit, cxGridTableView, dxSkinVS2010, cxContainer;

type
  // Test methods for class TImportGroupForm

  TestTImportGroupForm = class(TTestCase)
  strict private
    ExecuteImportSettingsAction: TExecuteImportSettingsAction;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure Test;
  end;

implementation

uses Storage, UtilConst, CommonData;

procedure TestTImportGroupForm.SetUp;
begin
  TAuthentication.CheckLogin(TStorageFactory.GetStorage, 'Админ', gc_AdminPassword, gc_User);
  ExecuteImportSettingsAction := TExecuteImportSettingsAction.Create(nil);
  with ExecuteImportSettingsAction.ExternalParams.Add do
  begin
    Name := 'inAreaId';
    Value := 3692911;//NULL;
  end;
  //230529 фитолек
  //3711614 фитолек json
  //977312 бадм
  //3711645 бадм json
  ExecuteImportSettingsAction.ImportSettingsId.Value := 3711645;
end;

procedure TestTImportGroupForm.TearDown;
begin
  ExecuteImportSettingsAction.Free;
  ExecuteImportSettingsAction := nil;
end;

procedure TestTImportGroupForm.Test;
begin
  ExecuteImportSettingsAction.Execute;
end;

initialization
  TestFramework.RegisterTest('Загрузка прайса', TestTImportGroupForm.Suite);
end.

