CREATE OR REPLACE FUNCTION zc_isReturnIn_bySale() RETURNS Boolean AS $BODY$BEGIN RETURN (TRUE); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_isReturnInNAL_bySale() RETURNS TDateTime AS $BODY$BEGIN RETURN ('14.09.2016'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_isHistoryCost_byInfoMoneyDetail() RETURNS Boolean AS $BODY$BEGIN RETURN (TRUE AND zc_isHistoryCost()); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_isHistoryCost() RETURNS Boolean AS $BODY$BEGIN RETURN (TRUE); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_isEDISaveLocal() RETURNS Boolean AS $BODY$BEGIN RETURN (FALSE); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_isPromo_Sign_check() RETURNS Boolean AS $BODY$BEGIN RETURN (FALSE); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_DateEnd() RETURNS TDateTime AS $BODY$BEGIN RETURN ('01.01.2100'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateStart() RETURNS TDateTime AS $BODY$BEGIN RETURN ('01.01.2000'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_DateStart_PartionGoods() RETURNS TDateTime AS $BODY$BEGIN RETURN ('18.03.2013'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateStart_PartionGoods_20103() RETURNS TDateTime AS $BODY$BEGIN RETURN ('01.12.2021'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateStart_OperDatePartner() RETURNS TDateTime AS $BODY$BEGIN RETURN ('01.11.2018'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateStart_Tax_2018() RETURNS TDateTime AS $BODY$BEGIN RETURN ('01.12.2018'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateStart_PriceTruncate() RETURNS TDateTime AS $BODY$BEGIN RETURN ('07.05.2019'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateStart_Asset() RETURNS TDateTime AS $BODY$BEGIN RETURN ('31.08.2020'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_DateEnd_GoodsRus() RETURNS TDateTime AS $BODY$BEGIN RETURN ('22.03.2019'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_DateStart_ObjectCostOnUnit() RETURNS TDateTime AS $BODY$BEGIN RETURN ('01.10.2010'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_BarCodePref_Object() RETURNS TVarChar AS $BODY$BEGIN RETURN ('2010'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_BarCodePref_Movement() RETURNS TVarChar AS $BODY$BEGIN RETURN ('2020'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_BarCodePref_MI() RETURNS TVarChar AS $BODY$BEGIN RETURN ('203'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_Color_Goods_Additional() RETURNS Integer AS $BODY$BEGIN RETURN (14941410); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Goods_Alternative() RETURNS Integer AS $BODY$BEGIN RETURN (16380671); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Warning_Red() RETURNS Integer AS $BODY$BEGIN RETURN (255); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Warning_Navy() RETURNS Integer AS $BODY$BEGIN RETURN (9502720); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_FormClass_Income() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TIncomeForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_ReturnOut() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TReturnOutForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Inventory() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TInventoryForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Send() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TSendForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Loss() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TLossForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Check() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TCheckForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Sale() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TSaleForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_SendPartionDate() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TSendPartionDateForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Reprice() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TRepriceForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_OrderInternal() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TOrderInternalForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Over() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TOverForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_OrderExternal() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TOrderExternalForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_FormClass_Layout() RETURNS TVarChar AS $BODY$BEGIN RETURN ('TLayout_MovementForm'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
    
CREATE OR REPLACE FUNCTION zc_InvNumber_Status_UnComlete() RETURNS TVarChar AS $BODY$BEGIN RETURN ('***'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_InvNumber_Status_Erased()    RETURNS TVarChar AS $BODY$BEGIN RETURN ('---'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
    
-- Почта - !!! VOLATILE !!! - !!!ФЛП_Шапиро И А!!!
CREATE OR REPLACE FUNCTION zc_Mail_Host()     RETURNS TVarChar AS $BODY$BEGIN RETURN (/*'smtp.mail.ru'*/                 SELECT gpSelect.Value FROM gpSelect_Object_EmailSettings (inEmailId:= 0, inIsShowAll:= FALSE, inSession:= '') AS gpSelect WHERE gpSelect.EmailKindId = zc_Enum_EmailKind_OutReport() AND gpSelect.EmailToolsId = zc_Enum_EmailTools_Host() AND COALESCE (gpSelect.JuridicalId, 0) = /*393052*/ 0);     END; $BODY$ LANGUAGE PLPGSQL VOLATILE;
CREATE OR REPLACE FUNCTION zc_Mail_Port()     RETURNS Integer  AS $BODY$BEGIN RETURN (/*465*/                            SELECT gpSelect.Value FROM gpSelect_Object_EmailSettings (inEmailId:= 0, inIsShowAll:= FALSE, inSession:= '') AS gpSelect WHERE gpSelect.EmailKindId = zc_Enum_EmailKind_OutReport() AND gpSelect.EmailToolsId = zc_Enum_EmailTools_Port() AND COALESCE (gpSelect.JuridicalId, 0) = /*393052*/ 0);     END; $BODY$ LANGUAGE PLPGSQL VOLATILE;
CREATE OR REPLACE FUNCTION zc_Mail_From()     RETURNS TVarChar AS $BODY$BEGIN RETURN (/*'zakaz_family-neboley@mail.ru'*/ SELECT gpSelect.Value FROM gpSelect_Object_EmailSettings (inEmailId:= 0, inIsShowAll:= FALSE, inSession:= '') AS gpSelect WHERE gpSelect.EmailKindId = zc_Enum_EmailKind_OutReport() AND gpSelect.EmailToolsId = zc_Enum_EmailTools_Mail() AND COALESCE (gpSelect.JuridicalId, 0) = /*393052*/ 0);     END; $BODY$ LANGUAGE PLPGSQL VOLATILE;
CREATE OR REPLACE FUNCTION zc_Mail_User()     RETURNS TVarChar AS $BODY$BEGIN RETURN (/*'zakaz_family-neboley@mail.ru'*/ SELECT gpSelect.Value FROM gpSelect_Object_EmailSettings (inEmailId:= 0, inIsShowAll:= FALSE, inSession:= '') AS gpSelect WHERE gpSelect.EmailKindId = zc_Enum_EmailKind_OutReport() AND gpSelect.EmailToolsId = zc_Enum_EmailTools_User() AND COALESCE (gpSelect.JuridicalId, 0) = /*393052*/ 0);     END; $BODY$ LANGUAGE PLPGSQL VOLATILE;
CREATE OR REPLACE FUNCTION zc_Mail_Password() RETURNS TVarChar AS $BODY$BEGIN RETURN (/*'fgntrfghfdls6'*/                SELECT gpSelect.Value FROM gpSelect_Object_EmailSettings (inEmailId:= 0, inIsShowAll:= FALSE, inSession:= '') AS gpSelect WHERE gpSelect.EmailKindId = zc_Enum_EmailKind_OutReport() AND gpSelect.EmailToolsId = zc_Enum_EmailTools_Password() AND COALESCE (gpSelect.JuridicalId, 0) = /*393052*/ 0); END; $BODY$ LANGUAGE PLPGSQL VOLATILE;

-- Farmacy - Site
CREATE OR REPLACE FUNCTION zc_Member_Site() RETURNS TVarChar AS $BODY$BEGIN RETURN ('автоматический'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
-- CREATE OR REPLACE FUNCTION zc_Area_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (5803492); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

/*
-- Значения для эти ф-ций будут сформированы в Load_PostgreSql, или !!!руками значения =0!!!
CREATE OR REPLACE FUNCTION zfCalc_UserMain() RETURNS Integer AS $BODY$BEGIN RETURN (6604558); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Measure_Kg() RETURNS Integer AS $BODY$BEGIN RETURN (1822); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Measure_Kgg() RETURNS Integer AS $BODY$BEGIN RETURN (301436); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Measure_Sh() RETURNS Integer AS $BODY$BEGIN RETURN (1824); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Measure_Sht() RETURNS Integer AS $BODY$BEGIN RETURN (301416); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Goods_WorkIce() RETURNS Integer AS $BODY$BEGIN RETURN (3924); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Goods_ReWork() RETURNS Integer AS $BODY$BEGIN RETURN (3934); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_GoodsGroup_ReWork() RETURNS Integer AS $BODY$BEGIN RETURN (1938); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_GoodsKind_WorkProgress() RETURNS Integer AS $BODY$BEGIN RETURN (8345); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_GoodsKind_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (8335); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_PriceList_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (18840); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE; -- 18840
CREATE OR REPLACE FUNCTION zc_PriceList_BasisPrior() RETURNS Integer AS $BODY$BEGIN RETURN (18846); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE; -- 18846
CREATE OR REPLACE FUNCTION zc_PriceList_ProductionSeparate() RETURNS Integer AS $BODY$BEGIN RETURN (18889); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE; -- 18889
CREATE OR REPLACE FUNCTION zc_PriceList_ProductionSeparateHist() RETURNS Integer AS $BODY$BEGIN RETURN (2707438); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE; -- 2707438
CREATE OR REPLACE FUNCTION zc_PriceList_Bread() RETURNS Integer AS $BODY$BEGIN RETURN (131980); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE; -- 131980
CREATE OR REPLACE FUNCTION zc_PriceList_Fuel() RETURNS Integer AS $BODY$BEGIN RETURN (1755717); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE; -- 1755717 -- select * from object where ValueData = 'Цены ГСМ' AND DescId = zc_object_PriceList()

-- CREATE OR REPLACE FUNCTION zc_InfoMoneyDestination_WorkProgress() RETURNS Integer AS $BODY$BEGIN RETURN (8874); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Branch_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (8380); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Branch_Kiev() RETURNS Integer AS $BODY$BEGIN RETURN (8379); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Juridical_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (9399); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Juridical_Irna() RETURNS Integer AS $BODY$BEGIN RETURN (15512); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_Unit_RK() RETURNS Integer AS $BODY$BEGIN RETURN (8459); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Unit_Pack() RETURNS Integer AS $BODY$BEGIN RETURN (8451); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Unit_RK_Label() RETURNS Integer AS $BODY$BEGIN RETURN (9073781); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PartionCell_RK() RETURNS Integer AS $BODY$BEGIN RETURN (10374355); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PartionCell_Err() RETURNS Integer AS $BODY$BEGIN RETURN (11237418); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_Business_Irna() RETURNS Integer AS $BODY$BEGIN RETURN (8020705); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

-- CREATE OR REPLACE FUNCTION zc_Enum_PaidKind_FirstForm()  RETURNS integer AS $BODY$BEGIN RETURN (SELECT ObjectId AS Id FROM ObjectString WHERE ValueData = 'zc_Enum_PaidKind_FirstForm' AND DescId = zc_ObjectString_Enum()); END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
-- CREATE OR REPLACE FUNCTION zc_Enum_PaidKind_SecondForm() RETURNS integer AS $BODY$BEGIN RETURN (SELECT ObjectId AS Id FROM ObjectString WHERE ValueData = 'zc_Enum_PaidKind_SecondForm' AND DescId = zc_ObjectString_Enum()); END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
-- CREATE OR REPLACE FUNCTION zc_Enum_Currency_Basis() RETURNS Integer AS $BODY$BEGIN RETURN (SELECT ObjectId AS Id FROM ObjectString WHERE ValueData = 'zc_Enum_Currency_Basis' AND DescId = zc_ObjectString_Enum()); END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_Color_Black() RETURNS Integer AS $BODY$BEGIN RETURN (0); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Red() RETURNS Integer AS $BODY$BEGIN RETURN (1118719); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Aqua() RETURNS Integer AS $BODY$BEGIN RETURN (16777158); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Cyan() RETURNS Integer AS $BODY$BEGIN RETURN (14862279); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_GreenL() RETURNS Integer AS $BODY$BEGIN RETURN (11987626); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Yelow() RETURNS Integer AS $BODY$BEGIN RETURN (8978431); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_White() RETURNS Integer AS $BODY$BEGIN RETURN (16777215); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Blue() RETURNS Integer AS $BODY$BEGIN RETURN (14614528); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Lime() RETURNS Integer AS $BODY$BEGIN RETURN (65280); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Pink() RETURNS Integer AS $BODY$BEGIN RETURN (16440317); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
-- CREATE OR REPLACE FUNCTION zc_Color_Orange() RETURNS Integer AS $BODY$BEGIN RETURN (33023); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Color_Orange() RETURNS Integer AS $BODY$BEGIN RETURN (8572157); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_IsLockTable() RETURNS Boolean AS $BODY$BEGIN RETURN (FALSE); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_IsLockTableCycle() RETURNS Boolean AS $BODY$BEGIN RETURN (TRUE); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_IsLockTableSecond() RETURNS Integer AS $BODY$BEGIN RETURN (5); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

CREATE OR REPLACE FUNCTION zc_DateStart_Role_CashReplace() RETURNS TDateTime AS $BODY$BEGIN RETURN ('24.11.2016'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_DateEnd_Role_CashReplace() RETURNS TDateTime AS $BODY$BEGIN RETURN ('25.11.2016'); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

-- Функции для определения метода суммирования в TPivotAddOn
CREATE OR REPLACE FUNCTION zc_PivotSummartType_None() RETURNS Integer AS $BODY$BEGIN RETURN (0); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Count() RETURNS Integer AS $BODY$BEGIN RETURN (1); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Sum() RETURNS Integer AS $BODY$BEGIN RETURN (2); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Min() RETURNS Integer AS $BODY$BEGIN RETURN (3); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Max() RETURNS Integer AS $BODY$BEGIN RETURN (4); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Average() RETURNS Integer AS $BODY$BEGIN RETURN (5); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_StdDev() RETURNS Integer AS $BODY$BEGIN RETURN (6); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_StdDevP() RETURNS Integer AS $BODY$BEGIN RETURN (7); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Variance() RETURNS Integer AS $BODY$BEGIN RETURN (8); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_VarianceP() RETURNS Integer AS $BODY$BEGIN RETURN (9); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_AveragePrice() RETURNS Integer AS $BODY$BEGIN RETURN (10); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;

-- пластиковые ящики
CREATE OR REPLACE FUNCTION zc_Box_E2() RETURNS Integer AS $BODY$BEGIN RETURN (SELECT Id AS Id FROM Object WHERE ValueData = 'E2' AND DescId = zc_Object_Box()); END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_Box_E3() RETURNS Integer AS $BODY$BEGIN RETURN (SELECT Id AS Id FROM Object WHERE ValueData = 'E3' AND DescId = zc_Object_Box()); END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
*/

/*-------------------------------------------------------------------------------
 ИСТОРИЯ РАЗРАБОТКИ: ДАТА, АВТОР
               Фелонюк И.В.   Кухтин И.В.   Климентьев К.И.   Воробкало А.А.   Ярошенко Р.Ф.   Шаблий О.В.
 09.03.19                                                                                        *zc_PivotSummartType_ ...
 12.11.18                                                                                        *zc_Color_Lime
 29.09.15                                                        *zc_Color_Goods_Additional,zc_Color_Goods_Alternative 
 07.05.14                                        * add rem zc_PriceList_Bread
 20.10.13                                        * add rem zc_Juridical_Basis
 22.09.13                                        * add rem zc_Branch_Basis
 09.08.13                                        * rem zc_PriceList_ProductionSeparate and zc_PriceList_Basis, эти ф-ции создадутся при зугрузке данных (Load_PostgreSql.exe)
 09.08.13                                        * add zc_isHistoryCost and zc_isHistoryCost_byInfoMoneyDetail
 06.08.13                                        * ? как сделать что б некоторые ф-ции определялись после загрузки данных (а не при нинициализации БД)
 21.07.13                                        * add zc_PriceList_ProductionSeparate and zc_PriceList_Basis
 16.07.13                                        *
 12.07.13                                        *
*/
