SELECT 
 C.RELNAME AS TABLE_NAME, 
 A.ATTNAME AS COLUMN_NAME, 
 A.ATTNUM AS COLUMN_POSITION, 
 A.ATTTYPID AS COLUMN_DATATYPE, 
 T.TYPNAME AS COLUMN_TYPENAME, 
 (16384 + CASE WHEN A.ATTNOTNULL THEN 0 ELSE 2 END + CASE WHEN A.ATTNUM > 0 THEN 0 ELSE 16 END + 
 	  CASE WHEN UPPER(A.ATTNAME) = 'OID' AND A.ATTNUM < 0 THEN 64 ELSE 0 END + 
 	  CASE WHEN UPPER(SUBSTR(PG_GET_EXPR(D.ADBIN, D.ADRELID), 1, 8)) = 'NEXTVAL(' THEN 32 WHEN D.ADBIN IS NOT NULL THEN 128 
 	  /*ELSE 0 END + CASE WHEN A.ATTIDENTITY = 'a' OR A.ATTIDENTITY = 'd' THEN 32 */ELSE 0 END)::INTEGER AS COLUMN_ATTRIBUTES

FROM PG_CATALOG.PG_CLASS C 
 INNER JOIN PG_CATALOG.PG_ATTRIBUTE A ON A.ATTRELID = C.OID 
 INNER JOIN PG_CATALOG.PG_TYPE T ON A.ATTTYPID = T.OID 
 LEFT JOIN PG_CATALOG.PG_ATTRDEF D ON D.ADNUM = A.ATTNUM AND D.ADRELID = C.OID  
WHERE A.ATTNUM > 0 AND NOT A.ATTISDROPPED  AND C.RELNAME = :TABLE_NAME ORDER BY 3   