  SELECT 
   TC.RELNAME AS TABLE_NAME, 
   IC.RELNAME AS INDEX_NAME,
   CASE WHEN I.INDISPRIMARY THEN 2 WHEN I.INDISUNIQUE THEN 1 ELSE 0 END::INTEGER AS INDEX_TYPE
  FROM PG_CATALOG.PG_INDEX I 
   INNER JOIN PG_CATALOG.PG_CLASS TC ON TC.OID = I.INDRELID 
   INNER JOIN PG_CATALOG.PG_CLASS IC ON IC.OID = I.INDEXRELID 
  WHERE /*N.NSPNAME = 'public' AND */TC.RELNAME = :table_name AND (I.INDISPRIMARY OR I.INDISUNIQUE) 