SELECT 
   IC.RELNAME AS INDEX_NAME, 
   A.ATTNAME AS COLUMN_NAME, 
   A.ATTNUM AS COLUMN_POSITION
  FROM PG_CATALOG.PG_INDEX I 
   INNER JOIN PG_CATALOG.PG_CLASS IC ON IC.OID = I.INDEXRELID 
   INNER JOIN PG_CATALOG.PG_ATTRIBUTE A ON A.ATTRELID = I.INDRELID AND A.ATTNUM = ANY(I.INDKEY)  
  WHERE IC.RELNAME = :index_name