SELECT 
       N.NSPNAME AS SCHEMA_NAME, 
       C.RELNAME AS TABLE_NAME, 
       CASE WHEN C.RELKIND = 'r' THEN 1 WHEN C.RELKIND = 'v' THEN 2 ELSE 0 END::INTEGER AS TABLE_TYPE, 
       A.USENAME AS "USER"
FROM PG_CATALOG.PG_CLASS C 
     INNER JOIN PG_CATALOG.PG_NAMESPACE N ON N.OID = C.RELNAMESPACE 
     INNER JOIN PG_CATALOG.PG_USER A ON C.RELOWNER = A.USESYSID  
WHERE C.RELKIND IN ('r','v') AND N.NSPNAME = :SCHEMA_NAME AND N.OID <> pg_my_temp_schema() ORDER BY 1, 2