GRANT ALL ON ALL TABLES IN SCHEMA public TO ProjectBoat;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ProjectBoat;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO ProjectBoat;
CREATE EXTENSION tablefunc;
