-- !!!
-- !!! Типы PUSH сообщений
-- !!!

CREATE OR REPLACE FUNCTION zc_TypePUSH_Warning() RETURNS integer AS $BODY$BEGIN RETURN 1; END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_TypePUSH_Error() RETURNS integer AS $BODY$BEGIN RETURN 2; END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_TypePUSH_Information() RETURNS integer AS $BODY$BEGIN RETURN 3; END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_TypePUSH_Confirmation() RETURNS integer AS $BODY$BEGIN RETURN 4; END;  $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
