object CallbackHandlerForm: TCallbackHandlerForm
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = #1054#1078#1080#1076#1072#1085#1080#1077
  ClientHeight = 120
  ClientWidth = 430
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object edMsgDescription: TEdit
    Left = 16
    Top = 16
    Width = 393
    Height = 21
    TabStop = False
    BevelInner = bvNone
    BevelOuter = bvNone
    BiDiMode = bdLeftToRight
    Color = clScrollBar
    ParentBiDiMode = False
    ReadOnly = True
    TabOrder = 0
  end
  object cxProgressBar1: TcxProgressBar
    Left = 16
    Top = 47
    Properties.AnimationPath = cxapPingPong
    Properties.AnimationRestartDelay = 2
    Properties.AnimationSpeed = 2
    Properties.Marquee = True
    TabOrder = 1
    Width = 393
  end
  object cxButton1: TcxButton
    Left = 334
    Top = 78
    Width = 75
    Height = 25
    Caption = #1055#1088#1077#1088#1074#1072#1090#1100
    TabOrder = 2
    OnClick = cxButton1Click
  end
  object labInterval: TcxLabel
    Left = 16
    Top = 74
    Caption = '0:00'
    ParentFont = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -21
    Style.Font.Name = 'Tahoma'
    Style.Font.Style = []
    Style.IsFontAssigned = True
  end
  object Timer: TTimer
    Enabled = False
    Interval = 200
    OnTimer = TimerTimer
    Left = 384
    Top = 16
  end
  object IdHTTPServer: TIdHTTPServer
    Bindings = <>
    OnCommandGet = IdHTTPServerCommandGet
    Left = 256
    Top = 72
  end
end
