object ListSelectionForm: TListSelectionForm
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'ListSelectionForm'
  ClientHeight = 287
  ClientWidth = 454
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 454
    Height = 246
    Align = alClient
    TabOrder = 0
    ExplicitLeft = 144
    ExplicitTop = 72
    ExplicitWidth = 185
    ExplicitHeight = 41
    object cxListBox1: TcxListBox
      Left = 1
      Top = 1
      Width = 452
      Height = 244
      Align = alClient
      ItemHeight = 19
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -16
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.IsFontAssigned = True
      TabOrder = 0
      OnDblClick = cxListBox1DblClick
      ExplicitLeft = 128
      ExplicitTop = 64
      ExplicitWidth = 121
      ExplicitHeight = 97
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 246
    Width = 454
    Height = 41
    Align = alBottom
    TabOrder = 1
    ExplicitLeft = 120
    ExplicitTop = 168
    ExplicitWidth = 185
    object bbCancel: TcxButton
      Left = 274
      Top = 6
      Width = 75
      Height = 25
      Cancel = True
      Caption = #1054#1090#1084#1077#1085#1072
      ModalResult = 2
      TabOrder = 0
    end
    object bbOk: TcxButton
      Left = 87
      Top = 6
      Width = 75
      Height = 25
      Caption = 'Ok'
      Default = True
      ModalResult = 1
      TabOrder = 1
    end
  end
end
