program BoutiqueTest;

uses
  Forms,
  DUnitTestRunner,
  SysUtils,
  dbCreateStructureTest in '..\SOURCEBoutique\STRUCTURE\dbCreateStructureTest.pas',
  dbMetadataTest in '..\SOURCEBoutique\METADATA\dbMetadataTest.pas',
  zLibUtil in '..\SOURCEBoutique\zLibUtil.pas',
  CommonFunctionTest in '..\SOURCEBoutique\Function\CommonFunctionTest.pas',
  dbBoutiqueProcedureTest in '..\SOURCEBoutique\dbBoutiqueProcedureTest.pas',
  UtilConst in '..\SOURCEBoutique\UtilConst.pas',
  dbEnumTest in '..\SOURCEBoutique\dbEnumTest.pas',
  ProcessTest in '..\SOURCEBoutique\Process\ProcessTest.pas',
  dbCreateViewTest in '..\SOURCEBoutique\View\dbCreateViewTest.pas',
  DefaultsTest in '..\SOURCEBoutique\Defaults\DefaultsTest.pas',
  { Forms }
  LoadBoutiqueFormTest in '..\SOURCEBoutique\LoadBoutiqueFormTest.pas',

  PriceListGoodsItem in '..\..\Forms\Guides\PriceListGoodsItem.pas' {PriceListGoodsItemForm},
  CommonData in '..\..\SOURCE\CommonData.pas',
  Authentication in '..\..\SOURCE\Authentication.pas',
  FormStorage in '..\..\SOURCE\FormStorage.pas',
  ParentForm in '..\..\SOURCE\ParentForm.pas' {ParentForm},
  Storage in '..\..\SOURCE\Storage.pas',
  UtilConvert in '..\..\SOURCE\UtilConvert.pas',
  dsdAction in '..\..\SOURCE\COMPONENT\dsdAction.pas',
  dsdAddOn in '..\..\SOURCE\COMPONENT\dsdAddOn.pas',
  dsdDB in '..\..\SOURCE\COMPONENT\dsdDB.pas',
  dsdGuides in '..\..\SOURCE\COMPONENT\dsdGuides.pas',
  DataModul in '..\..\SOURCE\DataModul.pas' {dmMain: TDataModule},
//  GoodsPartnerCodeMaster in '..\..\FormsFarmacy\Guides\GoodsPartnerCodeMaster.pas' {GoodsPartnerCodeMasterForm},
//  GoodsMainEdit in '..\..\FormsFarmacy\Guides\GoodsMainEdit.pas' {GoodsMainEditForm},
  dbTest in '..\SOURCEBoutique\dbTest.pas',
  ChoicePeriod in '..\..\SOURCE\COMPONENT\ChoicePeriod.pas' {PeriodChoiceForm},
  Defaults in '..\..\SOURCE\COMPONENT\Defaults.pas',
  UnilWin in '..\..\SOURCE\UnilWin.pas',
  MessagesUnit in '..\..\SOURCE\MessagesUnit.pas' {MessagesForm},
  SimpleGauge in '..\..\SOURCE\SimpleGauge.pas' {SimpleGaugeForm},
  ClientBankLoad in '..\..\SOURCE\COMPONENT\ClientBankLoad.pas',
  Document in '..\..\SOURCE\COMPONENT\Document.pas',
  ExternalLoad in '..\..\SOURCE\COMPONENT\ExternalLoad.pas',
  Log in '..\..\SOURCE\Log.pas',
  ExternalData in '..\..\SOURCE\COMPONENT\ExternalData.pas',
  ExternalSave in '..\..\SOURCE\COMPONENT\ExternalSave.pas',
  VKDBFDataSet in '..\..\SOURCE\DBF\VKDBFDataSet.pas',
  VKDBFPrx in '..\..\SOURCE\DBF\VKDBFPrx.pas',
  VKDBFUtil in '..\..\SOURCE\DBF\VKDBFUtil.pas',
  VKDBFMemMgr in '..\..\SOURCE\DBF\VKDBFMemMgr.pas',
  VKDBFCrypt in '..\..\SOURCE\DBF\VKDBFCrypt.pas',
  VKDBFGostCrypt in '..\..\SOURCE\DBF\VKDBFGostCrypt.pas',
  VKDBFCDX in '..\..\SOURCE\DBF\VKDBFCDX.pas',
  VKDBFIndex in '..\..\SOURCE\DBF\VKDBFIndex.pas',
  VKDBFSorters in '..\..\SOURCE\DBF\VKDBFSorters.pas',
  VKDBFCollate in '..\..\SOURCE\DBF\VKDBFCollate.pas',
  VKDBFParser in '..\..\SOURCE\DBF\VKDBFParser.pas',
  VKDBFNTX in '..\..\SOURCE\DBF\VKDBFNTX.pas',
  VKDBFSortedList in '..\..\SOURCE\DBF\VKDBFSortedList.pas',
  ObjectTest in '..\SOURCEBoutique\Objects\ObjectTest.pas',
  cxGridAddOn in '..\..\SOURCE\DevAddOn\cxGridAddOn.pas',
  MeDOC in '..\..\SOURCE\MeDOC\MeDOC.pas',
  MeDocXML in '..\..\SOURCE\MeDOC\MeDocXML.pas',

  Measure in '..\..\FormsBoutique\Guides\Measure.pas' {MeasureForm: TParentForm},
  MeasureEdit in '..\..\FormsBoutique\Guides\MeasureEdit.pas' {MeasureEditForm: TParentForm},

  CompositionGroup in '..\..\FormsBoutique\Guides\CompositionGroup.pas' {CompositionGroupForm: TParentForm},
  CompositionGroupEdit in '..\..\FormsBoutique\Guides\CompositionGroupEdit.pas' {CompositionGroupEditForm: TParentForm},

  Composition in '..\..\FormsBoutique\Guides\Composition.pas' {CompositionForm: TParentForm},
  CompositionEdit in '..\..\FormsBoutique\Guides\CompositionEdit.pas' {CompositionEditForm: TParentForm},

  CountryBrand in '..\..\FormsBoutique\Guides\CountryBrand.pas' {CountryBrandForm: TParentForm},
  CountryBrandEdit in '..\..\FormsBoutique\Guides\CountryBrandEdit.pas' {CountryBrandEditForm: TParentForm},

  Brand in '..\..\FormsBoutique\Guides\Brand.pas' {BrandForm: TParentForm},
  BrandEdit in '..\..\FormsBoutique\Guides\BrandEdit.pas' {BrandEditForm: TParentForm},

  Fabrika in '..\..\FormsBoutique\Guides\Fabrika.pas' {FabrikaForm: TParentForm},
  FabrikaEdit in '..\..\FormsBoutique\Guides\FabrikaEdit.pas' {FabrikaEditForm: TParentForm},

  LineFabrica in '..\..\FormsBoutique\Guides\LineFabrica.pas' {LineFabricaForm: TParentForm},
  LineFabricaEdit in '..\..\FormsBoutique\Guides\LineFabricaEdit.pas' {LineFabricaEditForm: TParentForm},

  GoodsInfo in '..\..\FormsBoutique\Guides\GoodsInfo.pas' {GoodsInfoForm: TParentForm},
  GoodsInfoEdit in '..\..\FormsBoutique\Guides\GoodsInfoEdit.pas' {GoodsInfoEditForm: TParentForm},

  GoodsSize in '..\..\FormsBoutique\Guides\GoodsSize.pas' {GoodsSizeForm: TParentForm},
  GoodsSizeEdit in '..\..\FormsBoutique\Guides\GoodsSizeEdit.pas' {GoodsSizeEditForm: TParentForm},

  GoodsGroup in '..\..\FormsBoutique\Guides\GoodsGroup.pas' {GoodsGroupForm: TParentForm},
  GoodsGroupEdit in '..\..\FormsBoutique\Guides\GoodsGroupEdit.pas' {GoodsGroupEditForm: TParentForm},

  Kassa in '..\..\FormsBoutique\Guides\Kassa.pas' {KassaForm: TParentForm},
  KassaEdit in '..\..\FormsBoutique\Guides\KassaEdit.pas' {KassaEditForm: TParentForm},

  Valuta in '..\..\FormsBoutique\Guides\Valuta.pas' {ValutaForm: TParentForm},
  ValutaEdit in '..\..\FormsBoutique\Guides\ValutaEdit.pas' {ValutaEditForm: TParentForm},

  Member in '..\..\FormsBoutique\Guides\Member.pas' {MemberForm: TParentForm},
  MemberEdit in '..\..\FormsBoutique\Guides\MemberEdit.pas' {MemberEditForm: TParentForm},

  Period in '..\..\FormsBoutique\Guides\Period.pas' {PeriodForm: TParentForm},
  PeriodEdit in '..\..\FormsBoutique\Guides\PeriodEdit.pas' {PeriodEditForm: TParentForm},

  Discount in '..\..\FormsBoutique\Guides\Discount.pas' {DiscountForm: TParentForm},
  DiscountEdit in '..\..\FormsBoutique\Guides\DiscountEdit.pas' {DiscountEditForm: TParentForm},

  DiscountTools in '..\..\FormsBoutique\Guides\DiscountTools.pas' {DiscountToolsForm: TParentForm},
  DiscountToolsEdit in '..\..\FormsBoutique\Guides\DiscountToolsEdit.pas' {DiscountToolsEditForm: TParentForm},

  Partner in '..\..\FormsBoutique\Guides\Partner.pas' {PartnerForm: TParentForm},
  PartnerEdit in '..\..\FormsBoutique\Guides\PartnerEdit.pas' {PartnerEditForm: TParentForm},

  JuridicalGroup in '..\..\FormsBoutique\Guides\JuridicalGroup.pas' {JuridicalGroupForm: TParentForm},
  JuridicalGroupEdit in '..\..\FormsBoutique\Guides\JuridicalGroupEdit.pas' {JuridicalGroupEditForm: TParentForm},

  Juridical in '..\..\FormsBoutique\Guides\Juridical.pas' {JuridicalForm: TParentForm},
  JuridicalEdit in '..\..\FormsBoutique\Guides\JuridicalEdit.pas' {JuridicalEditForm: TParentForm},

  Units in '..\..\FormsBoutique\Guides\Units.pas' {UnitsForm: TParentForm},
  UnitEdit in '..\..\FormsBoutique\Guides\UnitEdit.pas' {UnitsEditForm: TParentForm},

//  Box in '..\..\Forms\Box.pas' {BoxForm: TParentForm},
//  BoxEdit in '..\..\Forms\BoxEdit.pas' {BoxEditForm: TParentForm},
  ImportExportLinkType in '..\..\Forms\Kind\ImportExportLinkType.pas' {ImportExportLinkTypeForm: TParentForm},
//  UnitEdit in '..\..\FormsFarmacy\Guides\UnitEdit.pas' {UnitEditForm: TParentForm},
  AncestorBase in '..\..\Forms\Ancestor\AncestorBase.pas' {AncestorBaseForm: TParentForm},
  AncestorData in '..\..\Forms\Ancestor\AncestorData.pas' {AncestorDataForm: TParentForm},
  AncestorDBGrid in '..\..\Forms\Ancestor\AncestorDBGrid.pas' {AncestorDBGridForm: TParentForm},
  AncestorDialog in '..\..\Forms\Ancestor\AncestorDialog.pas' {AncestorDialogForm: TParentForm},
  AncestorDocument in '..\..\Forms\Ancestor\AncestorDocument.pas' {AncestorDocumentForm: TParentForm},
  AncestorDocumentMC in '..\..\Forms\Ancestor\AncestorDocumentMC.pas' {AncestorDocumentMCForm: TParentForm},
  AncestorEditDialog in '..\..\Forms\Ancestor\AncestorEditDialog.pas' {AncestorEditDialogForm: TParentForm},
  AncestorEnum in '..\..\Forms\Ancestor\AncestorEnum.pas' {AncestorEnumForm: TParentForm},
  AncestorGuides in '..\..\Forms\Ancestor\AncestorGuides.pas' {AncestorGuidesForm: TParentForm},
  AncestorJournal in '..\..\Forms\Ancestor\AncestorJournal.pas' {AncestorJournalForm: TParentForm},
  AboutBoxUnit in '..\..\SOURCE\AboutBoxUnit.pas' {AboutBox},
//  dbLoadTest in '..\SOURCEBoutique\Load\dbLoadTest.pas',
//  Country in '..\..\Forms\Guides\Country.pas' {CountryForm: TParentForm},
//  CountryEdit in '..\..\Forms\Guides\CountryEdit.pas' {CountryEditForm: TParentForm},
//  MovementLoad in '..\..\FormsFarmacy\Load\MovementLoad.pas' {MovementLoadForm: TParentForm},
  UpdaterTest in '..\SOURCEBoutique\Component\UpdaterTest.pas',
  dbObjectTest in '..\SOURCEBoutique\dbObjectTest.pas',
//  Retail in '..\..\Forms\Guides\Retail.pas' {RetailForm: TParentForm},
//  RetailEdit in '..\..\Forms\Guides\RetailEdit.pas' {RetailEditForm: TParentForm},
//  Juridical in '..\..\FormsFarmacy\Guides\Juridical.pas' {JuridicalForm: TParentForm},
//  JuridicalEdit in '..\..\FormsFarmacy\Guides\JuridicalEdit.pas' {JuridicalEditForm: TParentForm},
  MainForm in '..\..\FormsBoutique\MainForm.pas' {MainForm},
//  IncomeJournal in '..\..\FormsFarmacy\Document\IncomeJournal.pas' {IncomeJournalForm: TParentForm},
//  PriceList in '..\..\FormsFarmacy\Document\PriceList.pas' {PriceListForm: TParentForm},
//  PriceListJournal in '..\..\FormsFarmacy\Document\PriceListJournal.pas' {PriceListJournalForm: TParentForm},
//  OrderExternal in '..\..\FormsFarmacy\Document\OrderExternal.pas' {OrderExternalForm: TParentForm},
//  OrderExternalJournal in '..\..\FormsFarmacy\Document\OrderExternalJournal.pas' {OrderExternalJournalForm: TParentForm},
//  OrderInternalLite in '..\..\FormsFarmacy\Document\OrderInternalLite.pas' {OrderInternalLiteForm: TParentForm},
//  OrderInternalJournal in '..\..\FormsFarmacy\Document\OrderInternalJournal.pas' {OrderInternalJournalForm: TParentForm},
  User in '..\..\FormsBoutique\Guides\User.pas' {UserForm: TParentForm},
  UserEdit in '..\..\FormsBoutique\Guides\UserEdit.pas' {UserEditForm: TParentForm},
//  Role in '..\..\Forms\Role.pas' {RoleForm: TParentForm},
//  RoleEdit in '..\..\Forms\RoleEdit.pas' {RoleEditForm: TParentForm},
  RoleTest in '..\SOURCEBoutique\Objects\All\RoleTest.pas',
//  ImportType in '..\..\Forms\Import\ImportType.pas' {ImportTypeForm: TParentForm},
//  JuridicalTest in '..\SOURCEBoutique\Objects\All\Farmacy\JuridicalTest.pas',
//  CommonObjectHistoryProcedureTest in '..\SOURCEBoutique\ObjectHistory\CommonObjectHistoryProcedureTest.pas',
//  MovementItemsLoad in '..\..\FormsFarmacy\Load\MovementItemsLoad.pas' {MovementItemsLoadForm: TParentForm},
//  ImportGroup in '..\..\Forms\Import\ImportGroup.pas' {ImportGroupForm: TParentForm},
//  FileTypeKind in '..\..\Forms\Kind\FileTypeKind.pas' {FileTypeKindForm: TParentForm},
//  PriceListItemsLoad in '..\..\FormsFarmacy\Load\PriceListItemsLoad.pas' {PriceListItemsLoadForm: TParentForm},
//  PriceListLoad in '..\..\FormsFarmacy\Load\PriceListLoad.pas' {PriceListLoadForm: TParentForm},
//  AdditionalGoods in '..\..\FormsFarmacy\Guides\AdditionalGoods.pas' {AdditionalGoodsForm: TParentForm},
//  LinkGoodsTest in '..\SOURCEBoutique\Objects\All\LinkGoodsTest.pas',
//  GoodsTest in '..\SOURCEBoutique\Objects\All\Farmacy\GoodsTest.pas',
//  GoodsGroupTest in '..\SOURCEBoutique\Objects\All\Farmacy\GoodsGroupTest.pas',
//  ImportTypeTest in '..\SOURCEBoutique\Objects\All\ImportTypeTest.pas',
//  ImportTypeItemsTest in '..\SOURCEBoutique\Objects\All\ImportTypeItemsTest.pas',
//  MeasureTest in '..\SOURCEBoutique\Objects\All\MeasureTest.pas',
//  PaidKindTest in '..\SOURCEBoutique\Objects\All\PaidKindTest.pas',
//  PriceListTest in '..\SOURCEBoutique\Objects\All\PriceListTest.pas',
//  RetailTest in '..\SOURCEBoutique\Objects\All\RetailTest.pas',
  UserTest in '..\SOURCEBoutique\Objects\All\UserTest.pas',
  ParentFormTest in '..\SOURCEBoutique\Form\ParentFormTest.pas' {TestForm: TParentForm},
//  GoodsMainLite in '..\..\FormsFarmacy\Guides\GoodsMainLite.pas' {GoodsMainLiteForm: TParentForm},
//  DefaultsKey in '..\..\Forms\System\DefaultsKey.pas' {DefaultsKeyForm: TParentForm},
  Objects in '..\..\FormsBoutique\Guides\Objects.pas' {ObjectForm: TParentForm},
//  ImportExportLink in '..\..\Forms\System\ImportExportLink.pas' {ImportExportLinkForm: TParentForm},
  ObjectDesc in '..\..\FormsBoutique\Guides\ObjectDesc.pas' {ObjectDescForm: TParentForm},
//  FormsUnit in '..\..\Forms\System\FormsUnit.pas' {FormsForm: TParentForm},
//  UnionDesc in '..\..\Forms\System\UnionDesc.pas' {UnionDescForm: TParentForm},
//  CommonObjectDescProcedureTest in '..\SOURCEBoutique\ObjectDesc\CommonObjectDescProcedureTest.pas',
//  UserKey in '..\..\Forms\Guides\UserKey.pas' {UserKeyForm: TParentForm},
//  CommonObjectProcedureTest in '..\SOURCEBoutique\Objects\CommonObjectProcedureTest.pas',
//  Goods in '..\..\FormsFarmacy\Guides\Goods.pas' {GoodsForm: TParentForm},
//  UnitsTest in '..\SOURCEBoutique\Objects\All\Farmacy\UnitsTest.pas',
//  UnitTree in '..\..\FormsFarmacy\Guides\UnitTree.pas' {UnitTreeForm: TParentForm},
//  GoodsEdit in '..\..\FormsFarmacy\Guides\GoodsEdit.pas' {GoodsEditForm: TParentForm},
//  GoodsMain in '..\..\FormsFarmacy\Guides\GoodsMain.pas' {GoodsMainForm: TParentForm},
//  GoodsPartnerCode in '..\..\FormsFarmacy\Guides\GoodsPartnerCode.pas' {GoodsPartnerCodeForm: TParentForm},
//  ImportSettingsTest in '..\SOURCEBoutique\Objects\All\ImportSettingsTest.pas',
//  ExternalDocumentLoad in '..\..\SOURCE\COMPONENT\ExternalDocumentLoad.pas',
//  ExternalLoadTest in '..\SOURCEBoutique\Component\ExternalLoadTest.pas',
//  LoadObjectUnit in '..\..\FormsFarmacy\Guides\LoadObjectUnit.pas' {LoadObjectForm: TParentForm},
//  OrderExternalTest in '..\SOURCEBoutique\Movement\All\OrderExternalTest.pas',
//  dbMovementTest in '..\SOURCEBoutique\Movement\dbMovementTest.pas',
//  CommonMovementProcedureTest in '..\SOURCEBoutique\Movement\CommonMovementProcedureTest.pas',
//  PriceListMovementTest in '..\SOURCEBoutique\Movement\All\PriceListMovementTest.pas',
//  OrderInternalTest in '..\SOURCEBoutique\Movement\All\OrderInternalTest.pas',
//  ContractKindTest in '..\SOURCEBoutique\Objects\All\ContractKindTest.pas',
//  ContractTest in '..\SOURCEBoutique\Objects\All\Farmacy\ContractTest.pas',
//  Contract in '..\..\FormsFarmacy\Guides\Contract.pas' {ContractForm: TParentForm},
//  ContractEdit in '..\..\FormsFarmacy\Guides\ContractEdit.pas' {ContractEditForm: TParentForm},
//  PriceGroupSettingsTest in '..\SOURCEBoutique\Objects\All\Farmacy\PriceGroupSettingsTest.pas',
//  PriceGroupSettingsUnit in '..\..\FormsFarmacy\Guides\PriceGroupSettingsUnit.pas' {PriceGroupSettingsForm: TParentForm},
//  JuridicalSettingsTest in '..\SOURCEBoutique\Objects\All\JuridicalSettingsTest.pas',
//  JuridicalSettings in '..\..\FormsFarmacy\Guides\JuridicalSettings.pas' {JuridicalSettingsForm: TParentForm},
//  CommonProtocolProcedureTest in '..\SOURCEBoutique\Protocol\CommonProtocolProcedureTest.pas',
  ActionTest in '..\SOURCEBoutique\Objects\All\ActionTest.pas',
//  Action in '..\..\Forms\Action.pas' {ActionForm: TParentForm},
//  UserProtocol in '..\..\Forms\System\UserProtocol.pas' {UserProtocolForm: TParentForm},
//  ImportGroupTest in '..\SOURCEBoutique\Objects\All\ImportGroupTest.pas',
//  ImportGroupItemsTest in '..\SOURCEBoutique\Objects\All\ImportGroupItemsTest.pas',
//  ImportSettings in '..\..\Forms\Import\ImportSettings.pas' {ImportSettingsForm: TParentForm},
//  не нужно  CommonMovementItemProcedureTest in '..\SOURCEBoutique\MovementItem\CommonMovementItemProcedureTest.pas',
//  UploadUnloadData in '..\..\FormsFarmacy\ConnectWithOld\UploadUnloadData.pas' {dmUnloadUploadData: TDataModule},
//  ContactPersonKind in '..\..\Forms\Kind\ContactPersonKind.pas' {ContactPersonKindForm: TParentForm},
//  OrderKind in '..\..\Forms\Kind\OrderKind.pas' {OrderKindForm: TParentForm},
//  ContactPersonEdit in '..\..\Forms\Guides\ContactPersonEdit.pas' {ContactPersonEditForm: TParentForm},
//  ContactPersonTest in '..\SOURCEBoutique\Objects\All\ContactPersonTest.pas',
//  PartnerCode in '..\..\FormsFarmacy\Guides\PartnerCode.pas' {PartnerCodeForm: TParentForm},
//  GoodsLite in '..\..\FormsFarmacy\Guides\GoodsLite.pas' {GoodsLiteForm: TParentForm},
//  ReportOrderGoods in '..\..\FormsFarmacy\Report\ReportOrderGoods.pas' {ReportOrderGoodsForm: TParentForm},
//  LookAndFillSettings in '..\..\SOURCE\LookAndFillSettings.pas' {LookAndFillSettingsForm},
//  ComDocXML in '..\..\SOURCE\EDI\ComDocXML.pas',
//  DeclarXML in '..\..\SOURCE\EDI\DeclarXML.pas',
//  DesadvXML in '..\..\SOURCE\EDI\DesadvXML.pas',
//  EDI in '..\..\SOURCE\EDI\EDI.pas',
//  InvoiceXML in '..\..\SOURCE\EDI\InvoiceXML.pas',
//  OrderXML in '..\..\SOURCE\EDI\OrderXML.pas',
//  OrdrspXML in '..\..\SOURCE\EDI\OrdrspXML.pas',
//  dsdInternetAction in '..\..\SOURCE\COMPONENT\dsdInternetAction.pas',
//  Member_Object in '..\..\Forms\Guides\Member_Object.pas' {Member_ObjectForm: TParentForm},
//  MemberTest in '..\SOURCEBoutique\Objects\All\MemberTest.pas',
//  Process in '..\..\Forms\Kind\Process.pas' {ProcessForm: TParentForm},
//  NDSKindTest in '..\SOURCEBoutique\Objects\All\NDSKindTest.pas',
  AncestorMain in '..\..\Forms\Ancestor\AncestorMain.pas' {AncestorMainForm},
//  IncomeTest in '..\SOURCEBoutique\Movement\All\Farmacy\IncomeTest.pas',
//  IncomeMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\IncomeMovementItemTest.pas',
//  ChoiceGoodsFromPriceList in '..\..\FormsFarmacy\System\ChoiceGoodsFromPriceList.pas' {ChoiceGoodsFromPriceListForm: TParentForm},
//  OrderInternal in '..\..\FormsFarmacy\Document\OrderInternal.pas' {OrderInternalForm: TParentForm},
//  OrderKindTest in '..\SOURCEBoutique\Objects\All\OrderKindTest.pas',
//  ContactPerson in '..\..\Forms\Guides\ContactPerson.pas' {ContactPersonForm: TParentForm},
//  OrderKindEdit in '..\..\Forms\Kind\OrderKindEdit.pas' {OrderKindEditForm: TParentForm},
//  ImportExportLinkTest in '..\SOURCEBoutique\Objects\All\ImportExportLinkTest.pas',
//  SetUserDefaults in '..\..\Forms\System\SetUserDefaults.pas' {SetUserDefaultsForm: TParentForm},
  Protocol in  '..\..\FormsBoutique\Guides\Protocol.pas' {ProtocolForm: TParentForm},
//  MovementProtocol in '..\..\Forms\System\MovementProtocol.pas' {MovementProtocolForm: TParentForm},
//  ImportExportLinkTypeTest in '..\SOURCEBoutique\Objects\All\ImportExportLinkTypeTest.pas',
//  NDSKind in '..\..\Forms\Kind\NDSKind.pas' {NDSKindForm: TParentForm},
//  ComponentDBTest in '..\SOURCEBoutique\Component\ComponentDBTest.pas',
//  BankAccount in '..\..\Forms\Guides\BankAccount.pas' {BankAccountForm: TParentForm},
//  BankAccountEdit in '..\..\Forms\Guides\BankAccountEdit.pas' {BankAccountEditForm: TParentForm},
//  Bank in '..\..\Forms\Bank.pas' {BankForm: TParentForm},
//  BankAccountTest in '..\SOURCEBoutique\Objects\All\BankAccountTest.pas',
//  BankTest in '..\SOURCEBoutique\Objects\All\BankTest.pas',
//  CurrencyTest in '..\SOURCEBoutique\Objects\All\CurrencyTest.pas',
//  dsdDataSetDataLink in '..\..\SOURCE\COMPONENT\dsdDataSetDataLink.pas',
//  dsdXMLTransform in '..\..\SOURCE\COMPONENT\dsdXMLTransform.pas',
//  BankAccount_Object in '..\..\Forms\Guides\BankAccount_Object.pas' {BankAccount_ObjectForm: TParentForm},
//  BankEdit in '..\..\Forms\BankEdit.pas' {BankEditForm: TParentForm},
//  Juridical_Object in '..\..\FormsFarmacy\Guides\Juridical_Object.pas' {Juridical_ObjectForm: TParentForm},
//  Currency in '..\..\Forms\Guides\Currency.pas' {CurrencyForm: TParentForm},
//  Currency_Object in '..\..\Forms\Guides\Currency_Object.pas' {Currency_ObjectForm: TParentForm},
//  CurrencyEdit in '..\..\Forms\Guides\CurrencyEdit.pas' {CurrencyEditForm: TParentForm},
//  CurrencyValue_Object in '..\..\Forms\Guides\CurrencyValue_Object.pas' {CurrencyValue_ObjectForm: TParentForm},
  Account in '..\..\FormsBoutique\Guides\Account.pas' {AccountForm: TParentForm},
  Account_Object in '..\..\FormsBoutique\Guides\Account_Object.pas' {Account_ObjectForm: TParentForm},
  AccountDirection in '..\..\FormsBoutique\Guides\AccountDirection.pas' {AccountDirectionForm: TParentForm},
  AccountDirection_Object in '..\..\FormsBoutique\Guides\AccountDirection_Object.pas' {AccountDirection_ObjectForm: TParentForm},
  AccountDirectionEdit in '..\..\FormsBoutique\Guides\AccountDirectionEdit.pas' {AccountDirectionEditForm: TParentForm},
  AccountEdit in '..\..\FormsBoutique\Guides\AccountEdit.pas' {AccountEditForm: TParentForm},
  AccountGroup in '..\..\FormsBoutique\Guides\AccountGroup.pas' {AccountGroupForm: TParentForm},
  AccountGroup_Object in '..\..\FormsBoutique\Guides\AccountGroup_Object.pas' {AccountGroup_ObjectForm: TParentForm},
  AccountGroupEdit in '..\..\FormsBoutique\Guides\AccountGroupEdit.pas' {AccountGroupEditForm: TParentForm},
  AccountDirectionTest in '..\SOURCEBoutique\Objects\All\AccountDirectionTest.pas',
  AccountGroupTest in '..\SOURCEBoutique\Objects\All\AccountGroupTest.pas',
  AccountTest in '..\SOURCEBoutique\Objects\All\AccountTest.pas',
//  InfoMoneyDestinationTest in '..\SOURCEBoutique\Objects\All\InfoMoneyDestinationTest.pas',
//  InfoMoneyGroupTest in '..\SOURCEBoutique\Objects\All\InfoMoneyGroupTest.pas',
//  InfoMoneyTest in '..\SOURCEBoutique\Objects\All\InfoMoneyTest.pas',
//  InfoMoney in '..\..\Forms\Guides\InfoMoney.pas' {InfoMoneyForm: TParentForm},
//  InfoMoneyDestination in '..\..\Forms\Guides\InfoMoneyDestination.pas' {InfoMoneyDestinationForm: TParentForm},
//  InfoMoneyDestination_Object in '..\..\Forms\Guides\InfoMoneyDestination_Object.pas' {InfoMoneyDestination_ObjectForm: TParentForm},
//  InfoMoneyDestinationEdit in '..\..\Forms\Guides\InfoMoneyDestinationEdit.pas' {InfoMoneyDestinationEditForm: TParentForm},
//  InfoMoneyEdit in '..\..\Forms\Guides\InfoMoneyEdit.pas' {InfoMoneyEditForm: TParentForm},
//  InfoMoneyGroup in '..\..\Forms\Guides\InfoMoneyGroup.pas' {InfoMoneyGroupForm: TParentForm},
//  InfoMoneyGroup_Object in '..\..\Forms\Guides\InfoMoneyGroup_Object.pas' {InfoMoneyGroup_ObjectForm: TParentForm},
//  InfoMoneyGroupEdit in '..\..\Forms\Guides\InfoMoneyGroupEdit.pas' {InfoMoneyGroupEditForm: TParentForm},
//  ProfitLossDirectionTest in '..\SOURCEBoutique\Objects\All\ProfitLossDirectionTest.pas',
//  ProfitLossGroupTest in '..\SOURCEBoutique\Objects\All\ProfitLossGroupTest.pas',
//  ProfitLossTest in '..\SOURCEBoutique\Objects\All\ProfitLossTest.pas',
//  ProfitLoss in '..\..\Forms\Guides\ProfitLoss.pas' {ProfitLossForm: TParentForm},
//  ProfitLoss_Object in '..\..\Forms\Guides\ProfitLoss_Object.pas' {ProfitLoss_ObjectForm: TParentForm},
//  ProfitLossDirection in '..\..\Forms\Guides\ProfitLossDirection.pas' {ProfitLossDirectionForm: TParentForm},
//  ProfitLossDirection_Object in '..\..\Forms\Guides\ProfitLossDirection_Object.pas' {ProfitLossDirection_ObjectForm: TParentForm},
//  ProfitLossDirectionEdit in '..\..\Forms\Guides\ProfitLossDirectionEdit.pas' {ProfitLossDirectionEditForm: TParentForm},
//  ProfitLossEdit in '..\..\Forms\Guides\ProfitLossEdit.pas' {ProfitLossEditForm: TParentForm},
//  ProfitLossGroup in '..\..\Forms\Guides\ProfitLossGroup.pas' {ProfitLossGroupForm: TParentForm},
//  ProfitLossGroup_Object in '..\..\Forms\Guides\ProfitLossGroup_Object.pas' {ProfitLossGroup_ObjectForm: TParentForm},
//  ProfitLossGroupEdit in '..\..\Forms\Guides\ProfitLossGroupEdit.pas' {ProfitLossGroupEditForm: TParentForm},
//  ReturnTypeTest in '..\SOURCEBoutique\Objects\All\ReturnTypeTest.pas',
//  ReturnType in '..\..\Forms\Kind\ReturnType.pas' {ReturnTypeForm: TParentForm},
//  ReturnTypeEdit in '..\..\Forms\Kind\ReturnTypeEdit.pas' {ReturnTypeEditForm: TParentForm},
//  LossDebtTest in '..\SOURCEBoutique\Movement\All\Farmacy\LossDebtTest.pas',
//  LossDebtMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\LossDebtMovementItemTest.pas',
//  LossDebt in '..\..\FormsFarmacy\Document\LossDebt.pas' {LossDebtForm: TParentForm},
//  LossDebtJournal in '..\..\FormsFarmacy\Document\LossDebtJournal.pas' {LossDebtJournalForm: TParentForm},
//  MovementItemContainer in '..\..\Forms\System\MovementItemContainer.pas' {MovementItemContainerForm: TParentForm},
//  Report_Balance in '..\..\Forms\Report\Report_Balance.pas' {Report_BalanceForm: TParentForm},
//  ReturnOutJournal in '..\..\FormsFarmacy\Document\ReturnOutJournal.pas' {ReturnOutJournalForm: TParentForm},
//  ReturnOutTest in '..\SOURCEBoutique\Movement\All\Farmacy\ReturnOutTest.pas',
//  IncomeJournalChoice in '..\..\FormsFarmacy\Document\IncomeJournalChoice.pas' {IncomeJournalChoiceForm: TParentForm},
//  BankAccountJournal in '..\..\Forms\Document\BankAccountJournal.pas' {BankAccountJournalForm: TParentForm},
//  BankAccountMovement in '..\..\Forms\Document\BankAccountMovement.pas' {BankAccountMovementForm: TParentForm},
//  BankAccountJournalFarmacy in '..\..\FormsFarmacy\Document\BankAccountJournalFarmacy.pas' {BankAccountJournalFarmacyForm},
//  BankAccountMovementFarmacy in '..\..\FormsFarmacy\Document\BankAccountMovementFarmacy.pas' {BankAccountMovementFarmacyForm: TParentForm},
//  BankAccountMovementTest in '..\SOURCEBoutique\Movement\All\Farmacy\BankAccountMovementTest.pas',
//  InfoMoney_Object in '..\..\Forms\Guides\InfoMoney_Object.pas' {InfoMoney_ObjectForm: TParentForm},
//  MoneyPlace_Object in '..\..\FormsFarmacy\Guides\MoneyPlace_Object.pas' {MoneyPlace_ObjectForm: TParentForm},
//  BankStatement in '..\..\FormsFarmacy\Document\BankStatement.pas' {BankStatementForm: TParentForm},
//  BankStatementJournal in '..\..\FormsFarmacy\Document\BankStatementJournal.pas' {BankStatementJournalForm: TParentForm},
//  BankStatementTest in '..\SOURCEBoutique\Movement\All\BankStatementTest.pas',
//  BankStatementItemTest in '..\SOURCEBoutique\Movement\All\BankStatementItemTest.pas',
//  Report_JuridicalCollation in '..\..\FormsFarmacy\Report\Report_JuridicalCollation.pas' {Report_JuridicalCollationForm: TParentForm},
//  Report_JuridicalSold in '..\..\FormsFarmacy\Report\Report_JuridicalSold.pas' {Report_JuridicalSoldForm: TParentForm},
//  StatusXML in '..\..\SOURCE\EDI\StatusXML.pas',
//  SendOnPrice in '..\..\FormsFarmacy\Document\SendOnPrice.pas' {SendOnPriceForm: TParentForm},
//  SendOnPriceJournal in '..\..\FormsFarmacy\Document\SendOnPriceJournal.pas' {SendOnPriceJournalForm: TParentForm},
//  MarginCategory in '..\..\Forms\Guides\MarginCategory.pas' {MarginCategoryForm: TParentForm},
//  MarginCategoryItem in '..\..\Forms\Guides\MarginCategoryItem.pas' {MarginCategoryItemForm: TParentForm},
//  MarginCategoryLink in '..\..\Forms\Guides\MarginCategoryLink.pas' {MarginCategoryLinkForm: TParentForm},
//  dsdException in '..\..\SOURCE\dsdException.pas',
//  MovementDescForms in '..\..\Forms\System\MovementDescForms.pas' {MovementDescDataForm: TParentForm},
//  IncomePharmacy in '..\..\FormsFarmacy\Document\IncomePharmacy.pas' {IncomePharmacyForm: TParentForm},
//  IncomePharmacyJournal in '..\..\FormsFarmacy\Document\IncomePharmacyJournal.pas' {IncomePharmacyJournalForm: TParentForm},
//  LoadFarmacyReportTest in '..\SOURCEBoutique\LoadFarmacyReportTest.pas',
//  CheckJournal in '..\..\Forms\Document\CheckJournal.pas' {CheckJournalForm: TParentForm},
//  Check in '..\..\Forms\Document\Check.pas' {CheckForm: TParentForm},
//  CashRegisterKind in '..\..\Forms\Kind\CashRegisterKind.pas' {CashRegisterKindForm: TParentForm},
//  CashRegister in '..\..\Forms\Guides\CashRegister.pas' {CashRegisterForm: TParentForm},
//  CashRegisterEdit in '..\..\Forms\Guides\CashRegisterEdit.pas' {CashRegisterEditForm: TParentForm},
    AncestorReport in '..\..\Forms\Ancestor\AncestorReport.pas' {AncestorReportForm: TParentForm},
//  Report_RemainGoods in '..\..\FormsFarmacy\Report\Report_RemainGoods.pas' {Report_GoodsRemainsForm: TParentForm},
//  Report_GoodsPartionMove in '..\..\FormsFarmacy\Report\Report_GoodsPartionMove.pas' {Report_GoodsPartionMoveForm: TParentForm},
//  PriceTest in '..\SOURCEBoutique\Objects\All\Farmacy\PriceTest.pas',
//  AlternativeGroupTest in '..\SOURCEBoutique\Objects\All\Farmacy\AlternativeGroupTest.pas',
//  AlternativeGroup in '..\..\FormsFarmacy\Guides\AlternativeGroup.pas' {AlternativeGroupForm: TParentForm},
//  RepriceUnit in '..\..\FormsFarmacy\ConnectWithOld\RepriceUnit.pas' {RepriceUnitForm},
//  CheckVIP in '..\..\FormsFarmacy\Document\CheckVIP.pas' {CheckVIPForm: TParentForm},
//  CheckDeferred in '..\..\FormsFarmacy\Document\CheckDeferred.pas' {CheckDeferredForm: TParentForm},
//  PaidType in '..\..\Forms\Guides\PaidType.pas' {PaidTypeForm: TParentForm},
//  PaidTypeTest in '..\SOURCEBoutique\Objects\All\Farmacy\PaidTypeTest.pas',
//  CashRegisterTest in '..\SOURCEBoutique\Objects\All\Farmacy\CashRegisterTest.pas',
//  InventoryTest in '..\SOURCEBoutique\Movement\All\Farmacy\InventoryTest.pas',
//  Inventory in '..\..\FormsFarmacy\Document\Inventory.pas' {InventoryForm: TParentForm},
//  InventoryJournal in '..\..\FormsFarmacy\Document\InventoryJournal.pas' {InventoryJournalForm: TParentForm},
//  InventoryMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\InventoryMovementItemTest.pas',
//  LossTest in '..\SOURCEBoutique\Movement\All\Farmacy\LossTest.pas',
//  LossMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\LossMovementItemTest.pas',
//  ArticleLossTest in '..\SOURCEBoutique\Objects\All\Farmacy\ArticleLossTest.pas',
//  Loss in '..\..\FormsFarmacy\Document\Loss.pas' {LossForm: TParentForm},
//  LossJournal in '..\..\FormsFarmacy\Document\LossJournal.pas' {LossJournalForm: TParentForm},
//  ArticleLoss in '..\..\Forms\Guides\ArticleLoss.pas' {ArticleLossForm: TParentForm},
//  ArticleLossEdit in '..\..\Forms\Guides\ArticleLossEdit.pas' {ArticleLossEditForm: TParentForm},
//  Send in '..\..\FormsFarmacy\Document\Send.pas' {SendForm: TParentForm},
//  SendJournal in '..\..\FormsFarmacy\Document\SendJournal.pas' {SendJournalForm: TParentForm},
//  SendTest in '..\SOURCEBoutique\Movement\All\Farmacy\SendTest.pas',
//  SendMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\SendMovementItemTest.pas',
//  CreateOrderFromMCS in '..\..\FormsFarmacy\Document\CreateOrderFromMCS.pas' {CreateOrderFromMCSForm: TParentForm},
//  CheckJournalUser in '..\..\Forms\Document\CheckJournalUser.pas' {CheckJournalUserForm: TParentForm},
//  MCS in '..\..\Forms\Guides\MCS.pas' {MCSForm: TParentForm},
//  PartionGoodsChoice in '..\..\Forms\Guides\PartionGoodsChoice.pas' {PartionGoodsChoiceForm: TParentForm},
//  Report_GoodsPartionHistory in '..\..\FormsFarmacy\Report\Report_GoodsPartionHistory.pas' {Report_GoodsPartionHistoryForm: TParentForm},
//  RecalcMCS_Dialog in '..\..\FormsFarmacy\System\RecalcMCS_Dialog.pas' {RecalcMCS_DialogForm: TParentForm},
//  ReportSoldParams in '..\..\FormsFarmacy\Object\ReportSoldParams.pas' {ReportSoldParamsForm: TParentForm},
//  ReportSoldParamsTest in '..\SOURCEBoutique\Objects\All\Farmacy\ReportSoldParamsTest.pas',
//  Report_Sold in '..\..\FormsFarmacy\Report\Report_Sold.pas' {Report_SoldForm: TParentForm},
//  Report_Sold_Day in '..\..\FormsFarmacy\Report\Report_Sold_Day.pas' {Report_Sold_DayForm: TParentForm},
//  Report_Sold_DayUser in '..\..\FormsFarmacy\Report\Report_Sold_DayUser.pas' {Report_Sold_DayUserForm: TParentForm},
//  RecadvXML in '..\..\SOURCE\EDI\RecadvXML.pas',
//  AdditionalGoodsTest in '..\SOURCEBoutique\Objects\All\Farmacy\AdditionalGoodsTest.pas',
//  SaleTest in '..\SOURCEBoutique\Movement\All\Farmacy\SaleTest.pas',
//  SaleMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\SaleMovementItemTest.pas',
//  SaleJournal in '..\..\FormsFarmacy\Document\SaleJournal.pas' {SaleJournalForm: TParentForm},
//  Sale in '..\..\FormsFarmacy\Document\Sale.pas' {SaleForm: TParentForm},
//  PaidKind in '..\..\Forms\Kind\PaidKind.pas' {PaidKindForm: TParentForm},
//  Report_Movement_ByPartionGoods in '..\..\FormsFarmacy\Report\Report_Movement_ByPartionGoods.pas' {Report_Movement_ByPartionGoodsForm: TParentForm},
//  PaymentTest in '..\SOURCEBoutique\Movement\All\Farmacy\PaymentTest.pas',
//  PaymentMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\PaymentMovementItemTest.pas',
//  Payment in '..\..\FormsFarmacy\Document\Payment.pas' {PaymentForm: TParentForm},
//  PaymentJournal in '..\..\FormsFarmacy\Document\PaymentJournal.pas' {PaymentJournalForm: TParentForm},
//  JuridicalCorporate in '..\..\FormsFarmacy\Guides\JuridicalCorporate.pas' {JuridicalCorporateForm: TParentForm},
//  ReasonDifferences in '..\..\FormsFarmacy\Guides\ReasonDifferences.pas' {ReasonDifferencesForm: TParentForm},
//  ReasonDifferencesTest in '..\SOURCEBoutique\Objects\All\Farmacy\ReasonDifferencesTest.pas',
//  Income_AmountTrouble in '..\..\FormsFarmacy\Document\Income_AmountTrouble.pas' {Income_AmountTroubleForm: TParentForm},
//  Report_UploadBaDM in '..\..\FormsFarmacy\Report\Report_UploadBaDM.pas' {Report_UploadBaDMForm: TParentForm},
//  Report_UploadOptima in '..\..\FormsFarmacy\Report\Report_UploadOptima.pas' {Report_UploadOptimaForm: TParentForm},
//  RepriceTest in '..\SOURCEBoutique\Movement\All\Farmacy\RepriceTest.pas',
//  RepriceMovementItemTest in '..\SOURCEBoutique\MovementItem\All\Farmacy\RepriceMovementItemTest.pas',
//  RepriceJournal in '..\..\FormsFarmacy\Document\RepriceJournal.pas' {RepriceJournalForm: TParentForm},
//  Reprice in '..\..\FormsFarmacy\Document\Reprice.pas' {RepriceForm: TParentForm},
//  ChangeIncomePaymentKindTest in '..\SOURCEBoutique\Objects\All\Farmacy\ChangeIncomePaymentKindTest.pas',
//  ChangeIncomePaymentKind in '..\..\FormsFarmacy\Guides\ChangeIncomePaymentKind.pas' {ChangeIncomePaymentKindForm: TParentForm},
//  ChangeIncomePaymentTest in '..\SOURCEBoutique\Movement\All\Farmacy\ChangeIncomePaymentTest.pas',
//  ChangeIncomePaymentJournal in '..\..\FormsFarmacy\Document\ChangeIncomePaymentJournal.pas' {ChangeIncomePaymentJournalForm: TParentForm},
//  ChangeIncomePayment in '..\..\FormsFarmacy\Document\ChangeIncomePayment.pas' {ChangeIncomePaymentForm: TParentForm},
//  PriceHistory in '..\..\FormsFarmacy\Guides\PriceHistory.pas' {PriceHistoryForm: TParentForm},
//  ReturnOutPartnerDataDialog in '..\..\FormsFarmacy\Document\ReturnOutPartnerDataDialog.pas' {ReturnOutPartnerDataDialogForm: TParentForm},
//  IncomePartnerDataDialog in '..\..\FormsFarmacy\Document\IncomePartnerDataDialog.pas' {IncomePartnerDataDialogForm: TParentForm},
//  PersonalGroupEdit in '..\..\FormsFarmacy\Guides\PersonalGroupEdit.pas' {PersonalGroupEditForm: TParentForm},
//  PersonalGroup in '..\..\FormsFarmacy\Guides\PersonalGroup.pas' {PersonalGroupForm: TParentForm},
//  PersonalEdit in '..\..\FormsFarmacy\Guides\PersonalEdit.pas' {PersonalEditForm: TParentForm},
//  Personal_Object in '..\..\FormsFarmacy\Guides\Personal_Object.pas' {Personal_ObjectForm: TParentForm},
//  Personal in '..\..\FormsFarmacy\Guides\Personal.pas' {PersonalForm: TParentForm},
//  Education in '..\..\FormsFarmacy\Guides\Education.pas' {EducationForm: TParentForm},
//  EducationEdit in '..\..\FormsFarmacy\Guides\EducationEdit.pas' {EducationEditForm: TParentForm},
//  Position in '..\..\FormsFarmacy\Guides\Position.pas' {PositionForm: TParentForm},
//  PositionEdit in '..\..\FormsFarmacy\Guides\PositionEdit.pas' {PositionEditForm: TParentForm},
//  Calendar in '..\..\FormsFarmacy\Guides\Calendar.pas' {CalendarForm: TParentForm},
//  WorkTimeKind_Object in '..\..\FormsFarmacy\Kind\WorkTimeKind_Object.pas' {WorkTimeKind_ObjectForm: TParentForm},
//  WorkTimeKind in '..\..\FormsFarmacy\Kind\WorkTimeKind.pas' {WorkTimeKindForm: TParentForm},
//  Member in '..\..\FormsFarmacy\Guides\Member.pas' {MemberForm: TParentForm},
//  MemberEdit in '..\..\FormsFarmacy\Guides\MemberEdit.pas' {MemberEditForm: TParentForm},
//  SheetWorkTimeJournal in '..\..\FormsFarmacy\Document\SheetWorkTimeJournal.pas' {SheetWorkTimeJournalForm: TParentForm},
//  SheetWorkTime in '..\..\FormsFarmacy\Document\SheetWorkTime.pas' {SheetWorkTimeForm: TParentForm},
//  Report_MovementIncome in '..\..\FormsFarmacy\Report\Report_MovementIncome.pas' {Report_MovementIncomeForm: TParentForm},
//  SheetWorkTimeAddRecord in '..\..\FormsFarmacy\Document\SheetWorkTimeAddRecord.pas' {SheetWorkTimeAddRecordForm: TParentForm},
//  GoodsGroup in '..\..\FormsFarmacy\Guides\GoodsGroup.pas' {GoodsGroupForm: TParentForm},
//  GoodsGroupEdit in '..\..\FormsFarmacy\Guides\GoodsGroupEdit.pas' {GoodsGroupEditForm: TParentForm},
//  GoodsGroup_Object in '..\..\FormsFarmacy\Guides\GoodsGroup_Object.pas' {GoodsGroup_ObjectForm: TParentForm},
//  Report_LiquidDialog in '..\..\FormsFarmacy\Report\Report_LiquidDialog.pas' {Report_LiquidDialogForm: TParentForm},
//  Report_Wage in '..\..\FormsFarmacy\Report\Report_Wage.pas' {Report_WageForm: TParentForm},
//  Report_WageDialog in '..\..\FormsFarmacy\Report\Report_WageDialog.pas' {Report_WageDialogForm: TParentForm},
//  PriceDialog in '..\..\FormsFarmacy\Guides\PriceDialog.pas' {PriceDialogForm: TParentForm},
//  GoodsAll in '..\..\FormsFarmacy\Guides\GoodsAll.pas' {GoodsAllForm: TParentForm},
//  GoodsAllJuridical in '..\..\FormsFarmacy\Guides\GoodsAllJuridical.pas' {GoodsAllJuridicalForm: TParentForm},
//  GoodsAllRetail in '..\..\FormsFarmacy\Guides\GoodsAllRetail.pas' {GoodsAllRetailForm: TParentForm},
//  EmailKind in '..\..\FormsFarmacy\Kind\EmailKind.pas' {EmailKindForm: TParentForm},
//  EmailTools in '..\..\FormsFarmacy\Kind\EmailTools.pas' {EmailToolsForm: TParentForm},
//  EmailSettings in '..\..\FormsFarmacy\Guides\EmailSettings.pas' {EmailSettingsForm: TParentForm},
//  Movement_PeriodDialog in '..\..\FormsFarmacy\Document\Movement_PeriodDialog.pas' {Movement_PeriodDialogForm: TParentForm},
//  Report_Liquid in '..\..\FormsFarmacy\Report\Report_Liquid.pas' {Report_LiquidForm: TParentForm},
//  PriceOnDate in '..\..\FormsFarmacy\Guides\PriceOnDate.pas' {PriceOnDateForm: TParentForm},
//  BankAccountJournalFarmacyDialog in '..\..\FormsFarmacy\Document\BankAccountJournalFarmacyDialog.pas' {BankAccountJournalFarmacyDialogForm: TParentForm},
//  QualityNumberJournal in '..\..\Forms\Document\QualityNumberJournal.pas' {QualityNumberJournalForm: TParentForm},
//  QualityNumber in '..\..\Forms\Document\QualityNumber.pas' {QualityNumberForm: TParentForm},
//  Report_Profit in '..\..\FormsFarmacy\Report\Report_Profit.pas' {Report_ProfitForm: TParentForm},
//  Report_ProfitDialog in '..\..\FormsFarmacy\Report\Report_ProfitDialog.pas' {Report_ProfitDialogForm: TParentForm},
//  Report_PriceInterventionDialog in '..\..\FormsFarmacy\Report\Report_PriceInterventionDialog.pas' {Report_PriceInterventionDialogForm: TParentForm},
//  Report_MovementCheckDialog in '..\..\FormsFarmacy\Report\Report_MovementCheckDialog.pas' {Report_MovementCheckDialogForm: TParentForm},
//  Report_RemainGoodsDialog in '..\..\FormsFarmacy\Report\Report_RemainGoodsDialog.pas' {Report_GoodsRemainsDialogForm: TParentForm},
//  Report_MovementCheckFarmDialog in '..\..\FormsFarmacy\Report\Report_MovementCheckFarmDialog.pas' {Report_MovementCheckFarmDialogForm: TParentForm},
//  ReportMovementCheckFarm in '..\..\FormsFarmacy\Report\ReportMovementCheckFarm.pas' {ReportMovementCheckFarmForm: TParentForm},
//  Report_PriceIntervention in '..\..\FormsFarmacy\Report\Report_PriceIntervention.pas' {Report_PriceInterventionForm: TParentForm},
//  Report_MovementIncomeDialog in '..\..\FormsFarmacy\Report\Report_MovementIncomeDialog.pas' {Report_MovementIncomeDialogForm: TParentForm},
//  MarginReport in '..\..\FormsFarmacy\Guides\MarginReport.pas' {MarginReportForm: TParentForm},
//  MarginReportItem in '..\..\FormsFarmacy\Guides\MarginReportItem.pas' {MarginReportItemForm: TParentForm},
//  Report_MovementIncomeFarmDialog in '..\..\FormsFarmacy\Report\Report_MovementIncomeFarmDialog.pas' {Report_MovementIncomeFarmDialogForm: TParentForm},
//  Report_MovementIncomeFarm in '..\..\FormsFarmacy\Report\Report_MovementIncomeFarm.pas' {Report_MovementIncomeFarmForm: TParentForm},
//  Report_PriceIntervention2 in '..\..\FormsFarmacy\Report\Report_PriceIntervention2.pas' {Report_PriceIntervention2Form: TParentForm},
//  ReturnOut in '..\..\FormsFarmacy\Document\ReturnOut.pas' {ReturnOutForm: TParentForm},
//  ChoiceGoodsFromRemains in '..\..\FormsFarmacy\System\ChoiceGoodsFromRemains.pas' {ChoiceGoodsFromRemainsForm: TParentForm},
//  Report_GoodsOnUnit_ForSite in '..\..\FormsFarmacy\Report\Report_GoodsOnUnit_ForSite.pas' {Report_GoodsOnUnit_ForSiteForm: TParentForm},
//  Report_GoodsOnUnit_ForSiteDialog in '..\..\FormsFarmacy\Report\Report_GoodsOnUnit_ForSiteDialog.pas' {Report_GoodsOnUnit_ForSiteDialogForm: TParentForm},
//  Report_MovementCheckMiddleDialog in '..\..\FormsFarmacy\Report\Report_MovementCheckMiddleDialog.pas' {Report_MovementCheckMiddleDialogForm: TParentForm},
//  ReportMovementCheck in '..\..\FormsFarmacy\Report\ReportMovementCheck.pas' {ReportMovementCheckForm: TParentForm},
//  OrderExternalJournalChoice in '..\..\FormsFarmacy\Document\OrderExternalJournalChoice.pas' {OrderExternalJournalChoiceForm: TParentForm},
//  Income in '..\..\FormsFarmacy\Document\Income.pas' {IncomeForm: TParentForm},
//  Promo in '..\..\FormsFarmacy\Document\Promo.pas' {PromoForm: TParentForm},
//  PromoJournal in '..\..\FormsFarmacy\Document\PromoJournal.pas' {PromoJournalForm: TParentForm},
//  ReportMovementCheckMiddle in '..\..\FormsFarmacy\Report\ReportMovementCheckMiddle.pas' {ReportMovementCheckMiddleForm: TParentForm},
//  Report_RemainsOverGoodsDialog in '..\..\FormsFarmacy\Report\Report_RemainsOverGoodsDialog.pas' {Report_RemainsOverGoodsDialogForm: TParentForm},
//  MovementItemProtocol in '..\..\Forms\System\MovementItemProtocol.pas' {MovementItemProtocolForm: TParentForm},
//  UnitForFarmacyCash in '..\..\FormsFarmacy\Guides\UnitForFarmacyCash.pas' {UnitForFarmacyCashForm: TParentForm},
//  Report_GoodsPartionMoveDialog in '..\..\FormsFarmacy\Report\Report_GoodsPartionMoveDialog.pas' {Report_GoodsPartionMoveDialogForm: TParentForm},
//  Email in '..\..\FormsFarmacy\Guides\Email.pas' {EmailForm: TParentForm},
//  EmailEdit in '..\..\FormsFarmacy\Guides\EmailEdit.pas' {EmailEditForm: TParentForm},
//  Price in '..\..\FormsFarmacy\Guides\Price.pas' {PriceForm: TParentForm},
//  Report_GoodsPartionHistoryDialog in '..\..\FormsFarmacy\Report\Report_GoodsPartionHistoryDialog.pas' {Report_GoodsPartionHistoryDialogForm: TParentForm},
//  Over in '..\..\FormsFarmacy\Document\Over.pas' {OverForm: TParentForm},
//  OverJournal in '..\..\FormsFarmacy\Document\OverJournal.pas' {OverJournalForm: TParentForm},
//  RoleUnion in '..\..\Forms\RoleUnion.pas' {RoleUnionForm: TParentForm} ,
//  Report_RemainsOverGoods in '..\..\FormsFarmacy\Report\Report_RemainsOverGoods.pas' {Report_RemainsOverGoodsForm: TParentForm},
//  PriceGoodsDialog in '..\..\FormsFarmacy\Guides\PriceGoodsDialog.pas' {PriceGoodsDialogForm: TParentForm},
//  Color in '..\..\FormsFarmacy\System\Color.pas' {ColorForm: TParentForm},
//  OverSettingsEdit in '..\..\FormsFarmacy\Guides\OverSettingsEdit.pas' {OverSettingsEditForm: TParentForm},
//  OverSettings in '..\..\FormsFarmacy\Guides\OverSettings.pas' {OverSettingsForm: TParentForm},
//  DiscountExternalToolsEdit in '..\..\FormsFarmacy\Guides\DiscountExternalToolsEdit.pas' {DiscountExternalToolsEditForm: TParentForm},
//  DiscountCard in '..\..\FormsFarmacy\Guides\DiscountCard.pas' {DiscountCardForm: TParentForm},
//  BarCodeEdit in '..\..\FormsFarmacy\Guides\BarCodeEdit.pas' {BarCodeEditForm: TParentForm},
//  BarCode in '..\..\FormsFarmacy\Guides\BarCode.pas' {BarCodeForm: TParentForm},
//  DiscountExternalTools_Object in '..\..\FormsFarmacy\Guides\DiscountExternalTools_Object.pas' {DiscountExternalTools_ObjectForm: TParentForm},
//  DiscountCardEdit in '..\..\FormsFarmacy\Guides\DiscountCardEdit.pas' {DiscountCardEditForm: TParentForm},
//  DiscountExternal_Object in '..\..\FormsFarmacy\Guides\DiscountExternal_Object.pas' {DiscountExternal_ObjectForm: TParentForm},
//  ConfirmedKind in '..\..\FormsFarmacy\Kind\ConfirmedKind.pas' {ConfirmedKindForm: TParentForm},
//  DiscountExternal in '..\..\FormsFarmacy\Guides\DiscountExternal.pas' {DiscountExternalForm: TParentForm},
//  DiscountExternalEdit in '..\..\FormsFarmacy\Guides\DiscountExternalEdit.pas' {DiscountExternalEditForm: TParentForm},
//  DiscountExternalTools in '..\..\FormsFarmacy\Guides\DiscountExternalTools.pas' {DiscountExternalToolsForm: TParentForm},
//  PriceGroupSettingsTOP in '..\..\FormsFarmacy\Guides\PriceGroupSettingsTOP.pas' {PriceGroupSettingsTopForm: TParentForm},
//  Report_MovementCheck_UnLiquid in '..\..\FormsFarmacy\Report\Report_MovementCheck_UnLiquid.pas' {Report_MovementCheck_UnLiquidForm: TParentForm},
//  Report_MovementCheck_UnLiquidDialog in '..\..\FormsFarmacy\Report\Report_MovementCheck_UnLiquidDialog.pas' {Report_MovementCheck_UnLiquidDialogForm: TParentForm},
//  Report_Payment_Plan in '..\..\FormsFarmacy\Report\Report_Payment_Plan.pas' {Report_Payment_PlanForm: TParentForm},
//  Report_Payment_PlanDialog in '..\..\FormsFarmacy\Report\Report_Payment_PlanDialog.pas' {Report_Payment_PlanDialogForm: TParentForm},
//  Report_MovementCheckErrorDialog in '..\..\FormsFarmacy\Report\Report_MovementCheckErrorDialog.pas' {Report_MovementCheckErrorDialogForm: TParentForm},
//  Report_MovementCheckError in '..\..\FormsFarmacy\Report\Report_MovementCheckError.pas' {Report_MovementCheckErrorForm: TParentForm},
//  MCS_Lite in '..\..\FormsFarmacy\Guides\MCS_Lite.pas' {MCS_LiteForm: TParentForm},
//  OrderShedule in '..\..\FormsFarmacy\Guides\OrderShedule.pas' {OrderSheduleForm: TParentForm},
//  OrderSheduleEdit in '..\..\FormsFarmacy\Guides\OrderSheduleEdit.pas' {OrderSheduleEditForm: TParentForm},
//  CheckVIP_Error in '..\..\FormsFarmacy\Document\CheckVIP_Error.pas' {CheckVIP_ErrorForm: TParentForm},
//  Report_MovementIncome_Promo in '..\..\FormsFarmacy\Report\Report_MovementIncome_Promo.pas' {Report_MovementIncome_PromoForm: TParentForm},
//  Report_MovementCheck_Promo in '..\..\FormsFarmacy\Report\Report_MovementCheck_Promo.pas' {Report_MovementCheck_PromoForm: TParentForm},
//  InventoryPartion in '..\..\FormsFarmacy\Document\InventoryPartion.pas' {InventoryPartionForm: TParentForm},
//  CheckPrintDialog in '..\..\FormsFarmacy\Document\CheckPrintDialog.pas' {CheckPrintDialogForm: TParentForm},
//  Report_CheckPromo in '..\..\FormsFarmacy\Report\Report_CheckPromo.pas' {Report_CheckPromoForm: TParentForm},
//  Report_PeriodDialog in '..\..\FormsFarmacy\Report\Report_PeriodDialog.pas' {Report_PeriodDialogForm: TParentForm},
//  KindOutSP in '..\..\FormsFarmacy\Guides\KindOutSP.pas' {KindOutSPForm: TParentForm},
//  KindOutSPEdit in '..\..\FormsFarmacy\Guides\KindOutSPEdit.pas' {KindOutSPEditForm: TParentForm},
//  IntenalSPEdit in '..\..\FormsFarmacy\Guides\IntenalSPEdit.pas' {IntenalSPEditForm: TParentForm},
//  IntenalSP in '..\..\FormsFarmacy\Guides\IntenalSP.pas' {IntenalSPForm: TParentForm},
//  BrandSP in '..\..\FormsFarmacy\Guides\BrandSP.pas' {BrandSPForm: TParentForm},
//  BrandSPEdit in '..\..\FormsFarmacy\Guides\BrandSPEdit.pas' {BrandSPEditForm: TParentForm},
//  GoodsSP in '..\..\FormsFarmacy\Guides\GoodsSP.pas' {GoodsSPForm: TParentForm},
//  Report_CheckSP in '..\..\FormsFarmacy\Report\Report_CheckSP.pas' {Report_CheckSPForm: TParentForm},
//  Report_CheckSPDialog in '..\..\FormsFarmacy\Report\Report_CheckSPDialog.pas' {Report_CheckSPDialogForm: TParentForm},
//  PartnerMedical in '..\..\FormsFarmacy\Guides\PartnerMedical.pas' {PartnerMedicalForm: TParentForm},
//  PartnerMedicalEdit in '..\..\FormsFarmacy\Guides\PartnerMedicalEdit.pas' {PartnerMedicalEditForm: TParentForm},
//  ConditionsKeepEdit in '..\..\FormsFarmacy\Guides\ConditionsKeepEdit.pas' {ConditionsKeepEditForm: TParentForm},
//  ConditionsKeep in '..\..\FormsFarmacy\Guides\ConditionsKeep.pas' {ConditionsKeepForm: TParentForm},
//  ReportPromoParams in '..\..\FormsFarmacy\Object\ReportPromoParams.pas' {ReportPromoParamsForm: TParentForm},
//  Report_MinPrice_onGoods in '..\..\FormsFarmacy\Report\Report_MinPrice_onGoods.pas' {Report_MinPrice_onGoodsForm: TParentForm},
//  Report_MinPrice_onGoodsDialog in '..\..\FormsFarmacy\Report\Report_MinPrice_onGoodsDialog.pas' {Report_MinPrice_onGoodsDialogForm: TParentForm},
//  Contract_Object in '..\..\FormsFarmacy\Guides\Contract_Object.pas' {Contract_ObjectForm: TParentForm},
//  Report_Badm in '..\..\FormsFarmacy\Report\Report_Badm.pas' {Report_BadmForm: TParentForm},
//  Unit_byReportBadm in '..\..\FormsFarmacy\Guides\Unit_byReportBadm.pas' {Unit_byReportBadmForm: TParentForm},
//  Unit_Object in '..\..\FormsFarmacy\Guides\Unit_Object.pas' {Unit_ObjectForm: TParentForm},
//  DataTimeDialog in '..\..\FormsFarmacy\Document\DataTimeDialog.pas' {DataTimeDialogForm: TParentForm},
//  MarginCategory_Cross in '..\..\FormsFarmacy\Object\MarginCategory_Cross.pas' {MarginCategory_CrossForm: TParentForm},
//  MarginCategory_Total in '..\..\FormsFarmacy\Object\MarginCategory_Total.pas' {MarginCategory_TotalForm: TParentForm},
//  MarginCategory_CrossDialog in '..\..\FormsFarmacy\Object\MarginCategory_CrossDialog.pas' {MarginCategory_CrossDialogForm: TParentForm},
//  PromoUnit in '..\..\FormsFarmacy\Document\PromoUnit.pas' {PromoUnitForm: TParentForm},
//  PromoUnitJournal in '..\..\FormsFarmacy\Document\PromoUnitJournal.pas' {PromoUnitJournalForm: TParentForm},
//  Report_MovementCheck_Cross in '..\..\FormsFarmacy\Report\Report_MovementCheck_Cross.pas' {Report_MovementCheck_CrossForm: TParentForm},
//  GroupMemberSPEdit in '..\..\FormsFarmacy\Guides\GroupMemberSPEdit.pas' {GroupMemberSPEditForm: TParentForm},
//  GroupMemberSP in '..\..\FormsFarmacy\Guides\GroupMemberSP.pas' {GroupMemberSPForm: TParentForm},
//  MarginCategoryItemHistory in '..\..\FormsFarmacy\Guides\MarginCategoryItemHistory.pas' {MarginCategoryItemHistoryForm: TParentForm}

Vcl.Dialogs
;
{$R *.res}
{$R DevExpressRus.res}

begin
  ConnectionPath := '..\INIT\Boutique_init.php';
  EnumPath := '..\DATABASE\Boutique\METADATA\Enum\';
  CreateStructurePath := '..\DATABASE\Boutique\STRUCTURE\';
  LocalViewPath := '..\DATABASE\Boutique\View\';
  LocalProcedurePath := '..\DATABASE\Boutique\PROCEDURE\';
  LocalProcessPath := '..\DATABASE\COMMONBoutique\Boutique\PROCESS\';

  dsdProject := prBoutique;

  if FindCmdLineSwitch('realboutique', true)
  then gc_AdminPassword := 'Админ1234'
  else gc_AdminPassword := 'Админ';

  gc_ProgramName := 'Boutique.exe';

  Application.Initialize;
  gc_isSetDefault := true;
  Application.CreateForm(TdmMain, dmMain);
  Application.Run;

  DUnitTestRunner.RunRegisteredTests;
end.
