program ProjectBoatTest;

uses
  Forms,
  DUnitTestRunner,
  SysUtils,
  dbCreateStructureTest in '..\SOURCEBoat\STRUCTURE\dbCreateStructureTest.pas',
  dbMetadataTest in '..\SOURCEBoat\METADATA\dbMetadataTest.pas',
  zLibUtil in '..\SOURCE\zLibUtil.pas',
  CommonFunctionTest in '..\SOURCEBoat\Function\CommonFunctionTest.pas',
  UtilConst in '..\SOURCEBoat\UtilConst.pas',
  dbEnumTest in '..\SOURCEBoat\dbEnumTest.pas',
  ProcessTest in '..\SOURCEBoat\Process\ProcessTest.pas',
  dbCreateViewTest in '..\SOURCEBoat\View\dbCreateViewTest.pas',
  DefaultsTest in '..\SOURCEBoat\Defaults\DefaultsTest.pas',
  CommonData in '..\..\SOURCE\CommonData.pas',
  Authentication in '..\..\SOURCE\Authentication.pas',
  FormStorage in '..\..\SOURCE\FormStorage.pas',
  ParentForm in '..\..\SOURCE\ParentForm.pas' {ParentForm},
  Storage in '..\..\SOURCE\Storage.pas',
  UtilConvert in '..\..\SOURCE\UtilConvert.pas',
  dsdAction in '..\..\SOURCE\COMPONENT\dsdAction.pas',
  dsdAddOn in '..\..\SOURCE\COMPONENT\dsdAddOn.pas',
  dsdDB in '..\..\SOURCE\COMPONENT\dsdDB.pas',
  dsdGuides in '..\..\SOURCE\COMPONENT\dsdGuides.pas',
  DataModul in '..\..\SOURCE\DataModul.pas' {dmMain: TDataModule},
  dbTest in '..\SOURCE\dbTest.pas',
  ChoicePeriod in '..\..\SOURCE\COMPONENT\ChoicePeriod.pas' {PeriodChoiceForm},
  Defaults in '..\..\SOURCE\COMPONENT\Defaults.pas',
  UnilWin in '..\..\SOURCE\UnilWin.pas',
  MessagesUnit in '..\..\SOURCE\MessagesUnit.pas' {MessagesForm},
  SimpleGauge in '..\..\SOURCE\SimpleGauge.pas' {SimpleGaugeForm},
  ClientBankLoad in '..\..\SOURCE\COMPONENT\ClientBankLoad.pas',
  Document in '..\..\SOURCE\COMPONENT\Document.pas',
  Log in '..\..\SOURCE\Log.pas',
  ExternalData in '..\..\SOURCE\COMPONENT\ExternalData.pas',
  ExternalSave in '..\..\SOURCE\COMPONENT\ExternalSave.pas',
  VKDBFDataSet in '..\..\SOURCE\DBF\VKDBFDataSet.pas',
  VKDBFPrx in '..\..\SOURCE\DBF\VKDBFPrx.pas',
  VKDBFUtil in '..\..\SOURCE\DBF\VKDBFUtil.pas',
  VKDBFMemMgr in '..\..\SOURCE\DBF\VKDBFMemMgr.pas',
  VKDBFCrypt in '..\..\SOURCE\DBF\VKDBFCrypt.pas',
  VKDBFGostCrypt in '..\..\SOURCE\DBF\VKDBFGostCrypt.pas',
  VKDBFCDX in '..\..\SOURCE\DBF\VKDBFCDX.pas',
  VKDBFIndex in '..\..\SOURCE\DBF\VKDBFIndex.pas',
  VKDBFSorters in '..\..\SOURCE\DBF\VKDBFSorters.pas',
  VKDBFCollate in '..\..\SOURCE\DBF\VKDBFCollate.pas',
  VKDBFParser in '..\..\SOURCE\DBF\VKDBFParser.pas',
  VKDBFNTX in '..\..\SOURCE\DBF\VKDBFNTX.pas',
  VKDBFSortedList in '..\..\SOURCE\DBF\VKDBFSortedList.pas',
  ObjectTest in '..\SOURCEBoat\Objects\ObjectTest.pas',
  cxGridAddOn in '..\..\SOURCE\DevAddOn\cxGridAddOn.pas',
  MeDOC in '..\..\SOURCE\MeDOC\MeDOC.pas',
  MeDocXML in '..\..\SOURCE\MeDOC\MeDocXML.pas',
  Measure in '..\..\FormsBoat\Guides\Measure.pas' {MeasureForm: TParentForm},
  MeasureEdit in '..\..\FormsBoat\Guides\MeasureEdit.pas' {MeasureEditForm: TParentForm},
  Brand in '..\..\FormsBoat\Guides\Brand.pas' {BrandForm: TParentForm},
  BrandEdit in '..\..\FormsBoat\Guides\BrandEdit.pas' {BrandEditForm: TParentForm},
  GoodsSizeEdit in '..\..\FormsBoat\Guides\GoodsSizeEdit.pas' {GoodsSizeEditForm: TParentForm},
  GoodsGroup in '..\..\FormsBoat\Guides\GoodsGroup.pas' {GoodsGroupForm: TParentForm},
  GoodsGroupEdit in '..\..\FormsBoat\Guides\GoodsGroupEdit.pas' {GoodsGroupEditForm: TParentForm},
  Cash in '..\..\FormsBoat\Guides\Cash.pas' {CashForm: TParentForm},
  CashEdit in '..\..\FormsBoat\Guides\CashEdit.pas' {CashEditForm: TParentForm},
  Currency in '..\..\FormsBoat\Guides\Currency.pas' {CurrencyForm: TParentForm},
  CurrencyEdit in '..\..\FormsBoat\Guides\CurrencyEdit.pas' {CurrencyEditForm: TParentForm},
  Member in '..\..\FormsBoat\Guides\Member.pas' {MemberForm: TParentForm},
  MemberEdit in '..\..\FormsBoat\Guides\MemberEdit.pas' {MemberEditForm: TParentForm},
  Partner in '..\..\FormsBoat\Guides\Partner.pas' {PartnerForm: TParentForm},
  PartnerEdit in '..\..\FormsBoat\Guides\PartnerEdit.pas' {PartnerEditForm: TParentForm},
  Units in '..\..\FormsBoat\Guides\Units.pas' {UnitsForm: TParentForm},
  UnitEdit in '..\..\FormsBoat\Guides\UnitEdit.pas' {UnitsEditForm: TParentForm},
  Unit_Object in '..\..\FormsBoat\Guides\Unit_Object.pas' {UnitsEditForm: TParentForm},
  City in '..\..\FormsBoat\Guides\City.pas' {CityForm: TParentForm},
  CityEdit in '..\..\FormsBoat\Guides\CityEdit.pas' {CityEditForm: TParentForm},
  Client in '..\..\FormsBoat\Guides\Client.pas' {ClientForm: TParentForm},
  ClientEdit in '..\..\FormsBoat\Guides\ClientEdit.pas' {ClientEditForm: TParentForm},
  Goods in '..\..\FormsBoat\Guides\Goods.pas' {GoodsForm: TParentForm},
  GoodsEdit in '..\..\FormsBoat\Guides\GoodsEdit.pas' {GoodsEditForm: TParentForm},
  GoodsTree in '..\..\FormsBoat\Guides\GoodsTree.pas' {GoodsTreeForm: TParentForm},
  Position in '..\..\FormsBoat\Guides\Position.pas' {PositionForm: TParentForm},
  PositionEdit in '..\..\FormsBoat\Guides\PositionEdit.pas' {PositionEditForm: TParentForm},
  Personal in '..\..\FormsBoat\Guides\Personal.pas' {PersonalForm: TParentForm},
  PersonalEdit in '..\..\FormsBoat\Guides\PersonalEdit.pas' {PersonalEditForm: TParentForm},
  ImportExportLinkType in '..\..\Forms\Kind\ImportExportLinkType.pas' {ImportExportLinkTypeForm: TParentForm},
  AncestorBase in '..\..\Forms\Ancestor\AncestorBase.pas' {AncestorBaseForm: TParentForm},
  AncestorData in '..\..\Forms\Ancestor\AncestorData.pas' {AncestorDataForm: TParentForm},
  AncestorDBGrid in '..\..\Forms\Ancestor\AncestorDBGrid.pas' {AncestorDBGridForm: TParentForm},
  AncestorDialog in '..\..\Forms\Ancestor\AncestorDialog.pas' {AncestorDialogForm: TParentForm},
  AncestorDocument in '..\..\Forms\Ancestor\AncestorDocument.pas' {AncestorDocumentForm: TParentForm},
  AncestorDocumentMC in '..\..\Forms\Ancestor\AncestorDocumentMC.pas' {AncestorDocumentMCForm: TParentForm},
  AncestorEditDialog in '..\..\Forms\Ancestor\AncestorEditDialog.pas' {AncestorEditDialogForm: TParentForm},
  AncestorEnum in '..\..\Forms\Ancestor\AncestorEnum.pas' {AncestorEnumForm: TParentForm},
  AncestorGuides in '..\..\Forms\Ancestor\AncestorGuides.pas' {AncestorGuidesForm: TParentForm},
  AncestorJournal in '..\..\Forms\Ancestor\AncestorJournal.pas' {AncestorJournalForm: TParentForm},
  AboutBoxUnit in '..\..\SOURCE\AboutBoxUnit.pas' {AboutBox},
  UpdaterTest in '..\SOURCE\Component\UpdaterTest.pas',
  dbObjectTest in '..\SOURCE\dbObjectTest.pas',
  User in '..\..\FormsBoat\Guides\User.pas' {UserForm: TParentForm},
  UserEdit in '..\..\FormsBoat\Guides\UserEdit.pas' {UserEditForm: TParentForm},
  RoleTest in '..\SOURCEBoat\Objects\All\RoleTest.pas',
  UserTest in '..\SOURCEBoat\Objects\All\UserTest.pas',
  ParentFormTest in '..\SOURCE\Form\ParentFormTest.pas' {TestForm: TParentForm},
  Objects in '..\..\FormsBoat\Guides\Objects.pas' {ObjectForm: TParentForm},
  ObjectDesc in '..\..\FormsBoat\Guides\ObjectDesc.pas' {ObjectDescForm: TParentForm},
  ActionTest in '..\SOURCEBoat\Objects\All\ActionTest.pas',
  AncestorMain in '..\..\Forms\Ancestor\AncestorMain.pas' {AncestorMainForm},
  Protocol in '..\..\FormsBoat\Guides\Protocol.pas' {ProtocolForm: TParentForm},
  Account in '..\..\FormsBoat\Guides\Account.pas' {AccountForm: TParentForm},
  Account_Object in '..\..\FormsBoat\Guides\Account_Object.pas' {Account_ObjectForm: TParentForm},
  AccountDirection in '..\..\FormsBoat\Guides\AccountDirection.pas' {AccountDirectionForm: TParentForm},
  AccountDirection_Object in '..\..\FormsBoat\Guides\AccountDirection_Object.pas' {AccountDirection_ObjectForm: TParentForm},
  AccountDirectionEdit in '..\..\FormsBoat\Guides\AccountDirectionEdit.pas' {AccountDirectionEditForm: TParentForm},
  AccountEdit in '..\..\FormsBoat\Guides\AccountEdit.pas' {AccountEditForm: TParentForm},
  AccountGroup in '..\..\FormsBoat\Guides\AccountGroup.pas' {AccountGroupForm: TParentForm},
  AccountGroup_Object in '..\..\FormsBoat\Guides\AccountGroup_Object.pas' {AccountGroup_ObjectForm: TParentForm},
  AccountGroupEdit in '..\..\FormsBoat\Guides\AccountGroupEdit.pas' {AccountGroupEditForm: TParentForm},
  AccountDirectionTest in '..\SOURCEBoat\Objects\All\AccountDirectionTest.pas',
  AccountGroupTest in '..\SOURCEBoat\Objects\All\AccountGroupTest.pas',
  AccountTest in '..\SOURCEBoat\Objects\All\AccountTest.pas',
  AncestorReport in '..\..\Forms\Ancestor\AncestorReport.pas' {AncestorReportForm: TParentForm},
  Vcl.Dialogs,
  dsdDataSetDataLink in '..\..\SOURCE\COMPONENT\dsdDataSetDataLink.pas',
  dsdException in '..\..\SOURCE\dsdException.pas',
  EDI in '..\..\SOURCE\EDI\EDI.pas',
  ComDocXML in '..\..\SOURCE\EDI\ComDocXML.pas',
  OrderXML in '..\..\SOURCE\EDI\OrderXML.pas',
  DeclarXML in '..\..\SOURCE\EDI\DeclarXML.pas',
  DesadvXML in '..\..\SOURCE\EDI\DesadvXML.pas',
  InvoiceXML in '..\..\SOURCE\EDI\InvoiceXML.pas',
  OrdrspXML in '..\..\SOURCE\EDI\OrdrspXML.pas',
  RecadvXML in '..\..\SOURCE\EDI\RecadvXML.pas',
  StatusXML in '..\..\SOURCE\EDI\StatusXML.pas',
  dsdInternetAction in '..\..\SOURCE\COMPONENT\dsdInternetAction.pas',
  LookAndFillSettings in '..\..\SOURCE\LookAndFillSettings.pas' {LookAndFillSettingsForm},
  dsdXMLTransform in '..\..\SOURCE\COMPONENT\dsdXMLTransform.pas',
  IncomeJournal in '..\..\FormsBoat\Document\IncomeJournal.pas' {IncomeJournalForm: TParentForm},
  Movement_PeriodDialog in '..\..\FormsBoat\Document\Movement_PeriodDialog.pas' {Movement_PeriodDialogForm: TParentForm},
  ReturnOutJournal in '..\..\FormsBoat\Document\ReturnOutJournal.pas' {ReturnOutJournalForm: TParentForm},
  ReturnOut in '..\..\FormsBoat\Document\ReturnOut.pas' {ReturnOutForm: TParentForm},
  SendJournal in '..\..\FormsBoat\Document\SendJournal.pas' {SendJournalForm: TParentForm},
  Send in '..\..\FormsBoat\Document\Send.pas' {SendForm: TParentForm},
  LossJournal in '..\..\FormsBoat\Document\LossJournal.pas' {LossJournalForm: TParentForm},
  Loss in '..\..\FormsBoat\Document\Loss.pas' {LossForm: TParentForm},
  CurrencyMovement in '..\..\FormsBoat\Document\CurrencyMovement.pas' {CurrencyMovementForm: TParentForm},
  PriceList in '..\..\FormsBoat\Guides\PriceList.pas' {PriceListForm: TParentForm},
  PriceListEdit in '..\..\FormsBoat\Guides\PriceListEdit.pas' {PriceListEditForm: TParentForm},
  PriceListItem in '..\..\FormsBoat\Guides\PriceListItem.pas' {PriceListItemForm: TParentForm},
  PriceListTaxDialog in '..\..\FormsBoat\Guides\PriceListTaxDialog.pas' {PriceListTaxDialogForm: TParentForm},
  Inventory in '..\..\FormsBoat\Document\Inventory.pas' {InventoryForm: TParentForm},
  InventoryJournal in '..\..\FormsBoat\Document\InventoryJournal.pas' {InventoryJournalForm: TParentForm},
  Role in '..\..\FormsBoat\Guides\Role.pas' {RoleForm: TParentForm},
  RoleEdit in '..\..\FormsBoat\Guides\RoleEdit.pas' {RoleEditForm: TParentForm},
  Action in '..\..\Forms\Action.pas' {ActionForm: TParentForm},
  Bank in '..\..\FormsBoat\Guides\Bank.pas' {BankForm: TParentForm},
  BankEdit in '..\..\FormsBoat\Guides\BankEdit.pas' {BankEditForm: TParentForm},
  SaleJournal in '..\..\FormsBoat\Document\SaleJournal.pas' {SaleJournalForm: TParentForm},
  Sale in '..\..\FormsBoat\Document\Sale.pas' {SaleForm: TParentForm},
  BankAccount in '..\..\FormsBoat\Guides\BankAccount.pas' {BankAccountForm: TParentForm},
  BankAccountEdit in '..\..\FormsBoat\Guides\BankAccountEdit.pas' {BankAccountEditForm: TParentForm},
  InfoMoneyGroup in '..\..\FormsBoat\Guides\InfoMoneyGroup.pas' {InfoMoneyGroupForm: TParentForm},
  InfoMoneyGroup_Object in '..\..\FormsBoat\Guides\InfoMoneyGroup_Object.pas' {InfoMoneyGroup_ObjectForm: TParentForm},
  InfoMoneyGroupEdit in '..\..\FormsBoat\Guides\InfoMoneyGroupEdit.pas' {InfoMoneyGroupEditForm: TParentForm},
  InfoMoneyDestination in '..\..\FormsBoat\Guides\InfoMoneyDestination.pas' {InfoMoneyDestinationForm: TParentForm},
  InfoMoneyDestination_Object in '..\..\FormsBoat\Guides\InfoMoneyDestination_Object.pas' {InfoMoneyDestination_ObjectForm: TParentForm},
  InfoMoneyDestinationEdit in '..\..\FormsBoat\Guides\InfoMoneyDestinationEdit.pas' {InfoMoneyDestinationEditForm: TParentForm},
  ReturnInJournal in '..\..\FormsBoat\Document\ReturnInJournal.pas' {ReturnInJournalForm: TParentForm},
  ReturnIn in '..\..\FormsBoat\Document\ReturnIn.pas' {ReturnInForm: TParentForm},
  ReturnInItemEdit in '..\..\FormsBoat\Document\ReturnInItemEdit.pas' {ReturnInItemEditForm: TParentForm},
  CurrencyJournal in '..\..\FormsBoat\Document\CurrencyJournal.pas' {CurrencyJournalForm: TParentForm},
  Report_Balance in '..\..\FormsBoat\Report\Report_Balance.pas' {Report_BalanceForm: TParentForm},
  Report_BalanceDialog in '..\..\FormsBoat\Report\Report_BalanceDialog.pas' {Report_BalanceDialogForm: TParentForm},
  InfoMoney in '..\..\FormsBoat\Guides\InfoMoney.pas' {InfoMoneyForm: TParentForm},
  InfoMoney_Object in '..\..\FormsBoat\Guides\InfoMoney_Object.pas' {InfoMoney_ObjectForm: TParentForm},
  InfoMoneyEdit in '..\..\FormsBoat\Guides\InfoMoneyEdit.pas' {InfoMoneyEditForm: TParentForm},
  FormsUnit in '..\..\FormsBoat\Guides\FormsUnit.pas' {FormsUnit: TParentForm},
  ProfitLoss in '..\..\FormsBoat\Guides\ProfitLoss.pas' {ProfitLoss: TParentForm},
  ProfitLoss_Object in '..\..\FormsBoat\Guides\ProfitLoss_Object.pas' {ProfitLoss_Object: TParentForm},
  ProfitLossEdit in '..\..\FormsBoat\Guides\ProfitLossEdit.pas' {ProfitLossEdit: TParentForm},
  ProfitLossDirection in '..\..\FormsBoat\Guides\ProfitLossDirection.pas' {ProfitLossDirection: TParentForm},
  ProfitLossDirection_Object in '..\..\FormsBoat\Guides\ProfitLossDirection_Object.pas' {ProfitLossDirection_Object: TParentForm},
  ProfitLossDirectionEdit in '..\..\FormsBoat\Guides\ProfitLossDirectionEdit.pas' {ProfitLossDirectionEdit: TParentForm},
  ProfitLossGroup in '..\..\FormsBoat\Guides\ProfitLossGroup.pas' {ProfitLossGroup: TParentForm},
  ProfitLossGroup_Object in '..\..\FormsBoat\Guides\ProfitLossGroup_Object.pas' {ProfitLossGroup_Object: TParentForm},
  ProfitLossGroupEdit in '..\..\FormsBoat\Guides\ProfitLossGroupEdit.pas' {ProfitLossGroupEdit: TParentForm},
  UserProtocol in '..\..\FormsBoat\Guides\UserProtocol.pas' {UserProtocol: TParentForm},
  MovementItemProtocol in '..\..\FormsBoat\Document\MovementItemProtocol.pas' {MovementItemProtocolForm: TParentForm},
  MovementProtocol in '..\..\FormsBoat\Document\MovementProtocol.pas' {MovementProtocolForm: TParentForm},
  Report_ProfitLoss in '..\..\FormsBoat\Report\Report_ProfitLoss.pas' {Report_ProfitLossForm: TParentForm},
  Report_ProfitLossDialog in '..\..\FormsBoat\Report\Report_ProfitLossDialog.pas' {Report_ProfitLossDialogForm: TParentForm},
  MovementItemContainer in '..\..\FormsBoat\Document\MovementItemContainer.pas' {MovementItemContainerForm: TParentForm},
  IFIN_J1201009 in '..\..\SOURCE\MeDOC\IFIN_J1201009.pas',
  IFIN_J1201209 in '..\..\SOURCE\MeDOC\IFIN_J1201209.pas',
  CommonContainerProcedureTest in '..\SOURCEBoat\Container\CommonContainerProcedureTest.pas',
  Unit_Dialog in '..\..\FormsBoat\Guides\Unit_Dialog.pas' {Unit_DialogForm: TParentForm},
  PriceListItemDialog in '..\..\FormsBoat\Guides\PriceListItemDialog.pas' {PriceListItemDialogForm: TParentForm},
  InventoryItemEdit in '..\..\FormsBoat\Document\InventoryItemEdit.pas' {InventoryItemEditForm: TParentForm},
  Income in '..\..\FormsBoat\Document\Income.pas' {IncomeForm: TParentForm},
  Process in '..\..\FormsBoat\Guides\Process.pas' {ProcessForm: TParentForm},
  MovementDescForms in '..\..\FormsBoat\System\MovementDescForms.pas' {MovementDescDataForm: TParentForm},
  CashJournal in '..\..\FormsBoat\Document\CashJournal.pas' {CashJournalForm: TParentForm},
  CashOperation in '..\..\FormsBoat\Document\CashOperation.pas' {CashOperationForm: TParentForm},
  dsdPivotGrid in '..\..\SOURCE\COMPONENT\dsdPivotGrid.pas',
  Medoc_J1201010 in '..\..\SOURCE\MeDOC\Medoc_J1201010.pas',
  Medoc_J1201210 in '..\..\SOURCE\MeDOC\Medoc_J1201210.pas',
  dsdExportToXLSAction in '..\..\SOURCE\COMPONENT\dsdExportToXLSAction.pas',
  dsdExportToXMLAction in '..\..\SOURCE\COMPONENT\dsdExportToXMLAction.pas',
  Report_ProfitLossPeriod in '..\..\FormsBoat\Report\Report_ProfitLossPeriod.pas' {Report_ProfitLossPeriodForm: TParentForm},
  ProfitLossDemo in '..\..\FormsBoat\Guides\ProfitLossDemo.pas' {ProfitLossDemoForm: TParentForm},
  ImportType in '..\..\FormsBoat\Import\ImportType.pas' {ImportTypeForm: TParentForm},
  ImportSettings in '..\..\FormsBoat\Import\ImportSettings.pas' {ImportSettingsForm: TParentForm},
  ExternalLoad in '..\..\SOURCE\COMPONENT\ExternalLoad.pas',
  PUSHMessage in '..\..\SOURCE\COMPONENT\PUSHMessage.pas' {PUSHMessageForm},
  DesadvFozzXML in '..\..\SOURCE\EDI\DesadvFozzXML.pas',
  IftminFozzXML in '..\..\SOURCE\EDI\IftminFozzXML.pas',
  OrderSpFozzXML in '..\..\SOURCE\EDI\OrderSpFozzXML.pas',
  MainForm in '..\..\FormsBoat\MainForm.pas' {MainForm},
  dbProcedureBoatTest in '..\SOURCEBoat\dbProcedureBoatTest.pas',
  LoadBoatFormTest in '..\SOURCEBoat\LoadBoatFormTest.pas',
  LoadBoatReportTest in '..\SOURCEBoat\LoadBoatReportTest.pas',
  IncomeItemEdit in '..\..\FormsBoat\Document\IncomeItemEdit.pas' {IncomeItemEditForm: TParentForm},
  SaleItemEdit in '..\..\FormsBoat\Document\SaleItemEdit.pas' {SaleItemEditForm: TParentForm};

{$R *.res}
{$R DevExpressRus.res}

begin
  ConnectionPath := '..\INIT\Boat_init.php';
  EnumPath := '..\DATABASE\Boat\METADATA\Enum\';
  CreateStructurePath := '..\DATABASE\Boat\STRUCTURE\';
  LocalViewPath := '..\DATABASE\Boat\View\';
  LocalProcedurePath := '..\DATABASE\Boat\PROCEDURE\';
  LocalProcessPath := '..\DATABASE\Boat\PROCESS\';

  dsdProject := prBoat;

  if FindCmdLineSwitch('realProjectBoat', true)
  then gc_AdminPassword := 'qsxqsxw1'
  else gc_AdminPassword := 'Админ';

  gc_ProgramName := 'ProjectBoat.exe';

  Application.Initialize;
  gc_isSetDefault := true;
  Application.CreateForm(TdmMain, dmMain);
  Application.Run;
  DUnitTestRunner.RunRegisteredTests;
end.
