program ProjectTest;
{

  Delphi DUnit Test Project
  -------------------------
  This project contains the DUnit test framework and the GUI/Console test runners.
  Add "CONSOLE_TESTRUNNER" to the conditional defines entry in the project options
  to use the console test runner.  Otherwise the GUI test runner will be used by
  default.

}

{$IFDEF CONSOLE_TESTRUNNER}
{$APPTYPE CONSOLE}
{$ENDIF}



uses
  DUnitTestRunner,
  VKDBFDataSet in '..\..\SOURCE\DBF\VKDBFDataSet.pas',
  VKDBFPrx in '..\..\SOURCE\DBF\VKDBFPrx.pas',
  VKDBFUtil in '..\..\SOURCE\DBF\VKDBFUtil.pas',
  VKDBFMemMgr in '..\..\SOURCE\DBF\VKDBFMemMgr.pas',
  VKDBFCrypt in '..\..\SOURCE\DBF\VKDBFCrypt.pas',
  VKDBFGostCrypt in '..\..\SOURCE\DBF\VKDBFGostCrypt.pas',
  VKDBFCDX in '..\..\SOURCE\DBF\VKDBFCDX.pas',
  VKDBFIndex in '..\..\SOURCE\DBF\VKDBFIndex.pas',
  VKDBFSorters in '..\..\SOURCE\DBF\VKDBFSorters.pas',
  VKDBFCollate in '..\..\SOURCE\DBF\VKDBFCollate.pas',
  VKDBFParser in '..\..\SOURCE\DBF\VKDBFParser.pas',
  VKDBFNTX in '..\..\SOURCE\DBF\VKDBFNTX.pas',
  VKDBFSortedList in '..\..\SOURCE\DBF\VKDBFSortedList.pas',
  dbCreateStructureTest in '..\SOURCE\STRUCTURE\dbCreateStructureTest.pas',
  dbMetadataTest in '..\SOURCE\Metadata\dbMetadataTest.pas',
  dbCreateViewTest in '..\SOURCE\View\dbCreateViewTest.pas',
  dbProcedureTest in '..\SOURCE\dbProcedureTest.pas',
  dbEnumTest in '..\SOURCE\dbEnumTest.pas',
  AuthenticationTest in '..\SOURCE\AuthenticationTest.pas',
  CommonObjectProcedureTest in '..\SOURCE\Objects\CommonObjectProcedureTest.pas',
  dbObjectTest in '..\SOURCE\dbObjectTest.pas',
  CommonMovementProcedureTest in '..\SOURCE\Movement\CommonMovementProcedureTest.pas',
  dbMovementTest in '..\SOURCE\Movement\dbMovementTest.pas',
  LoadFormTest in '..\SOURCE\LoadFormTest.pas',
  Forms,
  CommonContainerProcedureTest in '..\SOURCE\Container\CommonContainerProcedureTest.pas',
  CommonMovementItemProcedureTest in '..\SOURCE\MovementItem\CommonMovementItemProcedureTest.pas',
  CommonMovementItemContainerProcedureTest in '..\SOURCE\MovementItemContainer\CommonMovementItemContainerProcedureTest.pas',
  CommonObjectHistoryProcedureTest in '..\SOURCE\ObjectHistory\CommonObjectHistoryProcedureTest.pas',
  CommonProtocolProcedureTest in '..\SOURCE\Protocol\CommonProtocolProcedureTest.pas',
  CommonFunctionTest in '..\SOURCE\Function\CommonFunctionTest.pas',
  CommonReportsProcedureTest in '..\SOURCE\Reports\CommonReportsProcedureTest.pas',
  DataModul in '..\..\SOURCE\DataModul.pas' {dmMain: TDataModule},
  Authentication in '..\..\SOURCE\Authentication.pas',
  Storage in '..\..\SOURCE\Storage.pas',
  zLibUtil in '..\SOURCE\zLibUtil.pas',
  UtilConst in '..\..\SOURCE\UtilConst.pas',
  UtilConvert in '..\..\SOURCE\UtilConvert.pas',
  CommonData in '..\..\SOURCE\CommonData.pas',
  dsdGuides in '..\..\SOURCE\COMPONENT\dsdGuides.pas',
  FormStorage in '..\..\SOURCE\FormStorage.pas',
  GoodsKindEdit in '..\..\Forms\Guides\GoodsKindEdit.pas' {GoodsKindEditForm},
  GoodsPropertyEdit in '..\..\Forms\Guides\GoodsPropertyEdit.pas' {GoodsPropertyEditForm},
  CurrencyEdit in '..\..\Forms\Guides\CurrencyEdit.pas' {CurencyEditForm},
  GoodsGroupEdit in '..\..\Forms\Guides\GoodsGroupEdit.pas' {GoodsGroupEditForm},
  PriceListEdit in '..\..\Forms\Guides\PriceListEdit.pas' {PriceListEditForm},
  PriceList_Object in '..\..\Forms\Guides\PriceList_Object.pas' {PriceList_ObjectForm},
  ParentForm in '..\..\SOURCE\ParentForm.pas' {ParentForm},
  dsdAction in '..\..\SOURCE\COMPONENT\dsdAction.pas',
  GoodsKind_Object in '..\..\Forms\Guides\GoodsKind_Object.pas' {GoodsKind_ObjectForm},
  Bank in '..\..\Forms\Bank.pas' {CurrencyForm},
  GoodsGroup_Object in '..\..\Forms\Guides\GoodsGroup_Object.pas' {GoodsGroup_ObjectForm},
  GoodsKindWeighingTree in '..\..\Forms\Guides\GoodsKindWeighingTree.pas' {GoodsKindWeighingTreeForm},
  ToolsWeighingEdit in '..\..\Forms\Guides\ToolsWeighingEdit.pas' {ToolsWeighingEditForm},
  BoxEdit in '..\..\Forms\BoxEdit.pas' {BoxEditForm},
  Status in '..\..\Forms\Status.pas' {StatusForm},
  Currency in '..\..\Forms\Guides\Currency.pas' {CurrencyForm},
  BankEdit in '..\..\Forms\BankEdit.pas' {BankEditForm},
  PriceListGoodsItem in '..\..\Forms\Guides\PriceListGoodsItem.pas' {PriceListGoodsItemForm},
  ContractKindEdit in '..\..\Forms\Guides\ContractKindEdit.pas' {ContractKindEditForm},
  ContractKind in '..\..\Forms\Guides\ContractKind.pas' {ContractKindForm},
  GoodsPropertyValueEdit in '..\..\Forms\Guides\GoodsPropertyValueEdit.pas' {GoodsPropertyValueEditForm},
  BankAccountContract in '..\..\Forms\Guides\BankAccountContract.pas' {BankAccountContractForm},
  BankAccountContractEdit in '..\..\Forms\Guides\BankAccountContractEdit.pas' {BankAccountContractEditForm},
  BusinessEdit in '..\..\Forms\Guides\BusinessEdit.pas' {BusinessEditForm},
  Business_Object in '..\..\Forms\Guides\Business_Object.pas' {Business_ObjectForm},
  Juridical_Object in '..\..\Forms\Guides\Juridical_Object.pas' {Juridical_ObjectForm},
  dsdDB in '..\..\SOURCE\COMPONENT\dsdDB.pas',
  ToolsWeighingTree in '..\..\Forms\Guides\ToolsWeighingTree.pas' {ToolsWeighingTreeForm},
  dbMovementItemTest in '..\SOURCE\dbMovementItemTest.pas',
  IncomePartner in '..\..\Forms\Document\IncomePartner.pas' {IncomePartnerForm},
  IncomePartnerJournal in '..\..\Forms\Document\IncomePartnerJournal.pas' {IncomePartnerJournalForm},
  dsdAddOn in '..\..\SOURCE\COMPONENT\dsdAddOn.pas',
  dbMovementCompleteTest in '..\SOURCE\dbMovementCompleteTest.pas',
  Report_Balance in '..\..\Forms\Report\Report_Balance.pas' {Report_BalanceForm},
  LoadReportTest in '..\SOURCE\LoadReportTest.pas',
  PriceListItemTest in '..\SOURCE\ObjectHistory\All\PriceListItemTest.pas',
  InfoMoneyGroup_ObjectDesc in '..\..\Forms\Guides\InfoMoneyGroup_ObjectDesc.pas' {InfoMoneyGroup_ObjectDescForm},
  InfoMoneyGroupEdit in '..\..\Forms\Guides\InfoMoneyGroupEdit.pas' {InfoMoneyGroupEditForm},
  InfoMoneyDestination_ObjectDesc in '..\..\Forms\Guides\InfoMoneyDestination_ObjectDesc.pas' {InfoMoneyDestination_ObjectDescForm},
  InfoMoneyDestinationEdit in '..\..\Forms\Guides\InfoMoneyDestinationEdit.pas' {InfoMoneyDestinationEditForm},
  InfoMoney_ObjectDesc in '..\..\Forms\Guides\InfoMoney_ObjectDesc.pas' {InfoMoney_ObjectDescForm},
  InfoMoneyEdit in '..\..\Forms\Guides\InfoMoneyEdit.pas' {InfoMoneyEditForm},
  AccountGroup_ObjectDesc in '..\..\Forms\Guides\AccountGroup_ObjectDesc.pas' {AccountGroup_ObjectDescForm},
  AccountGroupEdit in '..\..\Forms\Guides\AccountGroupEdit.pas' {AccountGroupEditForm},
  AccountDirection_ObjectDesc in '..\..\Forms\Guides\AccountDirection_ObjectDesc.pas' {AccountDirection_ObjectDescForm},
  AccountDirectionEdit in '..\..\Forms\Guides\AccountDirectionEdit.pas' {AccountDirectionEditForm},
  ProfitLossGroup_Object in '..\..\Forms\Guides\ProfitLossGroup_Object.pas' {ProfitLossGroup_ObjectForm},
  ProfitLossGroupEdit in '..\..\Forms\Guides\ProfitLossGroupEdit.pas' {ProfitLossGroupEditForm},
  Account_ObjectDesc in '..\..\Forms\Guides\Account_ObjectDesc.pas' {Account_ObjectDescForm},
  AccountEdit in '..\..\Forms\Guides\AccountEdit.pas' {AccountEditForm},
  ProfitLoss_Object in '..\..\Forms\Guides\ProfitLoss_Object.pas' {ProfitLoss_ObjectForm},
  ProfitLossDirectionEdit in '..\..\Forms\Guides\ProfitLossDirectionEdit.pas' {ProfitLossDirectionEditForm},
  ProfitLossEdit in '..\..\Forms\Guides\ProfitLossEdit.pas' {ProfitLossEditForm},
  dbTest in '..\SOURCE\dbTest.pas',
  TradeMark in '..\..\Forms\TradeMark.pas' {TradeMarkForm},
  TradeMarkEdit in '..\..\Forms\TradeMarkEdit.pas' {TradeMarkEditForm},
  Route_Object in '..\..\Forms\Guides\Route_Object.pas' {Route_ObjectForm},
  RouteEdit in '..\..\Forms\Guides\RouteEdit.pas' {RouteEditForm},
  RouteSorting_Object in '..\..\Forms\Guides\RouteSorting_Object.pas' {RouteSorting_ObjectForm},
  RouteSortingEdit in '..\..\Forms\Guides\RouteSortingEdit.pas' {RouteSortingEditForm},
  Member_ObjectDesc in '..\..\Forms\Guides\Member_ObjectDesc.pas' {Member_ObjectDescForm},
  MemberEdit in '..\..\Forms\Guides\MemberEdit.pas' {MemberEditForm},
  CarModel in '..\..\Forms\CarModel.pas' {CarModelForm},
  CarModelEdit in '..\..\Forms\CarModelEdit.pas' {CarModelEditForm},
  Car in '..\..\Forms\Guides\Car.pas' {CarForm},
  CarEdit in '..\..\Forms\Guides\CarEdit.pas' {CarEditForm},
  Position in '..\..\Forms\Guides\Position.pas' {PositionForm},
  PositionEdit in '..\..\Forms\Guides\PositionEdit.pas' {PositionEditForm},
  AssetGroupEdit in '..\..\Forms\Guides\AssetGroupEdit.pas' {AssetGroupEditForm: TParentForm},
  Personal_Object in '..\..\Forms\Guides\Personal_Object.pas' {Personal_ObjectForm},
  PersonalEdit in '..\..\Forms\Guides\PersonalEdit.pas' {PersonalEditForm},
  ProductionSeparateJournal in '..\..\Forms\Document\ProductionSeparateJournal.pas' {ProductionSeparateJournalForm},
  JuridicalTest in '..\SOURCE\Objects\All\JuridicalTest.pas',
  SendOnPrice_BranchJournal in '..\..\Forms\Document\SendOnPrice_BranchJournal.pas' {SendOnPrice_BranchJournalForm},
  SendOnPrice_Branch in '..\..\Forms\Document\SendOnPrice_Branch.pas' {SendOnPrice_BranchForm},
  LossJournal in '..\..\Forms\Document\LossJournal.pas' {LossJournalForm},
  Loss in '..\..\Forms\Document\Loss.pas' {LossForm},
  ProductionUnionJournal in '..\..\Forms\Document\ProductionUnionJournal.pas' {ProductionUnionJournalForm},
  Report_ProfitLoss in '..\..\Forms\Report\Report_ProfitLoss.pas' {Report_ProfitLossForm},
  Report_HistoryCost in '..\..\Forms\Report\Report_HistoryCost.pas' {Report_HistoryCostForm},
  ProductionUnionTechJournal in '..\..\Forms\Document\ProductionUnionTechJournal.pas' {ProductionUnionTechJournalForm},
  ContractConditionValue in '..\..\Forms\Guides\ContractConditionValue.pas' {ContractConditionValueForm},
  ContractEdit in '..\..\Forms\Guides\ContractEdit.pas' {ContractEditForm},
  Box in '..\..\Forms\Box.pas' {BoxForm},
  PriceListItem in '..\..\Forms\Guides\PriceListItem.pas' {PriceListItemForm},
  ComponentActionTest in '..\SOURCE\Component\ComponentActionTest.pas',
  ComponentDBTest in '..\SOURCE\Component\ComponentDBTest.pas',
  CashOperationTest in '..\SOURCE\Movement\All\CashOperationTest.pas',
  CommonObjectCostProcedureTest in '..\SOURCE\ObjectCost\CommonObjectCostProcedureTest.pas',
  BankStatementTest in '..\SOURCE\Movement\All\BankStatementTest.pas',
  BankAccountMovementTest in '..\SOURCE\Movement\All\BankAccountMovementTest.pas',
  ProfitLossServiceTest in '..\SOURCE\Movement\All\ProfitLossServiceTest.pas',
  PersonalServiceTest in '..\SOURCE\Movement\All\PersonalServiceTest.pas',
  PersonalReportTest in '..\SOURCE\Movement\All\PersonalReportTest.pas',
  BankStatementItemTest in '..\SOURCE\Movement\All\BankStatementItemTest.pas',
  AccountTest in '..\SOURCE\Objects\All\AccountTest.pas',
  CashTest in '..\SOURCE\Objects\All\CashTest.pas',
  InfoMoneyTest in '..\SOURCE\Objects\All\InfoMoneyTest.pas',
  TransportServiceTest in '..\SOURCE\Movement\All\TransportServiceTest.pas',
  Unit_Object in '..\..\Forms\Guides\Unit_Object.pas' {Unit_ObjectForm},
  JuridicalTree in '..\..\Forms\Guides\JuridicalTree.pas' {JuridicalTreeForm},
  BankAccountTest in '..\SOURCE\Objects\All\BankAccountTest.pas',
  BusinessTest in '..\SOURCE\Objects\All\BusinessTest.pas',
  CommonMovementItemReportProcedureTest in '..\SOURCE\MovementItemReport\CommonMovementItemReportProcedureTest.pas',
  TradeMarkTest in '..\SOURCE\Objects\All\TradeMarkTest.pas',
  ChoicePeriod in '..\..\SOURCE\COMPONENT\ChoicePeriod.pas' {PeriodChoiceForm},
  Report_GoodsMI_SaleReturnInDialog in '..\..\Forms\Report\Report_GoodsMI_SaleReturnInDialog.pas' {Report_GoodsMI_SaleReturnInDialogForm},
  Report_MotionGoods in '..\..\Forms\Report\Report_MotionGoods.pas' {Report_MotionGoodsForm},
  ActionTest in '..\SOURCE\Objects\All\ActionTest.pas',
  Role in '..\..\Forms\Role.pas' {RoleForm},
  RoleEdit in '..\..\Forms\RoleEdit.pas' {RoleEditForm},
  Action in '..\..\Forms\Action.pas' {ActionForm},
  User in '..\..\Forms\User.pas' {UserForm},
  UserEdit in '..\..\Forms\UserEdit.pas' {UserEditForm},
  Process in '..\..\Forms\Kind\Process.pas' {ProcessForm},
  ComponentAddOnTest in '..\SOURCE\Component\ComponentAddOnTest.pas',
  DefaultsTest in '..\SOURCE\Defaults\DefaultsTest.pas',
  Transport in '..\..\Forms\Document\Transport.pas' {TransportForm},
  TransportJournal in '..\..\Forms\Document\TransportJournal.pas' {TransportJournalForm},
  FuelEdit in '..\..\Forms\FuelEdit.pas' {FuelEditForm},
  RateFuelKindEdit in '..\..\Forms\RateFuelKindEdit.pas' {RateFuelKindEditForm},
  RateFuelKind in '..\..\Forms\RateFuelKind.pas' {RateFuelKindForm},
  Fuel in '..\..\Forms\Fuel.pas' {FuelForm},
  RoleTest in '..\SOURCE\Objects\All\RoleTest.pas',
  Defaults in '..\..\SOURCE\COMPONENT\Defaults.pas',
  IncomeFuel in '..\..\Forms\Document\IncomeFuel.pas' {IncomeFuelForm},
  IncomeFuelJournal in '..\..\Forms\Document\IncomeFuelJournal.pas' {IncomeFuelJournalForm},
  Freight in '..\..\Forms\Freight.pas' {FreightForm},
  FreightEdit in '..\..\Forms\FreightEdit.pas' {FreightEditForm},
  RouteKind in '..\..\Forms\Guides\RouteKind.pas' {RouteKindForm},
  RouteKindEdit in '..\..\Forms\Guides\RouteKindEdit.pas' {RouteKindEditForm},
  RateFuel in '..\..\Forms\RateFuel.pas' {RateFuelForm},
  PersonalGroup in '..\..\Forms\Guides\PersonalGroup.pas' {PersonalGroupForm},
  PersonalGroupEdit in '..\..\Forms\Guides\PersonalGroupEdit.pas' {PersonalGroupEditForm},
  PersonalSendCash in '..\..\Forms\Document\PersonalSendCash.pas' {PersonalSendCashForm},
  PersonalSendCashJournal in '..\..\Forms\Document\PersonalSendCashJournal.pas' {PersonalSendCashJournalForm},
  SendDebtTest in '..\SOURCE\Movement\All\SendDebtTest.pas' {$R *.RES},
  SheetWorkTimeTest in '..\SOURCE\Movement\All\SheetWorkTimeTest.pas',
  Report_Fuel in '..\..\Forms\Report\Report_Fuel.pas' {Report_FuelForm},
  Report_Transport in '..\..\Forms\Report\Report_Transport.pas' {Report_TransportForm},
  CrossAddOnViewTestForm in '..\SOURCE\Component\CrossAddOnViewTestForm.pas' {CrossAddOnViewTest},
  Report_Account in '..\..\Forms\Report\Report_Account.pas' {Report_AccountForm},
  MessagesUnit in '..\..\SOURCE\MessagesUnit.pas' {MessagesForm},
  SourceFuel_Object in '..\..\Forms\Guides\SourceFuel_Object.pas' {SourceFuel_ObjectForm: TParentForm},
  CardFuel in '..\..\Forms\CardFuel.pas' {CardFuelForm},
  TicketFuel in '..\..\Forms\TicketFuel.pas' {TicketFuelForm},
  TicketFuelEdit in '..\..\Forms\TicketFuelEdit.pas' {TicketFuelEditForm},
  CardFuelEdit in '..\..\Forms\CardFuelEdit.pas' {CardFuelEditForm},
  SheetWorkTime in '..\..\Forms\Document\SheetWorkTime.pas' {SheetWorkTimeForm},
  SheetWorkTimeJournal in '..\..\Forms\Document\SheetWorkTimeJournal.pas' {SheetWorkTimeJournalForm},
  PositionLevel in '..\..\Forms\Guides\PositionLevel.pas' {PositionLevelForm},
  PositionLevelEdit in '..\..\Forms\Guides\PositionLevelEdit.pas' {PositionLevelEditForm},
  StaffListData in '..\..\Forms\StaffListData.pas' {StaffListDataForm},
  StaffListEdit in '..\..\Forms\StaffListEdit.pas' {StaffListEditForm},
  PersonalTest in '..\SOURCE\Objects\All\PersonalTest.pas',
  TaxCorrectiveMovementItemTest in '..\SOURCE\MovementItem\All\TaxCorrectiveMovementItemTest.pas',
  ModelService in '..\..\Forms\ModelService.pas' {ModelServiceForm},
  ModelServiceKind in '..\..\Forms\Kind\ModelServiceKind.pas' {NDSKindForm},
  UpdaterTest in '..\SOURCE\Component\UpdaterTest.pas',
  AboutBoxUnit in '..\..\SOURCE\AboutBoxUnit.pas' {AboutBox},
  UnilWin in '..\..\SOURCE\UnilWin.pas',
  ModelServiceEdit in '..\..\Forms\ModelServiceEdit.pas' {ModelServiceEditForm: TParentForm},
  MemberPlace_Object in '..\..\Forms\Guides\MemberPlace_Object.pas' {MemberPlace_ObjectForm: TParentForm},
  Report_TransportHoursWork in '..\..\Forms\Report\Report_TransportHoursWork.pas' {Report_TransportHoursWorkForm: TParentForm},
  StaffListChoice in '..\..\Forms\StaffListChoice.pas' {StaffListChoiceForm: TParentForm},
  StaffList in '..\..\Forms\StaffList.pas' {StaffListForm: TParentForm},
  StaffListSummKind in '..\..\Forms\Kind\StaffListSummKind.pas' {StaffListSummKindForm: TParentForm},
  DocumentTaxKind in '..\..\Forms\Kind\DocumentTaxKind.pas' {DocumentTaxKindForm: TParentForm},
  AncestorDialog in '..\..\Forms\Ancestor\AncestorDialog.pas' {AncestorDialogForm: TParentForm},
  AncestorEditDialog in '..\..\Forms\Ancestor\AncestorEditDialog.pas' {AncestorEditDialogForm: TParentForm},
  AncestorData in '..\..\Forms\Ancestor\AncestorData.pas' {AncestorDataForm: TParentForm},
  AncestorReport in '..\..\Forms\Ancestor\AncestorReport.pas' {AncestorReportForm: TParentForm},
  AncestorDBGrid in '..\..\Forms\Ancestor\AncestorDBGrid.pas' {AncestorDBGridForm: TParentForm},
  AncestorJournal in '..\..\Forms\Ancestor\AncestorJournal.pas' {AncestorJournalForm: TParentForm},
  ObjectDesc in '..\..\Forms\System\ObjectDesc.pas' {ObjectDescForm: TParentForm},
  CommonObjectDescProcedureTest in '..\SOURCE\ObjectDesc\CommonObjectDescProcedureTest.pas',
  AncestorEnum in '..\..\Forms\Ancestor\AncestorEnum.pas' {AncestorEnumForm: TParentForm},
  Objects in '..\..\Forms\System\Objects.pas' {ObjectForm: TParentForm},
  AncestorDocumentMC in '..\..\Forms\Ancestor\AncestorDocumentMC.pas' {AncestorDocumentMCForm: TParentForm},
  CashJournalUser in '..\..\Forms\Document\CashJournalUser.pas' {CashJournalUserForm: TParentForm},
  Report_GoodsMI_OrderExternal_Sale in '..\..\Forms\Report\Report_GoodsMI_OrderExternal_Sale.pas' {Report_GoodsMI_OrderExternal_SaleForm: TParentForm},
  CashOperation in '..\..\Forms\Document\CashOperation.pas' {CashOperationForm: TParentForm},
  SendTicketFuel in '..\..\Forms\Document\SendTicketFuel.pas' {SendTicketFuelForm: TParentForm},
  SendTicketFuelJournal in '..\..\Forms\Document\SendTicketFuelJournal.pas' {SendTicketFuelJournalForm: TParentForm},
  Units in '..\..\Forms\Guides\Units.pas' {UnitForm: TParentForm},
  Goods in '..\..\Forms\Guides\Goods.pas' {GoodsForm: TParentForm},
  BankAccountJournal in '..\..\Forms\Document\BankAccountJournal.pas' {BankAccountJournalForm: TParentForm},
  ClientBankLoad in '..\..\SOURCE\COMPONENT\ClientBankLoad.pas',
  SimpleGauge in '..\..\SOURCE\SimpleGauge.pas' {SimpleGaugeForm},
  ContractStateKind in '..\..\Forms\Kind\ContractStateKind.pas' {ContractStateKindForm: TParentForm},
  ContractArticleEdit in '..\..\Forms\Guides\ContractArticleEdit.pas' {ContractArticleEditForm: TParentForm},
  ContractArticle in '..\..\Forms\Guides\ContractArticle.pas' {ContractArticleForm: TParentForm},
  ContractTag in '..\..\Forms\Guides\ContractTag.pas' {ContractTagForm: TParentForm},
  ContractTagEdit in '..\..\Forms\Guides\ContractTagEdit.pas' {ContractTagEditForm: TParentForm},
  BankStatement in '..\..\Forms\Document\BankStatement.pas' {BankStatementForm: TParentForm},
  ContractChoicePartnerOrder in '..\..\Forms\Guides\ContractChoicePartnerOrder.pas' {ContractChoicePartnerOrderForm: TParentForm},
  ContractConditionByContract in '..\..\Forms\Guides\ContractConditionByContract.pas' {ContractConditionByContractForm: TParentForm},
  MoneyPlac_Object in '..\..\Forms\Guides\MoneyPlac_Object.pas' {MoneyPlaceCash_ObjectForm: TParentForm},
  ProfitLossService in '..\..\Forms\Document\ProfitLossService.pas' {ProfitLossServiceForm: TParentForm},
  AncestorGuides in '..\..\Forms\Ancestor\AncestorGuides.pas' {AncestorGuidesForm: TParentForm},
  WorkTimeKind in '..\..\Forms\Kind\WorkTimeKind.pas' {WorkTimeKindForm: TParentForm},
  MovementDesc in '..\..\Forms\Kind\MovementDesc.pas' {MovementDescForm: TParentForm},
  JuridicalEdit in '..\..\Forms\Guides\JuridicalEdit.pas' {JuridicalEditForm: TParentForm},
  JuridicalDetailsTest in '..\SOURCE\ObjectHistory\All\JuridicalDetailsTest.pas',
  WorkTimeKind_Object in '..\..\Forms\Kind\WorkTimeKind_Object.pas' {WorkTimeKind_ObjectForm: TParentForm},
  Calendar in '..\..\Forms\Guides\Calendar.pas' {CalendarForm: TParentForm},
  GoodsTree_Object in '..\..\Forms\Guides\GoodsTree_Object.pas' {GoodsTree_ObjectForm: TParentForm},
  BankStatementJournal in '..\..\Forms\Document\BankStatementJournal.pas' {BankStatementJournalForm: TParentForm},
  BankAccountMovement in '..\..\Forms\Document\BankAccountMovement.pas' {BankAccountMovementForm: TParentForm},
  Document in '..\..\SOURCE\COMPONENT\Document.pas',
  DefaultsKey in '..\..\Forms\System\DefaultsKey.pas' {DefaultsKeyForm: TParentForm},
  FormsUnit in '..\..\Forms\System\FormsUnit.pas' {FormsForm: TParentForm},
  UnionDesc in '..\..\Forms\System\UnionDesc.pas' {UnionDescForm: TParentForm},
  SendDebtJournal in '..\..\Forms\Document\SendDebtJournal.pas' {SendDebtJournalForm: TParentForm},
  BranchEdit in '..\..\Forms\Guides\BranchEdit.pas' {BranchEditForm: TParentForm},
  Branch in '..\..\Forms\Guides\Branch.pas' {BranchForm: TParentForm},
  Branch_Object in '..\..\Forms\Guides\Branch_Object.pas' {Branch_ObjectForm: TParentForm},
  Cash in '..\..\Forms\Guides\Cash.pas' {CashForm: TParentForm},
  CashEdit in '..\..\Forms\Guides\CashEdit.pas' {CashEditForm: TParentForm},
  Cash_Object in '..\..\Forms\Guides\Cash_Object.pas' {Cash_ObjectForm: TParentForm},
  SendDebt in '..\..\Forms\Document\SendDebt.pas' {SendDebtForm: TParentForm},
  TransportServiceJournal in '..\..\Forms\Document\TransportServiceJournal.pas' {TransportServiceJournalForm: TParentForm},
  UserKey in '..\..\Forms\Guides\UserKey.pas' {UserKeyForm: TParentForm},
  MovementCheck in '..\..\Forms\System\MovementCheck.pas' {MovementCheckForm: TParentForm},
  InfoMoney in '..\..\Forms\Guides\InfoMoney.pas' {InfoMoneyForm: TParentForm},
  SalaryCalculation in '..\SOURCE\Calculation\SalaryCalculation.pas',
  Juridical_PriceList in '..\..\Forms\Guides\Juridical_PriceList.pas' {Juridical_PriceListForm: TParentForm},
  TransportTest in '..\SOURCE\Movement\All\TransportTest.pas',
  SheetWorkTimeAddRecord in '..\..\Forms\Document\SheetWorkTimeAddRecord.pas' {SheetWorkTimeAddRecordForm: TParentForm},
  PartnerJuridicalEdit in '..\..\Forms\Guides\PartnerJuridicalEdit.pas' {PartnerJuridicalEditForm: TParentForm},
  PartnerEdit in '..\..\Forms\Guides\PartnerEdit.pas' {PartnerEditForm: TParentForm},
  PersonalAccountTest in '..\SOURCE\Movement\All\PersonalAccountTest.pas',
  PersonalAccount in '..\..\Forms\Document\PersonalAccount.pas' {PersonalAccountForm: TParentForm},
  PersonalAccountJournal in '..\..\Forms\Document\PersonalAccountJournal.pas' {PersonalAccountJournalForm: TParentForm},
  GoodsKindWeighingGroup in '..\..\Forms\Guides\GoodsKindWeighingGroup.pas' {GoodsKindWeighingGroupForm: TParentForm},
  GoodsKindWeighingEdit in '..\..\Forms\Guides\GoodsKindWeighingEdit.pas' {GoodsKindWeighingEditForm: TParentForm},
  GoodsKindWeighingGroupEdit in '..\..\Forms\Guides\GoodsKindWeighingGroupEdit.pas' {GoodsKindWeighingGroupEditForm: TParentForm},
  GoodsPropertyValue in '..\..\Forms\Guides\GoodsPropertyValue.pas' {GoodsPropertyValueForm: TParentForm},
  ContractChoice in '..\..\Forms\Guides\ContractChoice.pas' {ContractChoiceForm: TParentForm},
  ReturnIn_PartnerJournal in '..\..\Forms\Document\ReturnIn_PartnerJournal.pas' {ReturnIn_PartnerJournalForm: TParentForm},
  ReturnIn_Partner in '..\..\Forms\Document\ReturnIn_Partner.pas' {ReturnIn_PartnerForm: TParentForm},
  Report_JuridicalCollation in '..\..\Forms\Report\Report_JuridicalCollation.pas' {Report_JuridicalCollationForm: TParentForm},
  Report_JuridicalSold in '..\..\Forms\Report\Report_JuridicalSold.pas' {Report_JuridicalSoldForm: TParentForm},
  MovementDescForms in '..\..\Forms\System\MovementDescForms.pas' {MovementDescDataForm: TParentForm},
  Report_CheckTaxCorrective in '..\..\Forms\Report\Report_CheckTaxCorrective.pas' {Report_CheckTaxCorrectiveForm: TParentForm},
  LossDebtJournal in '..\..\Forms\Document\LossDebtJournal.pas' {LossDebtJournalForm: TParentForm},
  LossDebt in '..\..\Forms\Document\LossDebt.pas' {LossDebtForm: TParentForm},
  TransportService in '..\..\Forms\Document\TransportService.pas' {TransportServiceForm: TParentForm},
  TaxCorrectiveJournal in '..\..\Forms\Document\TaxCorrectiveJournal.pas' {TaxCorrectiveJournalForm: TParentForm},
  TaxCorrective in '..\..\Forms\Document\TaxCorrective.pas' {TaxCorrectiveForm: TParentForm},
  Partner1CLink_Excel in '..\..\Forms\LOAD1C\Partner1CLink_Excel.pas' {Partner1CLink_ExcelForm: TParentForm},
  GoodsByGoodsKind1CLink in '..\..\Forms\LOAD1C\GoodsByGoodsKind1CLink.pas' {GoodsByGoodsKind1CLinkForm: TParentForm},
  LossDebtTest in '..\SOURCE\Movement\All\LossDebtTest.pas',
  dbMeatTest in '..\SOURCE\dbMeatTest.pas',
  LoadMoneyFrom1C in '..\..\Forms\LOAD1C\LoadMoneyFrom1C.pas' {LoadMoneyFrom1CForm: TParentForm},
  ExternalDocumentLoad in '..\..\SOURCE\COMPONENT\ExternalDocumentLoad.pas',
  ExternalLoad in '..\..\SOURCE\COMPONENT\ExternalLoad.pas',
  ExternalLoadTest in '..\SOURCE\Component\ExternalLoadTest.pas',
  PersonalSendCashTest in '..\SOURCE\Movement\All\PersonalSendCashTest.pas',
  SheetWorkTimeMovementItemTest in '..\SOURCE\MovementItem\All\SheetWorkTimeMovementItemTest.pas',
  Report_GoodsMI_IncomeByPartner in '..\..\Forms\Report\Report_GoodsMI_IncomeByPartner.pas' {Report_GoodsMI_IncomeByPartnerForm: TParentForm},
  Account in '..\..\Forms\Guides\Account.pas' {AccountForm: TParentForm},
  Log in '..\..\SOURCE\Log.pas',
  Report_GoodsMI_TransferDebt in '..\..\Forms\Report\Report_GoodsMI_TransferDebt.pas' {Report_GoodsMI_TransferDebtForm: TParentForm},
  Report_JuridicalDefermentIncome in '..\..\Forms\Report\Report_JuridicalDefermentIncome.pas' {Report_JuridicalDefermentIncomeForm: TParentForm},
  PaidKind in '..\..\Forms\Kind\PaidKind.pas' {PaidKindForm: TParentForm},
  Tax in '..\..\Forms\Document\Tax.pas' {TaxForm: TParentForm},
  OrderExternalJournalChoice in '..\..\Forms\Document\OrderExternalJournalChoice.pas' {OrderExternalJournalChoiceForm: TParentForm},
  GoodsFuel_Object in '..\..\Forms\Guides\GoodsFuel_Object.pas' {GoodsFuel_ObjectForm: TParentForm},
  JuridicalGroupEdit in '..\..\Forms\Guides\JuridicalGroupEdit.pas' {JuridicalGroupEditForm: TParentForm},
  AssetGroup in '..\..\Forms\Guides\AssetGroup.pas' {AssetGroupForm: TParentForm},
  BonusKind in '..\..\Forms\Kind\BonusKind.pas' {BonusKindForm: TParentForm},
  BonusKindEdit in '..\..\Forms\Kind\BonusKindEdit.pas' {BonusKindEditForm: TParentForm},
  JuridicalGroup_Object in '..\..\Forms\Guides\JuridicalGroup_Object.pas' {JuridicalGroup_ObjectForm: TParentForm},
  SelectKind in '..\..\Forms\Kind\SelectKind.pas' {SelectKindForm: TParentForm},
  DocumentTaxKindTest in '..\SOURCE\Objects\All\DocumentTaxKindTest.pas',
  TaxCorrectiveTest in '..\SOURCE\Movement\All\TaxCorrectiveTest.pas',
  TaxTest in '..\SOURCE\Movement\All\TaxTest.pas',
  ReturnInTest in '..\SOURCE\Movement\All\ReturnInTest.pas',
  AssetEdit in '..\..\Forms\Guides\AssetEdit.pas' {AssetEditForm: TParentForm},
  Asset in '..\..\Forms\Guides\Asset.pas' {AssetForm: TParentForm},
  Maker in '..\..\Forms\Guides\Maker.pas' {MakerForm: TParentForm},
  MakerEdit in '..\..\Forms\Guides\MakerEdit.pas' {MakerEditForm: TParentForm},
  SaleMovementItemTest in '..\SOURCE\MovementItem\All\SaleMovementItemTest.pas',
  ReturnInMovementItemTest in '..\SOURCE\MovementItem\All\ReturnInMovementItemTest.pas',
  TaxMovementItemTest in '..\SOURCE\MovementItem\All\TaxMovementItemTest.pas',
  UserProtocol in '..\..\Forms\System\UserProtocol.pas' {UserProtocolForm: TParentForm},
  MovementProtocol in '..\..\Forms\System\MovementProtocol.pas' {MovementProtocolForm: TParentForm},
  Protocol in '..\..\Forms\System\Protocol.pas' {ProtocolForm: TParentForm},
  MovementItemProtocol in '..\..\Forms\System\MovementItemProtocol.pas' {MovementItemProtocolForm: TParentForm},
  Report_GoodsTax in '..\..\Forms\Report\Report_GoodsTax.pas' {Report_GoodsTaxForm: TParentForm},
  ReturnOutTest in '..\SOURCE\Movement\All\ReturnOutTest.pas',
  ReturnOutMovementItemTest in '..\SOURCE\MovementItem\All\ReturnOutMovementItemTest.pas',
  ReturnOutPartnerJournal in '..\..\Forms\Document\ReturnOutPartnerJournal.pas' {ReturnOutPartnerJournalForm: TParentForm},
  ReturnOutPartner in '..\..\Forms\Document\ReturnOutPartner.pas' {ReturnOutPartnerForm: TParentForm},
  Report_CheckBonus in '..\..\Forms\Report\Report_CheckBonus.pas' {Report_CheckBonusForm: TParentForm},
  PersonalReportJournal in '..\..\Forms\Document\PersonalReportJournal.pas' {PersonalReportJournalForm: TParentForm},
  ProfitLossServiceJournal in '..\..\Forms\Document\ProfitLossServiceJournal.pas' {ProfitLossServiceJournalForm: TParentForm},
  PersonalReport in '..\..\Forms\Document\PersonalReport.pas' {PersonalReportForm: TParentForm},
  ServiceTest in '..\SOURCE\Movement\All\ServiceTest.pas',
  MemberExternal in '..\..\Forms\Guides\MemberExternal.pas' {MemberExternalForm: TParentForm},
  MemberExternalEdit in '..\..\Forms\Guides\MemberExternalEdit.pas' {MemberExternalEditForm: TParentForm},
  ContractConditionKind in '..\..\Forms\Kind\ContractConditionKind.pas' {ContractConditionKindForm: TParentForm},
  PeriodClose_User in '..\..\Forms\System\PeriodClose_User.pas' {PeriodClose_UserForm: TParentForm},
  Contract in '..\..\Forms\Guides\Contract.pas' {ContractForm: TParentForm},
  SaveMarketingDocumentTo1C in '..\..\Forms\Export\SaveMarketingDocumentTo1C.pas' {SaveMarketingDocumentTo1CForm: TParentForm},
  ExternalSave in '..\..\SOURCE\COMPONENT\ExternalSave.pas',
  MovementGoods_Journal in '..\..\Forms\Report\MovementGoods_Journal.pas' {MovementGoodsJournalForm: TParentForm},
  UnitTree in '..\..\Forms\Guides\UnitTree.pas' {UnitTreeForm: TParentForm},
  UnitEdit in '..\..\Forms\Guides\UnitEdit.pas' {UnitEditForm: TParentForm},
  ExternalData in '..\..\SOURCE\COMPONENT\ExternalData.pas',
  Partner_Object in '..\..\Forms\Guides\Partner_Object.pas' {Partner_ObjectForm: TParentForm},
  WeighingProductionJournal in '..\..\Forms\Document\WeighingProductionJournal.pas' {WeighingProductionJournalForm: TParentForm},
  WeighingProduction in '..\..\Forms\Document\WeighingProduction.pas' {WeighingProductionForm: TParentForm},
  WeighingPartner in '..\..\Forms\Document\WeighingPartner.pas' {WeighingPartnerForm: TParentForm},
  WeighingPartnerJournal in '..\..\Forms\Document\WeighingPartnerJournal.pas' {WeighingPartnerJournalForm: TParentForm},
  Report_CheckTax in '..\..\Forms\Report\Report_CheckTax.pas' {Report_CheckTaxForm: TParentForm},
  AccountGroup in '..\..\Forms\Guides\AccountGroup.pas' {AccountGroupForm: TParentForm},
  AccountDirection in '..\..\Forms\Guides\AccountDirection.pas' {AccountDirectionForm: TParentForm},
  ProfitLoss in '..\..\Forms\Guides\ProfitLoss.pas' {ProfitLossForm: TParentForm},
  ProfitLossDirection in '..\..\Forms\Guides\ProfitLossDirection.pas' {ProfitLossDirectionForm: TParentForm},
  ProfitLossGroup in '..\..\Forms\Guides\ProfitLossGroup.pas' {ProfitLossGroupForm: TParentForm},
  InfoMoneyDestination in '..\..\Forms\Guides\InfoMoneyDestination.pas' {InfoMoneyDestinationForm: TParentForm},
  Business in '..\..\Forms\Guides\Business.pas' {BusinessForm: TParentForm},
  GoodsTree in '..\..\Forms\Guides\GoodsTree.pas' {GoodsTreeForm: TParentForm},
  GoodsEdit in '..\..\Forms\Guides\GoodsEdit.pas' {GoodsEditForm: TParentForm},
  MovementTaxChoice in '..\..\Forms\Guides\MovementTaxChoice.pas' {MovementTaxChoiceForm: TParentForm},
  CityEdit in '..\..\Forms\Guides\CityEdit.pas' {CityEditForm: TParentForm},
  ProvinceCity in '..\..\Forms\Guides\ProvinceCity.pas' {ProvinceCityForm: TParentForm},
  TaxJournal in '..\..\Forms\Document\TaxJournal.pas' {TaxJournalForm: TParentForm},
  Report_CheckContractInMovement in '..\..\Forms\Report\Report_CheckContractInMovement.pas' {Report_CheckContractInMovementForm: TParentForm},
  Area in '..\..\Forms\Guides\Area.pas' {AreaForm: TParentForm},
  AreaEdit in '..\..\Forms\Guides\AreaEdit.pas' {AreaEditForm: TParentForm},
  SaleJournal in '..\..\Forms\Document\SaleJournal.pas' {SaleJournalForm: TParentForm},
  Sale in '..\..\Forms\Document\Sale.pas' {SaleForm: TParentForm},
  BankAccount_Object in '..\..\Forms\Guides\BankAccount_Object.pas' {BankAccount_ObjectForm: TParentForm},
  CorrespondentAccountEdit in '..\..\Forms\Guides\CorrespondentAccountEdit.pas' {CorrespondentAccountEditForm: TParentForm},
  Partner1CLinkPlace in '..\..\Forms\LOAD1C\Partner1CLinkPlace.pas' {Partner1CLinkPlaceForm: TParentForm},
  TransferDebtIn in '..\..\Forms\Document\TransferDebtIn.pas' {TransferDebtInForm: TParentForm},
  TransferDebtInJournal in '..\..\Forms\Document\TransferDebtInJournal.pas' {TransferDebtInJournalForm: TParentForm},
  TransferDebtOut in '..\..\Forms\Document\TransferDebtOut.pas' {TransferDebtOutForm: TParentForm},
  TransferDebtOutJournal in '..\..\Forms\Document\TransferDebtOutJournal.pas' {TransferDebtOutJournalForm: TParentForm},
  EdiTest in '..\SOURCE\EDI\EdiTest.pas',
  ComDocXML in '..\..\SOURCE\EDI\ComDocXML.pas',
  DeclarXML in '..\..\SOURCE\EDI\DeclarXML.pas',
  EDI in '..\..\SOURCE\EDI\EDI.pas',
  MeDocXML in '..\..\SOURCE\MeDOC\MeDocXML.pas',
  MeDOC in '..\..\SOURCE\MeDOC\MeDOC.pas',
  DesadvXML in '..\..\SOURCE\EDI\DesadvXML.pas',
  ObjectTest in '..\SOURCE\Objects\ObjectTest.pas',
  OrderXML in '..\..\SOURCE\EDI\OrderXML.pas',
  MovementItemContainer in '..\..\Forms\System\MovementItemContainer.pas' {MovementItemContainerForm: TParentForm},
  EDIMovementTest in '..\SOURCE\Movement\All\EDIMovementTest.pas',
  EDIJournal in '..\..\Forms\EDI\EDIJournal.pas' {EDIJournalForm: TParentForm},
  cxGridAddOn in '..\..\SOURCE\DevAddOn\cxGridAddOn.pas',
  Report_GoodsMI_byMovement in '..\..\Forms\Report\Report_GoodsMI_byMovement.pas' {Report_GoodsMI_byMovementForm: TParentForm},
  SaveTaxDocument in '..\..\Forms\Export\SaveTaxDocument.pas' {SaveTaxDocumentForm: TParentForm},
  Report_GoodsMI in '..\..\Forms\Report\Report_GoodsMI.pas' {Report_GoodsMIForm: TParentForm},
  Report_GoodsMI_byPriceDif in '..\..\Forms\Report\Report_GoodsMI_byPriceDif.pas' {Report_GoodsMI_byPriceDifForm: TParentForm},
  Report_GoodsMI_byMovementDif in '..\..\Forms\Report\Report_GoodsMI_byMovementDif.pas' {Report_GoodsMI_byMovementDifForm: TParentForm},
  Report_Goods in '..\..\Forms\Report\Report_Goods.pas' {Report_GoodsForm: TParentForm},
  PriceList in '..\..\Forms\Guides\PriceList.pas' {PriceListForm: TParentForm},
  Retail in '..\..\Forms\Guides\Retail.pas' {RetailForm: TParentForm},
  RetailEdit in '..\..\Forms\Guides\RetailEdit.pas' {RetailEditForm: TParentForm},
  OrderExternalJournal in '..\..\Forms\Document\OrderExternalJournal.pas' {OrderExternalJournalForm: TParentForm},
  OrderExternal in '..\..\Forms\Document\OrderExternal.pas' {OrderExternalForm: TParentForm},
  AncestorDocument in '..\..\Forms\Ancestor\AncestorDocument.pas' {AncestorDocumentForm: TParentForm},
  ProductionSeparate in '..\..\Forms\Document\ProductionSeparate.pas' {ProductionSeparateForm: TParentForm},
  PriceCorrectiveJournal in '..\..\Forms\Document\PriceCorrectiveJournal.pas' {PriceCorrectiveJournalForm: TParentForm},
  PriceCorrective in '..\..\Forms\Document\PriceCorrective.pas' {PriceCorrectiveForm: TParentForm},
  GoodsGroup in '..\..\Forms\Guides\GoodsGroup.pas' {GoodsGroupForm: TParentForm},
  GoodsKind in '..\..\Forms\Guides\GoodsKind.pas' {GoodsKindForm: TParentForm},
  Province in '..\..\Forms\Guides\Province.pas' {ProvinceForm: TParentForm},
  ProvinceCityEdit in '..\..\Forms\Guides\ProvinceCityEdit.pas' {ProvinceCityEditForm: TParentForm},
  Country in '..\..\Forms\Guides\Country.pas' {CountryForm: TParentForm},
  CountryEdit in '..\..\Forms\Guides\CountryEdit.pas' {CountryEditForm: TParentForm},
  Street in '..\..\Forms\Guides\Street.pas' {StreetForm: TParentForm},
  StreetEdit in '..\..\Forms\Guides\StreetEdit.pas' {StreetEditForm: TParentForm},
  StreetKind in '..\..\Forms\Guides\StreetKind.pas' {StreetKindForm: TParentForm},
  StreetKindEdit in '..\..\Forms\Guides\StreetKindEdit.pas' {StreetKindEditForm: TParentForm},
  Region in '..\..\Forms\Guides\Region.pas' {RegionForm: TParentForm},
  RegionEdit in '..\..\Forms\Guides\RegionEdit.pas' {RegionEditForm: TParentForm},
  City in '..\..\Forms\Guides\City.pas' {CityForm: TParentForm},
  ProvinceEdit in '..\..\Forms\Guides\ProvinceEdit.pas' {ProvinceEditForm: TParentForm},
  Inventory in '..\..\Forms\Document\Inventory.pas' {InventoryForm: TParentForm},
  InventoryJournal in '..\..\Forms\Document\InventoryJournal.pas' {InventoryJournalForm: TParentForm},
  OrderInternalBasisJournal in '..\..\Forms\Document\OrderInternalBasisJournal.pas' {OrderInternalBasisJournalForm: TParentForm},
  OrderInternalBasis in '..\..\Forms\Document\OrderInternalBasis.pas' {OrderInternalBasisForm: TParentForm},
  OrderKind in '..\..\Forms\Kind\OrderKind.pas' {OrderKindForm: TParentForm},
  ContactPersonEdit in '..\..\Forms\Guides\ContactPersonEdit.pas' {ContactPersonEditForm: TParentForm},
  ContactPersonKind in '..\..\Forms\Kind\ContactPersonKind.pas' {ContactPersonKindForm: TParentForm},
  PartnerAddress in '..\..\Forms\Guides\PartnerAddress.pas' {PartnerAddressForm: TParentForm},
  dbObjectMeatTest in '..\SOURCE\dbObjectMeatTest.pas',
  AncestorBase in '..\..\Forms\Ancestor\AncestorBase.pas' {AncestorBaseForm: TParentForm},
  CurrencyValue_Object in '..\..\Forms\Guides\CurrencyValue_Object.pas' {CurrencyValue_ObjectForm: TParentForm},
  MeasureTest in '..\SOURCE\Objects\All\MeasureTest.pas',
  CorrespondentAccountTest in '..\SOURCE\Objects\All\CorrespondentAccountTest.pas',
  Storage_Object in '..\..\Forms\Guides\Storage_Object.pas' {Storage_ObjectForm: TParentForm},
  Storage_ObjectEdit in '..\..\Forms\Guides\Storage_ObjectEdit.pas' {Storage_ObjectEditForm: TParentForm},
  CurrencyMovement in '..\..\Forms\Document\CurrencyMovement.pas' {CurrencyMovementForm: TParentForm},
  CurrencyJournal in '..\..\Forms\Document\CurrencyJournal.pas' {CurrencyJournalForm: TParentForm},
  SendJournal in '..\..\Forms\Document\SendJournal.pas' {SendJournalForm: TParentForm},
  Send in '..\..\Forms\Document\Send.pas' {SendForm: TParentForm},
  BranchTest in '..\SOURCE\Objects\All\BranchTest.pas',
  JuridicalGroupTest in '..\SOURCE\Objects\All\JuridicalGroupTest.pas',
  GoodsPropertyTest in '..\SOURCE\Objects\All\GoodsPropertyTest.pas',
  GoodsTest in '..\SOURCE\Objects\All\GoodsTest.pas',
  GoodsKindTest in '..\SOURCE\Objects\All\GoodsKindTest.pas',
  PartnerTest in '..\SOURCE\Objects\All\PartnerTest.pas',
  RouteSortingTest in '..\SOURCE\Objects\All\RouteSortingTest.pas',
  RouteTest in '..\SOURCE\Objects\All\RouteTest.pas',
  AccountDirectionTest in '..\SOURCE\Objects\All\AccountDirectionTest.pas',
  AccountGroupTest in '..\SOURCE\Objects\All\AccountGroupTest.pas',
  CarTest in '..\SOURCE\Objects\All\CarTest.pas',
  CarModelTest in '..\SOURCE\Objects\All\CarModelTest.pas',
  PaidKindTest in '..\SOURCE\Objects\All\PaidKindTest.pas',
  InfoMoneyDestinationTest in '..\SOURCE\Objects\All\InfoMoneyDestinationTest.pas',
  InfoMoneyGroupTest in '..\SOURCE\Objects\All\InfoMoneyGroupTest.pas',
  ProfitLossDirectionTest in '..\SOURCE\Objects\All\ProfitLossDirectionTest.pas',
  ProfitLossGroupTest in '..\SOURCE\Objects\All\ProfitLossGroupTest.pas',
  PriceListTest in '..\SOURCE\Objects\All\PriceListTest.pas',
  CurrencyTest in '..\SOURCE\Objects\All\CurrencyTest.pas',
  AssetGroupTest in '..\SOURCE\Objects\All\AssetGroupTest.pas',
  MemberTest in '..\SOURCE\Objects\All\MemberTest.pas',
  PositionTest in '..\SOURCE\Objects\All\PositionTest.pas',
  BranchLink in '..\..\FormsMeat\Guides\BranchLink.pas' {BranchLinkForm: TParentForm},
  Partner_PriceList in '..\..\Forms\Guides\Partner_PriceList.pas' {Partner_PriceListForm: TParentForm},
  Report_GoodsMI_Production in '..\..\Forms\Report\Report_GoodsMI_Production.pas' {Report_GoodsMI_ProductionForm: TParentForm},
  Report_GoodsMI_ProductionSeparate in '..\..\Forms\Report\Report_GoodsMI_ProductionSeparate.pas' {Report_GoodsMI_ProductionSeparateForm: TParentForm},
  Member in '..\..\Forms\Guides\Member.pas' {MemberForm: TParentForm},
  MoneyPlace_Object in '..\..\Forms\Guides\MoneyPlace_Object.pas' {MoneyPlace_ObjectForm: TParentForm},
  UnitsTest in '..\SOURCE\Objects\All\UnitsTest.pas',
  ContractTest in '..\SOURCE\Objects\All\ContractTest.pas',
  LoadSaleFrom1C in '..\..\Forms\LOAD1C\LoadSaleFrom1C.pas' {LoadSaleFrom1CForm: TParentForm},
  Founder in '..\..\Forms\Guides\Founder.pas' {FounderForm: TParentForm},
  FounderEdit in '..\..\Forms\Guides\FounderEdit.pas' {FounderEditForm: TParentForm},
  ArticleLoss in '..\..\Forms\Guides\ArticleLoss.pas' {ArticleLossForm: TParentForm},
  ArticleLossEdit in '..\..\Forms\Guides\ArticleLossEdit.pas' {ArticleLossEditForm: TParentForm},
  Report_GoodsMI_OrderExternal in '..\..\Forms\Report\Report_GoodsMI_OrderExternal.pas' {Report_GoodsMI_OrderExternalForm: TParentForm},
  GoodsGroupStat in '..\..\Forms\Guides\GoodsGroupStat.pas' {GoodsGroupStatForm: TParentForm},
  GoodsGroupStatEdit in '..\..\Forms\Guides\GoodsGroupStatEdit.pas' {GoodsGroupStatEditForm: TParentForm},
  Report_Personal in '..\..\Forms\Report\Report_Personal.pas' {Report_PersonalForm: TParentForm},
  Report_Founders in '..\..\Forms\Report\Report_Founders.pas' {Report_FoundersForm: TParentForm},
  Report_CashUser in '..\..\Forms\Report\Report_CashUser.pas' {Report_CashUserForm: TParentForm},
  Report_BankAccount in '..\..\Forms\Report\Report_BankAccount.pas' {Report_BankAccountForm: TParentForm},
  Report_Member in '..\..\Forms\Report\Report_Member.pas' {Report_MemberForm: TParentForm},
  SaveDocumentTo1C in '..\..\Forms\Export\SaveDocumentTo1C.pas' {SaveDocumentTo1CForm: TParentForm},
  PersonalServiceJournal in '..\..\Forms\Document\PersonalServiceJournal.pas' {PersonalServiceJournalForm: TParentForm},
  PersonalService in '..\..\Forms\Document\PersonalService.pas' {PersonalServiceForm: TParentForm},
  Personal in '..\..\Forms\Guides\Personal.pas' {PersonalForm: TParentForm},
  PersonalServiceList in '..\..\Forms\Guides\PersonalServiceList.pas' {PersonalServiceListForm: TParentForm},
  PersonalServiceListEdit in '..\..\Forms\Guides\PersonalServiceListEdit.pas' {PersonalServiceListEditForm: TParentForm},
  InfoMoneyGroup in '..\..\Forms\Guides\InfoMoneyGroup.pas' {InfoMoneyGroupForm: TParentForm},
  JuridicalGroup in '..\..\Forms\Guides\JuridicalGroup.pas' {JuridicalGroupForm: TParentForm},
  GoodsTag in '..\..\Forms\Guides\GoodsTag.pas' {GoodsTagForm: TParentForm},
  GoodsTagEdit in '..\..\Forms\Guides\GoodsTagEdit.pas' {GoodsTagEditForm: TParentForm},
  Partner1CLink in '..\..\Forms\LOAD1C\Partner1CLink.pas' {Partner1CLinkForm: TParentForm},
  QualityParamsJournal in '..\..\Forms\Document\QualityParamsJournal.pas' {QualityParamsJournalForm: TParentForm},
  ProductionUnionTechEdit in '..\..\Forms\Document\ProductionUnionTechEdit.pas' {ProductionUnionTechEditForm: TParentForm},
  SaleTest in '..\SOURCE\Movement\All\SaleTest.pas',
  IncomeTest in '..\SOURCE\Movement\All\Farmacy\IncomeTest.pas',
  ProductionUnionTest in '..\SOURCE\Movement\All\ProductionUnionTest.pas',
  ProductionSeparateTest in '..\SOURCE\Movement\All\ProductionSeparateTest.pas',
  SendOnPriceTest in '..\SOURCE\Movement\All\SendOnPriceTest.pas',
  Cash_PersonalJournal in '..\..\Forms\Document\Cash_PersonalJournal.pas' {Cash_PersonalJournalForm: TParentForm},
  Cash_Personal in '..\..\Forms\Document\Cash_Personal.pas' {Cash_PersonalForm: TParentForm},
  PersonalServiceJournalChoice in '..\..\Forms\Document\PersonalServiceJournalChoice.pas' {PersonalServiceJournalChoiceForm: TParentForm},
  SendTest in '..\SOURCE\Movement\All\SendTest.pas',
  LossTest in '..\SOURCE\Movement\All\LossTest.pas',
  InventoryTest in '..\SOURCE\Movement\All\InventoryTest.pas',
  ZakazExternalTest in '..\SOURCE\Movement\All\ZakazExternalTest.pas',
  ZakazInternalTest in '..\SOURCE\Movement\All\ZakazInternalTest.pas',
  TransportGoods in '..\..\Forms\Document\TransportGoods.pas' {TransportGoodsForm: TParentForm},
  TransportGoodsJournal in '..\..\Forms\Document\TransportGoodsJournal.pas' {TransportGoodsJournalForm: TParentForm},
  PeriodClose in '..\..\Forms\System\PeriodClose.pas' {PeriodCloseForm: TParentForm},
  CorrespondentAccount in '..\..\Forms\Guides\CorrespondentAccount.pas' {CorrespondentAccountForm: TParentForm},
  ProfitLossDirection_Object in '..\..\Forms\Guides\ProfitLossDirection_Object.pas' {ProfitLossDirection_ObjectForm: TParentForm},
  MeasureEdit in '..\..\Forms\MeasureEdit.pas' {MeasureEditForm: TParentForm},
  Measure in '..\..\Forms\Measure.pas' {MeasureForm: TParentForm},
  PartionGoodsChoice in '..\..\Forms\Guides\PartionGoodsChoice.pas' {PartionGoodsChoiceForm: TParentForm},
  BankAccountEdit in '..\..\Forms\Guides\BankAccountEdit.pas' {BankAccountEditForm: TParentForm},
  BankAccount in '..\..\Forms\Guides\BankAccount.pas' {BankAccountForm: TParentForm},
  BankTest in '..\SOURCE\Objects\All\BankTest.pas',
  Partner_PriceList_view in '..\..\Forms\Guides\Partner_PriceList_view.pas' {Partner_PriceList_viewForm: TParentForm},
  CashJournal in '..\..\Forms\Document\CashJournal.pas' {CashJournalForm: TParentForm},
  ReturnInJournalChoice in '..\..\Forms\Document\ReturnInJournalChoice.pas' {ReturnInJournalChoiceForm: TParentForm},
  Sale_OrderJournal in '..\..\Forms\Document\Sale_OrderJournal.pas' {Sale_OrderJournalForm: TParentForm},
  Sale_Partner in '..\..\Forms\Document\Sale_Partner.pas' {Sale_PartnerForm: TParentForm},
  Sale_PartnerJournal in '..\..\Forms\Document\Sale_PartnerJournal.pas' {Sale_PartnerJournalForm: TParentForm},
  Sale_Order in '..\..\Forms\Document\Sale_Order.pas' {Sale_OrderForm: TParentForm},
  ContactPersonChoice in '..\..\Forms\Guides\ContactPersonChoice.pas' {ContactPersonChoiceForm: TParentForm},
  Route in '..\..\Forms\Guides\Route.pas' {RouteForm: TParentForm},
  RouteSorting in '..\..\Forms\Guides\RouteSorting.pas' {RouteSortingForm: TParentForm},
  ReturnIn in '..\..\Forms\Document\ReturnIn.pas' {ReturnInForm: TParentForm},
  ReturnInJournal in '..\..\Forms\Document\ReturnInJournal.pas' {ReturnInJournalForm: TParentForm},
  SendOnPrice in '..\..\Forms\Document\SendOnPrice.pas' {SendOnPriceForm: TParentForm},
  SendOnPriceJournal in '..\..\Forms\Document\SendOnPriceJournal.pas' {SendOnPriceJournalForm: TParentForm},
  Report_Cash in '..\..\Forms\Report\Report_Cash.pas' {Report_CashForm: TParentForm},
  AreaContract in '..\..\Forms\Guides\AreaContract.pas' {AreaContractForm: TParentForm},
  AreaContractEdit in '..\..\Forms\Guides\AreaContractEdit.pas' {AreaContractEditForm: TParentForm},
  RetailReport in '..\..\Forms\Guides\RetailReport.pas' {RetailReportForm: TParentForm},
  RetailReportEdit in '..\..\Forms\Guides\RetailReportEdit.pas' {RetailReportEditForm: TParentForm},
  LookAndFillSettings in '..\..\SOURCE\LookAndFillSettings.pas' {LookAndFillSettingsForm},
  PartnerTag in '..\..\Forms\Guides\PartnerTag.pas' {PartnerTagForm: TParentForm},
  PartnerTagEdit in '..\..\Forms\Guides\PartnerTagEdit.pas' {PartnerTagEditForm: TParentForm},
  InvoiceXML in '..\..\SOURCE\EDI\InvoiceXML.pas',
  OrdrspXML in '..\..\SOURCE\EDI\OrdrspXML.pas',
  Currency_Object in '..\..\Forms\Guides\Currency_Object.pas' {Currency_ObjectForm: TParentForm},
  dsdInternetAction in '..\..\SOURCE\COMPONENT\dsdInternetAction.pas',
  OLAPTest in '..\SOURCE\Component\OLAPTest.pas',
  dsdOlap in '..\..\SOURCE\COMPONENT\dsdOlap.pas',
  dsdOLAPXMLBind in '..\..\SOURCE\COMPONENT\dsdOLAPXMLBind.pas',
  GoodsGroupAnalyst in '..\..\Forms\Guides\GoodsGroupAnalyst.pas' {GoodsGroupAnalystForm: TParentForm},
  GoodsGroupAnalystEdit in '..\..\Forms\Guides\GoodsGroupAnalystEdit.pas' {GoodsGroupAnalystEditForm: TParentForm},
  MainForm in '..\..\FormsMeat\MainForm.pas' {MainForm},
  ImportGroupItemsTest in '..\SOURCE\Objects\All\ImportGroupItemsTest.pas',
  ImportGroupTest in '..\SOURCE\Objects\All\ImportGroupTest.pas',
  ImportSettingsTest in '..\SOURCE\Objects\All\ImportSettingsTest.pas',
  ImportTypeItemsTest in '..\SOURCE\Objects\All\ImportTypeItemsTest.pas',
  ImportTypeTest in '..\SOURCE\Objects\All\ImportTypeTest.pas',
  ImportGroup in '..\..\Forms\Import\ImportGroup.pas' {ImportGroupForm: TParentForm},
  ImportSettings in '..\..\Forms\Import\ImportSettings.pas' {ImportSettingsForm: TParentForm},
  ImportType in '..\..\Forms\Import\ImportType.pas' {ImportTypeForm: TParentForm},
  AncestorMain in '..\..\Forms\Ancestor\AncestorMain.pas' {AncestorMainForm},
  FileTypeKind in '..\..\Forms\Kind\FileTypeKind.pas' {FileTypeKindForm: TParentForm},
  NDSKindTest in '..\SOURCE\Objects\All\NDSKindTest.pas',
  FileTypeKindTest in '..\SOURCE\Objects\All\FileTypeKindTest.pas',
  IncomeMovementItemTest in '..\SOURCE\MovementItem\All\Farmacy\IncomeMovementItemTest.pas',
  Report_GoodsMI_ProductionUnionMD in '..\..\Forms\Report\Report_GoodsMI_ProductionUnionMD.pas' {Report_GoodsMI_ProductionUnionMDForm: TParentForm},
  GoodsQuality in '..\..\Forms\Guides\GoodsQuality.pas' {GoodsQualityForm: TParentForm},
  ImportExportLink in '..\..\Forms\System\ImportExportLink.pas' {ImportExportLinkForm: TParentForm},
  ImportExportLinkType in '..\..\Forms\Kind\ImportExportLinkType.pas' {ImportExportLinkTypeForm: TParentForm},
  ImportExportLinkTest in '..\SOURCE\Objects\All\ImportExportLinkTest.pas',
  ImportExportLinkTypeTest in '..\SOURCE\Objects\All\ImportExportLinkTypeTest.pas',
  ContactPerson in '..\..\Forms\Guides\ContactPerson.pas' {ContactPersonForm: TParentForm},
  ProductionPeresortJournal in '..\..\Forms\Document\ProductionPeresortJournal.pas' {ProductionPeresortJournalForm: TParentForm},
  ProductionPeresort in '..\..\Forms\Document\ProductionPeresort.pas' {ProductionPeresortForm: TParentForm},
  QualityParams in '..\..\Forms\Document\QualityParams.pas' {QualityParamsForm: TParentForm},
  ProductionUnion in '..\..\Forms\Document\ProductionUnion.pas' {ProductionUnionForm: TParentForm},
  Goods_Object in '..\..\Forms\Guides\Goods_Object.pas' {Goods_ObjectForm: TParentForm},
  Receipt_Object in '..\..\Forms\Guides\Receipt_Object.pas' {Receipt_ObjectForm: TParentForm},
  Receipt in '..\..\Forms\Guides\Receipt.pas' {ReceiptForm: TParentForm},
  ReceiptEdit in '..\..\Forms\Guides\ReceiptEdit.pas' {ReceiptEditForm: TParentForm},
  ReceiptCost in '..\..\Forms\Guides\ReceiptCost.pas' {ReceiptCostForm: TParentForm},
  ReceiptCostEdit in '..\..\Forms\Guides\ReceiptCostEdit.pas' {ReceiptCostEditForm: TParentForm},
  ReceiptKind in '..\..\Forms\Kind\ReceiptKind.pas' {ReceiptKindForm: TParentForm},
  ContractTagGroup in '..\..\Forms\Guides\ContractTagGroup.pas' {ContractTagGroupForm: TParentForm},
  ContractTagGroupEdit in '..\..\Forms\Guides\ContractTagGroupEdit.pas' {ContractTagGroupEditForm: TParentForm},
  TransferDebtOut_Order in '..\..\Forms\Document\TransferDebtOut_Order.pas' {TransferDebtOut_OrderForm: TParentForm},
  TransferDebtOut_OrderJournal in '..\..\Forms\Document\TransferDebtOut_OrderJournal.pas' {TransferDebtOut_OrderJournalForm: TParentForm},
  ContractPartner in '..\..\Forms\Guides\ContractPartner.pas' {ContractPartnerForm: TParentForm},
  ContractPartnerEdit in '..\..\Forms\Guides\ContractPartnerEdit.pas' {ContractPartnerEditForm: TParentForm},
  RoleMaskEdit in '..\..\Forms\RoleMaskEdit.pas' {RoleMaskEditForm: TParentForm},
  RoleUnion in '..\..\Forms\RoleUnion.pas' {RoleUnionForm: TParentForm},
  ToolsWeighingPlace_Object in '..\..\Forms\Guides\ToolsWeighingPlace_Object.pas' {ToolsWeighingPlace_ObjectForm: TParentForm},
  Scales in '..\..\SOURCE\Scale\Scales.pas',
  SysScalesLib_TLB in '..\..\Scale\Util\SysScalesLib_TLB.pas',
  dsdDataSetDataLink in '..\..\SOURCE\COMPONENT\dsdDataSetDataLink.pas',
  dsdXMLTransform in '..\..\SOURCE\COMPONENT\dsdXMLTransform.pas',
  Movement_Journal in '..\..\Forms\Report\Movement_Journal.pas' {MovementJournalForm: TParentForm},
  ContractGoodsEdit in '..\..\Forms\Guides\ContractGoodsEdit.pas' {ContractGoodsEditForm: TParentForm},
  ContractGoods in '..\..\Forms\Guides\ContractGoods.pas' {ContractGoodsForm: TParentForm},
  Quality in '..\..\Forms\Guides\Quality.pas' {QualityForm: TParentForm},
  QualityEdit in '..\..\Forms\Guides\QualityEdit.pas' {QualityEditForm: TParentForm},
  ServiceJournal in '..\..\Forms\Document\ServiceJournal.pas' {ServiceJournalForm: TParentForm},
  Service in '..\..\Forms\Document\Service.pas' {ServiceForm: TParentForm},
  OrderExternalUnit in '..\..\Forms\Document\OrderExternalUnit.pas' {OrderExternalUnitForm: TParentForm},
  OrderExternalUnitJournal in '..\..\Forms\Document\OrderExternalUnitJournal.pas' {OrderExternalUnitJournalForm: TParentForm},
  GoodsProperty in '..\..\Forms\Guides\GoodsProperty.pas' {GoodsPropertyForm: TParentForm},
  Report_JuridicalDefermentPayment in '..\..\Forms\Report\Report_JuridicalDefermentPayment.pas' {Report_JuridicalDefermentPaymentForm: TParentForm},
  ProductionOrderReportUnit in '..\..\FormsMeat\Report\Production\ProductionOrderReportUnit.pas' {ProductionOrderReportForm: TParentForm},
  OrderType in '..\..\Forms\Guides\OrderType.pas' {OrderTypeForm: TParentForm},
  ReceiptGoods_Object in '..\..\Forms\Guides\ReceiptGoods_Object.pas' {ReceiptGoods_ObjectForm: TParentForm},
  JuridicalGLN in '..\..\Forms\Guides\JuridicalGLN.pas' {JuridicalGLNForm: TParentForm},
  PartnerGLN in '..\..\Forms\Guides\PartnerGLN.pas' {PartnerGLNForm: TParentForm},
  GoodsByGoodsKind in '..\..\Forms\Guides\GoodsByGoodsKind.pas' {GoodsByGoodsKindForm: TParentForm},
  Report_ReceiptSaleAnalyze in '..\..\Forms\Report\Report_ReceiptSaleAnalyze.pas' {Report_ReceiptSaleAnalyzeForm: TParentForm},
  Report_GoodsMI_Defroster in '..\..\Forms\Report\Report_GoodsMI_Defroster.pas' {Report_GoodsMI_DefrosterForm: TParentForm},
  MeDocCOMTest in '..\SOURCE\Component\MeDocCOMTest.pas',
  StatusXML in '..\..\SOURCE\EDI\StatusXML.pas',
  MeDocCOM in '..\..\SOURCE\MeDOC\MeDocCOM.pas',
  CityKind in '..\..\Forms\Guides\CityKind.pas' {CityKindForm: TParentForm},
  CityKindEdit in '..\..\Forms\Guides\CityKindEdit.pas' {CityKindEditForm: TParentForm},
  FounderService in '..\..\Forms\Document\FounderService.pas' {FounderServiceForm: TParentForm},
  FounderServiceJournal in '..\..\Forms\Document\FounderServiceJournal.pas' {FounderServiceJournalForm: TParentForm},
  StoragePlace_Object in '..\..\Forms\Guides\StoragePlace_Object.pas' {StoragePlace_ObjectForm: TParentForm},
  TaxJournalChoice in '..\..\Forms\Document\TaxJournalChoice.pas' {TaxJournalChoiceForm: TParentForm},
  MEDOC_TLB in '..\..\SOURCE\MeDOC\MEDOC_TLB.pas',
  LoadFlagFromMedoc in '..\..\Forms\Import\LoadFlagFromMedoc.pas' {LoadFlagFromMedocForm: TParentForm},
  Account_Object in '..\..\Forms\Guides\Account_Object.pas' {Account_ObjectForm: TParentForm},
  AccountDirection_Object in '..\..\Forms\Guides\AccountDirection_Object.pas' {AccountDirection_ObjectForm: TParentForm},
  AccountGroup_Object in '..\..\Forms\Guides\AccountGroup_Object.pas' {AccountGroup_ObjectForm: TParentForm},
  InfoMoney_Object in '..\..\Forms\Guides\InfoMoney_Object.pas' {InfoMoney_ObjectForm: TParentForm},
  InfoMoneyDestination_Object in '..\..\Forms\Guides\InfoMoneyDestination_Object.pas' {InfoMoneyDestination_ObjectForm: TParentForm},
  InfoMoneyGroup_Object in '..\..\Forms\Guides\InfoMoneyGroup_Object.pas' {InfoMoneyGroup_ObjectForm: TParentForm},
  Report_GoodsMI_Package in '..\..\Forms\Report\Report_GoodsMI_Package.pas' {Report_GoodsMI_PackageForm: TParentForm},
  Report_GoodsMI_ProductionUnion in '..\..\Forms\Report\Report_GoodsMI_ProductionUnion.pas' {Report_GoodsMI_ProductionUnionForm: TParentForm},
  GlobalConst in '..\..\FormsMeat\System\GlobalConst.pas' {GlobalConstForm: TParentForm},
  BankAccount_Personal in '..\..\Forms\Document\BankAccount_Personal.pas' {BankAccount_PersonalForm: TParentForm},
  BankAccount_PersonalJournal in '..\..\Forms\Document\BankAccount_PersonalJournal.pas' {BankAccount_PersonalJournalForm: TParentForm},
  Member_Container in '..\..\Forms\Guides\Member_Container.pas' {Member_ContainerForm: TParentForm},
  Member_Object in '..\..\Forms\Guides\Member_Object.pas' {Member_ObjectForm: TParentForm},
  GoodsPlatform in '..\..\Forms\Guides\GoodsPlatform.pas' {GoodsPlatformForm: TParentForm},
  GoodsPlatformEdit in '..\..\Forms\Guides\GoodsPlatformEdit.pas' {GoodsPlatformEditForm: TParentForm},
  dsdException in '..\..\SOURCE\dsdException.pas',
  Report_MotionGoodsDialog in '..\..\Forms\Report\Report_MotionGoodsDialog.pas' {Report_MotionGoodsDialogForm: TParentForm},
  COMTestUnit in '..\SOURCE\COM\COMTestUnit.pas',
  RouteGroup in '..\..\Forms\Guides\RouteGroup.pas' {RouteGroupForm: TParentForm},
  RouteGroupEdit in '..\..\Forms\Guides\RouteGroupEdit.pas' {RouteGroupEditForm: TParentForm},
  Report_GoodsMI_InternalDialog in '..\..\Forms\Report\Report_GoodsMI_InternalDialog.pas' {Report_GoodsMI_InternalDialogForm: TParentForm},
  Report_GoodsBalance in '..\..\Forms\Report\Report_GoodsBalance.pas' {Report_GoodsBalanceForm: TParentForm},
  Report_MotionGoodsUpak in '..\..\Forms\Report\Report_MotionGoodsUpak.pas' {Report_MotionGoodsUpakForm: TParentForm},
  MedocJournal in '..\..\Forms\Document\MedocJournal.pas' {MedocJournalForm: TParentForm},
  Report_MotionGoodsCeh in '..\..\Forms\Report\Report_MotionGoodsCeh.pas' {Report_MotionGoodsCehForm: TParentForm},
  Retail_PrintKindItem in '..\..\Forms\Guides\Retail_PrintKindItem.pas' {Retail_PrintKindItemForm: TParentForm},
  Juridical_PrintKindItem in '..\..\Forms\Guides\Juridical_PrintKindItem.pas' {Juridical_PrintKindItemForm: TParentForm},
  QualityDoc in '..\..\Forms\Document\QualityDoc.pas' {QualityDocForm: TParentForm},
  QualityDocJournal in '..\..\Forms\Document\QualityDocJournal.pas' {QualityDocJournalForm: TParentForm},
  Report_PersonalComplete in '..\..\Forms\Report\Report_PersonalComplete.pas' {Report_PersonalCompleteForm: TParentForm},
  Report_DefrosterDialog in '..\..\Forms\Report\Report_DefrosterDialog.pas' {Report_DefrosterDialogForm: TParentForm},
  TaxJournalDialog in '..\..\Forms\Document\TaxJournalDialog.pas' {TaxJournalDialogForm: TParentForm},
  Partner in '..\..\Forms\Guides\Partner.pas' {PartnerForm: TParentForm},
  Juridical in '..\..\Forms\Guides\Juridical.pas' {JuridicalForm: TParentForm},
  ContractChoicePartner in '..\..\Forms\Guides\ContractChoicePartner.pas' {ContractChoicePartnerForm: TParentForm},
  IncomePartionGoodsJournal in '..\..\Forms\Document\IncomePartionGoodsJournal.pas' {IncomePartionGoodsJournalForm: TParentForm},
  SaleJournalChoice in '..\..\Forms\Document\SaleJournalChoice.pas' {SaleJournalChoiceForm: TParentForm},
  OrderInternal in '..\..\Forms\Document\OrderInternal.pas' {OrderInternalForm: TParentForm},
  OrderInternalJournal in '..\..\Forms\Document\OrderInternalJournal.pas' {OrderInternalJournalForm: TParentForm},
  IncomeJournal in '..\..\Forms\Document\IncomeJournal.pas' {IncomeJournalForm: TParentForm},
  Income in '..\..\Forms\Document\Income.pas' {IncomeForm: TParentForm},
  WeighingProductionItemJournal in '..\..\Forms\Document\WeighingProductionItemJournal.pas' {WeighingProductionItemJournalForm: TParentForm},
  WeighingPartnerItemJournal in '..\..\Forms\Document\WeighingPartnerItemJournal.pas' {WeighingPartnerItemJournalForm: TParentForm},
  OrderInternalPack in '..\..\Forms\Document\OrderInternalPack.pas' {OrderInternalPackForm: TParentForm},
  OrderInternalPackJournal in '..\..\Forms\Document\OrderInternalPackJournal.pas' {OrderInternalPackJournalForm: TParentForm},
  ReturnOut in '..\..\Forms\Document\ReturnOut.pas' {ReturnOutForm: TParentForm},
  ReturnOutJournal in '..\..\Forms\Document\ReturnOutJournal.pas' {ReturnOutJournalForm: TParentForm},
  Report_GoodsMI_SaleReturnInUnit in '..\..\Forms\Report\Report_GoodsMI_SaleReturnInUnit.pas' {Report_GoodsMI_SaleReturnInUnitForm: TParentForm},
  Report_GoodsMI_SaleReturnIn in '..\..\Forms\Report\Report_GoodsMI_SaleReturnIn.pas' {Report_GoodsMI_SaleReturnInForm: TParentForm},
  Report_GoodsBalanceDialog in '..\..\Forms\Report\Report_GoodsBalanceDialog.pas' {Report_GoodsBalanceDialogForm: TParentForm},
  Report_GoodsMI_IncomeDialog in '..\..\Forms\Report\Report_GoodsMI_IncomeDialog.pas' {Report_GoodsMI_IncomeDialogForm: TParentForm},
  Report_GoodsMI_Income in '..\..\Forms\Report\Report_GoodsMI_Income.pas' {Report_GoodsMI_IncomeForm: TParentForm},
  Report_GoodsMI_Dialog in '..\..\Forms\Report\Report_GoodsMI_Dialog.pas' {Report_GoodsMI_DialogForm: TParentForm},
  Report_GoodsMI_Internal in '..\..\Forms\Report\Report_GoodsMI_Internal.pas' {Report_GoodsMI_InternalForm: TParentForm},
  Report_PersonalCompleteDialog in '..\..\Forms\Report\Report_PersonalCompleteDialog.pas' {Report_PersonalCompleteDialogForm: TParentForm},
  Report_ReceiptProductionAnalyze in '..\..\Forms\Report\Report_ReceiptProductionAnalyze.pas' {Report_ReceiptProductionAnalyzeForm: TParentForm};

{$R *.RES}
{$R DevExpressRus.res}

begin
  gc_AdminPassword := 'qsxqsxw1';
  Application.Initialize;
  gc_isSetDefault := true;
  Application.CreateForm(TdmMain, dmMain);
  Application.Run;
  DUnitTestRunner.RunRegisteredTests;
end.

