program ProjectBoatTest;

uses
  Forms,
  DUnitTestRunner,
  SysUtils,
  dbCreateStructureTest in '..\SOURCEBoat\STRUCTURE\dbCreateStructureTest.pas',
  dbMetadataTest in '..\SOURCEBoat\METADATA\dbMetadataTest.pas',
  dbProcedureTest in '..\SourceBoat\dbProcedureTest.pas',
  zLibUtil in '..\SOURCE\zLibUtil.pas',
  CommonFunctionTest in '..\SOURCEBoat\Function\CommonFunctionTest.pas',
  UtilConst in '..\SOURCEBoat\UtilConst.pas',
  dbEnumTest in '..\SOURCEBoat\dbEnumTest.pas',
  ProcessTest in '..\SOURCEBoat\Process\ProcessTest.pas',
  dbCreateViewTest in '..\SOURCEBoat\View\dbCreateViewTest.pas',
  DefaultsTest in '..\SOURCEBoat\Defaults\DefaultsTest.pas',
  CommonData in '..\..\SOURCE\CommonData.pas',
  Authentication in '..\..\SOURCE\Authentication.pas',
  FormStorage in '..\..\SOURCE\FormStorage.pas',
  ParentForm in '..\..\SOURCE\ParentForm.pas' {ParentForm},
  Storage in '..\..\SOURCE\Storage.pas',
  UtilConvert in '..\..\SOURCE\UtilConvert.pas',
  dsdAction in '..\..\SOURCE\COMPONENT\dsdAction.pas',
  dsdAddOn in '..\..\SOURCE\COMPONENT\dsdAddOn.pas',
  dsdDB in '..\..\SOURCE\COMPONENT\dsdDB.pas',
  dsdGuides in '..\..\SOURCE\COMPONENT\dsdGuides.pas',
  DataModul in '..\..\SOURCE\DataModul.pas' {dmMain: TDataModule},
  dbTest in '..\SOURCE\dbTest.pas',
  ChoicePeriod in '..\..\SOURCE\COMPONENT\ChoicePeriod.pas' {PeriodChoiceForm},
  Defaults in '..\..\SOURCE\COMPONENT\Defaults.pas',
  UnilWin in '..\..\SOURCE\UnilWin.pas',
  MessagesUnit in '..\..\SOURCE\MessagesUnit.pas' {MessagesForm},
  SimpleGauge in '..\..\SOURCE\SimpleGauge.pas' {SimpleGaugeForm},
  Document in '..\..\SOURCE\COMPONENT\Document.pas',
  Log in '..\..\SOURCE\Log.pas',
  ExternalData in '..\..\SOURCE\COMPONENT\ExternalData.pas',
  ExternalSave in '..\..\SOURCE\COMPONENT\ExternalSave.pas',
  VKDBFDataSet in '..\..\SOURCE\DBF\VKDBFDataSet.pas',
  VKDBFPrx in '..\..\SOURCE\DBF\VKDBFPrx.pas',
  VKDBFUtil in '..\..\SOURCE\DBF\VKDBFUtil.pas',
  VKDBFMemMgr in '..\..\SOURCE\DBF\VKDBFMemMgr.pas',
  VKDBFCrypt in '..\..\SOURCE\DBF\VKDBFCrypt.pas',
  VKDBFGostCrypt in '..\..\SOURCE\DBF\VKDBFGostCrypt.pas',
  VKDBFCDX in '..\..\SOURCE\DBF\VKDBFCDX.pas',
  VKDBFIndex in '..\..\SOURCE\DBF\VKDBFIndex.pas',
  VKDBFSorters in '..\..\SOURCE\DBF\VKDBFSorters.pas',
  VKDBFCollate in '..\..\SOURCE\DBF\VKDBFCollate.pas',
  VKDBFParser in '..\..\SOURCE\DBF\VKDBFParser.pas',
  VKDBFNTX in '..\..\SOURCE\DBF\VKDBFNTX.pas',
  VKDBFSortedList in '..\..\SOURCE\DBF\VKDBFSortedList.pas',
  ObjectTest in '..\SOURCEBoat\Objects\ObjectTest.pas',
  cxGridAddOn in '..\..\SOURCE\DevAddOn\cxGridAddOn.pas',
  AncestorBase in '..\..\Forms\Ancestor\AncestorBase.pas' {AncestorBaseForm: TParentForm},
  AncestorData in '..\..\Forms\Ancestor\AncestorData.pas' {AncestorDataForm: TParentForm},
  AncestorDBGrid in '..\..\Forms\Ancestor\AncestorDBGrid.pas' {AncestorDBGridForm: TParentForm},
  AncestorDialog in '..\..\Forms\Ancestor\AncestorDialog.pas' {AncestorDialogForm: TParentForm},
  AncestorDocument in '..\..\Forms\Ancestor\AncestorDocument.pas' {AncestorDocumentForm: TParentForm},
  AncestorDocumentMC in '..\..\Forms\Ancestor\AncestorDocumentMC.pas' {AncestorDocumentMCForm: TParentForm},
  AncestorEditDialog in '..\..\Forms\Ancestor\AncestorEditDialog.pas' {AncestorEditDialogForm: TParentForm},
  AncestorEnum in '..\..\Forms\Ancestor\AncestorEnum.pas' {AncestorEnumForm: TParentForm},
  AncestorGuides in '..\..\Forms\Ancestor\AncestorGuides.pas' {AncestorGuidesForm: TParentForm},
  AncestorJournal in '..\..\Forms\Ancestor\AncestorJournal.pas' {AncestorJournalForm: TParentForm},
  AboutBoxUnit in '..\..\SOURCE\AboutBoxUnit.pas' {AboutBox},
  UpdaterTest in '..\SOURCE\Component\UpdaterTest.pas',
  dbObjectTest in '..\SOURCE\dbObjectTest.pas',
  User in '..\..\FormsBoat\Guides\User.pas' {UserForm: TParentForm},
  UserEdit in '..\..\FormsBoat\Guides\UserEdit.pas' {UserEditForm: TParentForm},
  RoleTest in '..\SOURCEBoat\Objects\All\RoleTest.pas',
  UserTest in '..\SOURCEBoat\Objects\All\UserTest.pas',
  ParentFormTest in '..\SOURCE\Form\ParentFormTest.pas' {TestForm: TParentForm},
  Objects in '..\..\FormsBoat\Guides\Objects.pas' {ObjectForm: TParentForm},
  ObjectDesc in '..\..\FormsBoat\Guides\ObjectDesc.pas' {ObjectDescForm: TParentForm},
  ActionTest in '..\SOURCEBoat\Objects\All\ActionTest.pas',
  AncestorMain in '..\..\Forms\Ancestor\AncestorMain.pas' {AncestorMainForm},
  Protocol in '..\..\FormsBoat\Guides\Protocol.pas' {ProtocolForm: TParentForm},
  AncestorReport in '..\..\Forms\Ancestor\AncestorReport.pas' {AncestorReportForm: TParentForm},
  Vcl.Dialogs,
  dsdDataSetDataLink in '..\..\SOURCE\COMPONENT\dsdDataSetDataLink.pas',
  dsdException in '..\..\SOURCE\dsdException.pas',
  EDI in '..\..\SOURCE\EDI\EDI.pas',
  ComDocXML in '..\..\SOURCE\EDI\ComDocXML.pas',
  OrderXML in '..\..\SOURCE\EDI\OrderXML.pas',
  DeclarXML in '..\..\SOURCE\EDI\DeclarXML.pas',
  DesadvXML in '..\..\SOURCE\EDI\DesadvXML.pas',
  InvoiceXML in '..\..\SOURCE\EDI\InvoiceXML.pas',
  OrdrspXML in '..\..\SOURCE\EDI\OrdrspXML.pas',
  RecadvXML in '..\..\SOURCE\EDI\RecadvXML.pas',
  StatusXML in '..\..\SOURCE\EDI\StatusXML.pas',
  dsdInternetAction in '..\..\SOURCE\COMPONENT\dsdInternetAction.pas',
  LookAndFillSettings in '..\..\SOURCE\LookAndFillSettings.pas' {LookAndFillSettingsForm},
  dsdXMLTransform in '..\..\SOURCE\COMPONENT\dsdXMLTransform.pas',
  Role in '..\..\FormsBoat\Guides\Role.pas' {RoleForm: TParentForm},
  RoleEdit in '..\..\FormsBoat\Guides\RoleEdit.pas' {RoleEditForm: TParentForm},
  Action in '..\..\Forms\Action.pas' {ActionForm: TParentForm},
  UserProtocol in '..\..\FormsBoat\Guides\UserProtocol.pas' {UserProtocol: TParentForm},
  CommonContainerProcedureTest in '..\SOURCEBoat\Container\CommonContainerProcedureTest.pas',
  MovementDescForms in '..\..\FormsBoat\System\MovementDescForms.pas' {MovementDescDataForm: TParentForm},
  dsdPivotGrid in '..\..\SOURCE\COMPONENT\dsdPivotGrid.pas',
  dsdExportToXLSAction in '..\..\SOURCE\COMPONENT\dsdExportToXLSAction.pas',
  dsdExportToXMLAction in '..\..\SOURCE\COMPONENT\dsdExportToXMLAction.pas',
  ExternalLoad in '..\..\SOURCE\COMPONENT\ExternalLoad.pas',
  PUSHMessage in '..\..\SOURCE\COMPONENT\PUSHMessage.pas' {PUSHMessageForm},
  DesadvFozzXML in '..\..\SOURCE\EDI\DesadvFozzXML.pas',
  IftminFozzXML in '..\..\SOURCE\EDI\IftminFozzXML.pas',
  OrderSpFozzXML in '..\..\SOURCE\EDI\OrderSpFozzXML.pas',
  MainForm in '..\..\FormsBoat\MainForm.pas' {MainForm},
  dbProcedureBoatTest in '..\SOURCEBoat\dbProcedureBoatTest.pas',
  LoadBoatFormTest in '..\SOURCEBoat\LoadBoatFormTest.pas',
  LoadBoatReportTest in '..\SOURCEBoat\LoadBoatReportTest.pas',
  dsdTranslator in '..\..\SOURCE\COMPONENT\dsdTranslator.pas',
  MeDOC in '..\..\SOURCE\MeDOC\MeDOC.pas',
  IFIN_J1201009 in '..\..\SOURCE\MeDOC\IFIN_J1201009.pas',
  IFIN_J1201209 in '..\..\SOURCE\MeDOC\IFIN_J1201209.pas',
  Medoc_J1201010 in '..\..\SOURCE\MeDOC\Medoc_J1201010.pas',
  Medoc_J1201210 in '..\..\SOURCE\MeDOC\Medoc_J1201210.pas',
  MeDocXML in '..\..\SOURCE\MeDOC\MeDocXML.pas',
  Language in '..\..\FormsBoat\Guides\Language.pas' {LanguageForm: TParentForm},
  LanguageEdit in '..\..\FormsBoat\Guides\LanguageEdit.pas' {LanguageEditForm: TParentForm},
  TranslateWord in '..\..\FormsBoat\Guides\TranslateWord.pas' {TranslateWordForm: TParentForm},
  TranslateWordEdit in '..\..\FormsBoat\Guides\TranslateWordEdit.pas' {TranslateWordEditForm: TParentForm},
  Brand in '..\..\FormsBoat\Guides\Brand.pas' {BrandForm: TParentForm},
  BrandEdit in '..\..\FormsBoat\Guides\BrandEdit.pas' {BrandEditForm: TParentForm},
  ProdModelEdit in '..\..\FormsBoat\Guides\ProdModelEdit.pas' {ProdModelEditForm: TParentForm},
  ProdModel in '..\..\FormsBoat\Guides\ProdModel.pas' {ProdModelForm: TParentForm},
  ProdEngine in '..\..\FormsBoat\Guides\ProdEngine.pas' {ProdEngineForm: TParentForm},
  ProdEngineEdit in '..\..\FormsBoat\Guides\ProdEngineEdit.pas' {ProdEngineEditForm: TParentForm},
  ProdColorGroup in '..\..\FormsBoat\Guides\ProdColorGroup.pas' {ProdColorGroupForm: TParentForm},
  ProdOptions in '..\..\FormsBoat\Guides\ProdOptions.pas' {ProdOptionsForm: TParentForm},
  ProdColorGroupEdit in '..\..\FormsBoat\Guides\ProdColorGroupEdit.pas' {ProdColorGroupEditForm: TParentForm},
  ProdOptionsEdit in '..\..\FormsBoat\Guides\ProdOptionsEdit.pas' {ProdOptionsEditForm: TParentForm},
  ProdColor in '..\..\FormsBoat\Guides\ProdColor.pas' {ProdColorForm: TParentForm},
  ProdColorEdit in '..\..\FormsBoat\Guides\ProdColorEdit.pas' {ProdColorEditForm: TParentForm},
  Product in '..\..\FormsBoat\Guides\Product.pas' {ProductForm: TParentForm},
  ProductEdit in '..\..\FormsBoat\Guides\ProductEdit.pas' {ProductEditForm: TParentForm},
  ImportSettings in '..\..\FormsBoat\Import\ImportSettings.pas' {ImportSettingsForm: TParentForm},
  ImportType in '..\..\FormsBoat\Import\ImportType.pas' {ImportTypeForm: TParentForm},
  ProdOptItems in '..\..\FormsBoat\Guides\ProdOptItems.pas' {ProdColorItemsForm: TParentForm},
  ProdOptItemsEdit in '..\..\FormsBoat\Guides\ProdOptItemsEdit.pas' {ProdOptItemsEditForm: TParentForm},
  ProdColorItemsEdit in '..\..\FormsBoat\Guides\ProdColorItemsEdit.pas' {ProdColorItemsEditForm: TParentForm},
  ProdColorItems1 in '..\..\FormsBoat\Guides\ProdColorItems1.pas' {ProdColorItems1Form: TParentForm},
  ProdOptPattern in '..\..\FormsBoat\Guides\ProdOptPattern.pas' {ProdOptPatternForm: TParentForm},
  ProdOptPatternEdit in '..\..\FormsBoat\Guides\ProdOptPatternEdit.pas' {ProdOptPatternEditForm: TParentForm},
  ProdColorPatternEdit in '..\..\FormsBoat\Guides\ProdColorPatternEdit.pas' {ProdColorPatternEditForm: TParentForm},
  ProdColorPattern in '..\..\FormsBoat\Guides\ProdColorPattern.pas' {ProdColorPatternForm: TParentForm};

{$R *.res}
{$R DevExpressRus.res}

begin
  ConnectionPath := '..\INIT\ProjectBoat.php';
  EnumPath := '..\DATABASE\Boat\METADATA\Enum\';
  CreateStructurePath := '..\DATABASE\Boat\STRUCTURE\';
  LocalViewPath := '..\DATABASE\Boat\View\';
  LocalProcedurePath := '..\DATABASE\Boat\PROCEDURE\';
  LocalProcessPath := '..\DATABASE\Boat\PROCESS\';

  dsdProject := prBoat;

  if FindCmdLineSwitch('realProjectBoat', true)
  then gc_AdminPassword := 'qsxqsxw1'
  else gc_AdminPassword := 'Админ';

  gc_ProgramName := 'ProjectBoat.exe';

  Application.Initialize;
  gc_isSetDefault := true;
  Application.CreateForm(TdmMain, dmMain);
  Application.Run;
  DUnitTestRunner.RunRegisteredTests;
end.
