program ProjectBoatTest;

uses
  Forms,
  DUnitTestRunner,
  SysUtils,
  dbCreateStructureTest in '..\SOURCEBoat\STRUCTURE\dbCreateStructureTest.pas',
  dbMetadataTest in '..\SOURCEBoat\METADATA\dbMetadataTest.pas',
  dbProcedureTest in '..\SourceBoat\dbProcedureTest.pas',
  zLibUtil in '..\SOURCE\zLibUtil.pas',
  CommonFunctionTest in '..\SOURCEBoat\Function\CommonFunctionTest.pas',
  UtilConst in '..\SOURCEBoat\UtilConst.pas',
  dbEnumTest in '..\SOURCEBoat\dbEnumTest.pas',
  ProcessTest in '..\SOURCEBoat\Process\ProcessTest.pas',
  dbCreateViewTest in '..\SOURCEBoat\View\dbCreateViewTest.pas',
  DefaultsTest in '..\SOURCEBoat\Defaults\DefaultsTest.pas',
  CommonData in '..\..\SOURCE\CommonData.pas',
  Authentication in '..\..\SOURCE\Authentication.pas',
  FormStorage in '..\..\SOURCE\FormStorage.pas',
  ParentForm in '..\..\SOURCE\ParentForm.pas' {ParentForm},
  Storage in '..\..\SOURCE\Storage.pas',
  UtilConvert in '..\..\SOURCE\UtilConvert.pas',
  dsdAction in '..\..\SOURCE\COMPONENT\dsdAction.pas',
  dsdDB in '..\..\SOURCE\COMPONENT\dsdDB.pas',
  dsdGuides in '..\..\SOURCE\COMPONENT\dsdGuides.pas',
  DataModul in '..\..\SOURCE\DataModul.pas' {dmMain: TDataModule},
  dbTest in '..\SOURCE\dbTest.pas',
  ChoicePeriod in '..\..\SOURCE\COMPONENT\ChoicePeriod.pas' {PeriodChoiceForm},
  Defaults in '..\..\SOURCE\COMPONENT\Defaults.pas',
  UnilWin in '..\..\SOURCE\UnilWin.pas',
  MessagesUnit in '..\..\SOURCE\MessagesUnit.pas' {MessagesForm},
  SimpleGauge in '..\..\SOURCE\SimpleGauge.pas' {SimpleGaugeForm},
  Document in '..\..\SOURCE\COMPONENT\Document.pas',
  Log in '..\..\SOURCE\Log.pas',
  ExternalData in '..\..\SOURCE\COMPONENT\ExternalData.pas',
  ExternalSave in '..\..\SOURCE\COMPONENT\ExternalSave.pas',
  VKDBFDataSet in '..\..\SOURCE\DBF\VKDBFDataSet.pas',
  VKDBFPrx in '..\..\SOURCE\DBF\VKDBFPrx.pas',
  VKDBFUtil in '..\..\SOURCE\DBF\VKDBFUtil.pas',
  VKDBFMemMgr in '..\..\SOURCE\DBF\VKDBFMemMgr.pas',
  VKDBFCrypt in '..\..\SOURCE\DBF\VKDBFCrypt.pas',
  VKDBFGostCrypt in '..\..\SOURCE\DBF\VKDBFGostCrypt.pas',
  VKDBFCDX in '..\..\SOURCE\DBF\VKDBFCDX.pas',
  VKDBFIndex in '..\..\SOURCE\DBF\VKDBFIndex.pas',
  VKDBFSorters in '..\..\SOURCE\DBF\VKDBFSorters.pas',
  VKDBFCollate in '..\..\SOURCE\DBF\VKDBFCollate.pas',
  VKDBFParser in '..\..\SOURCE\DBF\VKDBFParser.pas',
  VKDBFNTX in '..\..\SOURCE\DBF\VKDBFNTX.pas',
  VKDBFSortedList in '..\..\SOURCE\DBF\VKDBFSortedList.pas',
  ObjectTest in '..\SOURCEBoat\Objects\ObjectTest.pas',
  cxGridAddOn in '..\..\SOURCE\DevAddOn\cxGridAddOn.pas',
  AncestorBase in '..\..\Forms\Ancestor\AncestorBase.pas' {AncestorBaseForm: TParentForm},
  AncestorData in '..\..\Forms\Ancestor\AncestorData.pas' {AncestorDataForm: TParentForm},
  AncestorDBGrid in '..\..\Forms\Ancestor\AncestorDBGrid.pas' {AncestorDBGridForm: TParentForm},
  AncestorDialog in '..\..\Forms\Ancestor\AncestorDialog.pas' {AncestorDialogForm: TParentForm},
  AncestorDocument in '..\..\Forms\Ancestor\AncestorDocument.pas' {AncestorDocumentForm: TParentForm},
  AncestorDocumentMC in '..\..\Forms\Ancestor\AncestorDocumentMC.pas' {AncestorDocumentMCForm: TParentForm},
  AncestorEditDialog in '..\..\Forms\Ancestor\AncestorEditDialog.pas' {AncestorEditDialogForm: TParentForm},
  AncestorEnum in '..\..\Forms\Ancestor\AncestorEnum.pas' {AncestorEnumForm: TParentForm},
  AncestorGuides in '..\..\Forms\Ancestor\AncestorGuides.pas' {AncestorGuidesForm: TParentForm},
  AncestorJournal in '..\..\Forms\Ancestor\AncestorJournal.pas' {AncestorJournalForm: TParentForm},
  AboutBoxUnit in '..\..\SOURCE\AboutBoxUnit.pas' {AboutBox},
  UpdaterTest in '..\SOURCE\Component\UpdaterTest.pas',
  dbObjectTest in '..\SOURCE\dbObjectTest.pas',
  User in '..\..\FormsBoat\Guides\User.pas' {UserForm: TParentForm},
  UserEdit in '..\..\FormsBoat\Guides\UserEdit.pas' {UserEditForm: TParentForm},
  RoleTest in '..\SOURCEBoat\Objects\All\RoleTest.pas',
  UserTest in '..\SOURCEBoat\Objects\All\UserTest.pas',
  ParentFormTest in '..\SOURCE\Form\ParentFormTest.pas' {TestForm: TParentForm},
  Objects in '..\..\FormsBoat\Guides\Objects.pas' {ObjectForm: TParentForm},
  ObjectDesc in '..\..\FormsBoat\Guides\ObjectDesc.pas' {ObjectDescForm: TParentForm},
  ActionTest in '..\SOURCEBoat\Objects\All\ActionTest.pas',
  AncestorMain in '..\..\Forms\Ancestor\AncestorMain.pas' {AncestorMainForm},
  Protocol in '..\..\FormsBoat\Guides\Protocol.pas' {ProtocolForm: TParentForm},
  AncestorReport in '..\..\Forms\Ancestor\AncestorReport.pas' {AncestorReportForm: TParentForm},
  Vcl.Dialogs,
  dsdDataSetDataLink in '..\..\SOURCE\COMPONENT\dsdDataSetDataLink.pas',
  dsdException in '..\..\SOURCE\dsdException.pas',
  EDI in '..\..\SOURCE\EDI\EDI.pas',
  ComDocXML in '..\..\SOURCE\EDI\ComDocXML.pas',
  OrderXML in '..\..\SOURCE\EDI\OrderXML.pas',
  DeclarXML in '..\..\SOURCE\EDI\DeclarXML.pas',
  DesadvXML in '..\..\SOURCE\EDI\DesadvXML.pas',
  InvoiceXML in '..\..\SOURCE\EDI\InvoiceXML.pas',
  OrdrspXML in '..\..\SOURCE\EDI\OrdrspXML.pas',
  RecadvXML in '..\..\SOURCE\EDI\RecadvXML.pas',
  StatusXML in '..\..\SOURCE\EDI\StatusXML.pas',
  dsdInternetAction in '..\..\SOURCE\COMPONENT\dsdInternetAction.pas',
  LookAndFillSettings in '..\..\SOURCE\LookAndFillSettings.pas' {LookAndFillSettingsForm},
  dsdXMLTransform in '..\..\SOURCE\COMPONENT\dsdXMLTransform.pas',
  Role in '..\..\FormsBoat\Guides\Role.pas' {RoleForm: TParentForm},
  RoleEdit in '..\..\FormsBoat\Guides\RoleEdit.pas' {RoleEditForm: TParentForm},
  Action in '..\..\Forms\Action.pas' {ActionForm: TParentForm},
  UserProtocol in '..\..\FormsBoat\Guides\UserProtocol.pas' {UserProtocol: TParentForm},
  CommonContainerProcedureTest in '..\SOURCEBoat\Container\CommonContainerProcedureTest.pas',
  MovementDescForms in '..\..\FormsBoat\System\MovementDescForms.pas' {MovementDescDataForm: TParentForm},
  dsdPivotGrid in '..\..\SOURCE\COMPONENT\dsdPivotGrid.pas',
  dsdExportToXLSAction in '..\..\SOURCE\COMPONENT\dsdExportToXLSAction.pas',
  dsdExportToXMLAction in '..\..\SOURCE\COMPONENT\dsdExportToXMLAction.pas',
  ExternalLoad in '..\..\SOURCE\COMPONENT\ExternalLoad.pas',
  PUSHMessage in '..\..\SOURCE\COMPONENT\PUSHMessage.pas' {PUSHMessageForm},
  DesadvFozzXML in '..\..\SOURCE\EDI\DesadvFozzXML.pas',
  IftminFozzXML in '..\..\SOURCE\EDI\IftminFozzXML.pas',
  OrderSpFozzXML in '..\..\SOURCE\EDI\OrderSpFozzXML.pas',
  MainForm in '..\..\FormsBoat\MainForm.pas' {MainForm},
  dbProcedureBoatTest in '..\SOURCEBoat\dbProcedureBoatTest.pas',
  LoadBoatFormTest in '..\SOURCEBoat\LoadBoatFormTest.pas',
  LoadBoatReportTest in '..\SOURCEBoat\LoadBoatReportTest.pas',
  dsdTranslator in '..\..\SOURCE\COMPONENT\dsdTranslator.pas',
  MeDOC in '..\..\SOURCE\MeDOC\MeDOC.pas',
  IFIN_J1201009 in '..\..\SOURCE\MeDOC\IFIN_J1201009.pas',
  IFIN_J1201209 in '..\..\SOURCE\MeDOC\IFIN_J1201209.pas',
  Medoc_J1201010 in '..\..\SOURCE\MeDOC\Medoc_J1201010.pas',
  Medoc_J1201210 in '..\..\SOURCE\MeDOC\Medoc_J1201210.pas',
  MeDocXML in '..\..\SOURCE\MeDOC\MeDocXML.pas',
  Language in '..\..\FormsBoat\Guides\Language.pas' {LanguageForm: TParentForm},
  LanguageEdit in '..\..\FormsBoat\Guides\LanguageEdit.pas' {LanguageEditForm: TParentForm},
  TranslateWord in '..\..\FormsBoat\Guides\TranslateWord.pas' {TranslateWordForm: TParentForm},
  TranslateWordEdit in '..\..\FormsBoat\Guides\TranslateWordEdit.pas' {TranslateWordEditForm: TParentForm},
  Brand in '..\..\FormsBoat\Guides\Brand.pas' {BrandForm: TParentForm},
  BrandEdit in '..\..\FormsBoat\Guides\BrandEdit.pas' {BrandEditForm: TParentForm},
  ProdModelEdit in '..\..\FormsBoat\Guides\ProdModelEdit.pas' {ProdModelEditForm: TParentForm},
  ProdModel in '..\..\FormsBoat\Guides\ProdModel.pas' {ProdModelForm: TParentForm},
  ProdEngine in '..\..\FormsBoat\Guides\ProdEngine.pas' {ProdEngineForm: TParentForm},
  ProdEngineEdit in '..\..\FormsBoat\Guides\ProdEngineEdit.pas' {ProdEngineEditForm: TParentForm},
  ProdColorGroup in '..\..\FormsBoat\Guides\ProdColorGroup.pas' {ProdColorGroupForm: TParentForm},
  ProdOptions in '..\..\FormsBoat\Guides\ProdOptions.pas' {ProdOptionsForm: TParentForm},
  ProdColorGroupEdit in '..\..\FormsBoat\Guides\ProdColorGroupEdit.pas' {ProdColorGroupEditForm: TParentForm},
  ProdOptionsEdit in '..\..\FormsBoat\Guides\ProdOptionsEdit.pas' {ProdOptionsEditForm: TParentForm},
  ProdColor_goods in '..\..\FormsBoat\Guides\ProdColor_goods.pas' {ProdColor_goodsForm: TParentForm},
  ProdColorEdit in '..\..\FormsBoat\Guides\ProdColorEdit.pas' {ProdColorEditForm: TParentForm},
  Product in '..\..\FormsBoat\Guides\Product.pas' {ProductForm: TParentForm},
  ProductEdit in '..\..\FormsBoat\Guides\ProductEdit.pas' {ProductEditForm: TParentForm},
  ImportSettings in '..\..\FormsBoat\Import\ImportSettings.pas' {ImportSettingsForm: TParentForm},
  ImportType in '..\..\FormsBoat\Import\ImportType.pas' {ImportTypeForm: TParentForm},
  ProdOptItemsEdit in '..\..\FormsBoat\Guides\ProdOptItemsEdit.pas' {ProdOptItemsEditForm: TParentForm},
  ProdColorItemsEdit in '..\..\FormsBoat\Guides\ProdColorItemsEdit.pas' {ProdColorItemsEditForm: TParentForm},
  ProdOptPattern in '..\..\FormsBoat\Guides\ProdOptPattern.pas' {ProdOptPatternForm: TParentForm},
  ProdOptPatternEdit in '..\..\FormsBoat\Guides\ProdOptPatternEdit.pas' {ProdOptPatternEditForm: TParentForm},
  ProdColorPatternEdit in '..\..\FormsBoat\Guides\ProdColorPatternEdit.pas' {ProdColorPatternEditForm: TParentForm},
  ProdColorPattern in '..\..\FormsBoat\Guides\ProdColorPattern.pas' {ProdColorPatternForm: TParentForm},
  ProdColorItems in '..\..\FormsBoat\Guides\ProdColorItems.pas' {ProdColorItemsForm: TParentForm},
  ProdOptItems in '..\..\FormsBoat\Guides\ProdOptItems.pas' {ProdOptItemsForm: TParentForm},
  Units in '..\..\FormsBoat\Guides\Units.pas' {UnitForm: TParentForm},
  UnitEdit in '..\..\FormsBoat\Guides\UnitEdit.pas' {UnitEditForm: TParentForm},
  Unit_Object in '..\..\FormsBoat\Guides\Unit_Object.pas' {Unit_ObjectForm: TParentForm},
  MemberEdit in '..\..\FormsBoat\Guides\MemberEdit.pas' {MemberEditForm: TParentForm},
  Member in '..\..\FormsBoat\Guides\Member.pas' {MemberForm: TParentForm},
  Client in '..\..\FormsBoat\Guides\Client.pas' {ClientForm: TParentForm},
  ClientEdit in '..\..\FormsBoat\Guides\ClientEdit.pas' {ClientEditForm: TParentForm},
  Partner in '..\..\FormsBoat\Guides\Partner.pas' {PartnerForm: TParentForm},
  PartnerEdit in '..\..\FormsBoat\Guides\PartnerEdit.pas' {PartnerEditForm: TParentForm},
  Position in '..\..\FormsBoat\Guides\Position.pas' {PositionForm: TParentForm},
  PositionEdit in '..\..\FormsBoat\Guides\PositionEdit.pas' {PositionEditForm: TParentForm},
  PersonalEdit in '..\..\FormsBoat\Guides\PersonalEdit.pas' {PersonalEditForm: TParentForm},
  Personal_Object in '..\..\FormsBoat\Guides\Personal_Object.pas' {Personal_ObjectForm: TParentForm},
  Personal in '..\..\FormsBoat\Guides\Personal.pas' {PersonalForm: TParentForm},
  CountryEdit in '..\..\FormsBoat\Guides\CountryEdit.pas' {CountryEditForm: TParentForm},
  Country in '..\..\FormsBoat\Guides\Country.pas' {CountryForm: TParentForm},
  PLZ in '..\..\FormsBoat\Guides\PLZ.pas' {PLZForm: TParentForm},
  PLZEdit in '..\..\FormsBoat\Guides\PLZEdit.pas' {PLZEditForm: TParentForm},
  ModelEtiketenEdit in '..\..\FormsBoat\Guides\ModelEtiketenEdit.pas' {ModelEtiketenEditForm: TParentForm},
  ModelEtiketen in '..\..\FormsBoat\Guides\ModelEtiketen.pas' {ModelEtiketenForm: TParentForm},
  InfoMoney in '..\..\FormsBoat\Guides\InfoMoney.pas' {InfoMoneyForm: TParentForm},
  InfoMoney_Object in '..\..\FormsBoat\Guides\InfoMoney_Object.pas' {InfoMoney_ObjectForm: TParentForm},
  InfoMoneyEdit in '..\..\FormsBoat\Guides\InfoMoneyEdit.pas' {InfoMoneyEditForm: TParentForm},
  GoodsGroup in '..\..\FormsBoat\Guides\GoodsGroup.pas' {GoodsGroupForm: TParentForm},
  GoodsGroup_Object in '..\..\FormsBoat\Guides\GoodsGroup_Object.pas' {GoodsGroup_ObjectForm: TParentForm},
  GoodsGroupEdit in '..\..\FormsBoat\Guides\GoodsGroupEdit.pas' {GoodsGroupEditForm: TParentForm},
  InfoMoneyGroupEdit in '..\..\FormsBoat\Guides\InfoMoneyGroupEdit.pas' {InfoMoneyGroupEditForm: TParentForm},
  InfoMoneyGroup in '..\..\FormsBoat\Guides\InfoMoneyGroup.pas' {InfoMoneyGroupForm: TParentForm},
  InfoMoneyGroup_Object in '..\..\FormsBoat\Guides\InfoMoneyGroup_Object.pas' {InfoMoneyGroup_ObjectForm: TParentForm},
  InfoMoneyDestination_Object in '..\..\FormsBoat\Guides\InfoMoneyDestination_Object.pas' {InfoMoneyDestination_ObjectForm: TParentForm},
  InfoMoneyDestinationEdit in '..\..\FormsBoat\Guides\InfoMoneyDestinationEdit.pas' {InfoMoneyDestinationEditForm: TParentForm},
  InfoMoneyDestination in '..\..\FormsBoat\Guides\InfoMoneyDestination.pas' {InfoMoneyDestinationForm: TParentForm},
  Bank in '..\..\FormsBoat\Guides\Bank.pas' {BankForm: TParentForm},
  BankEdit in '..\..\FormsBoat\Guides\BankEdit.pas' {BankEditForm: TParentForm},
  Measure in '..\..\FormsBoat\Guides\Measure.pas' {MeasureForm: TParentForm},
  MeasureEdit in '..\..\FormsBoat\Guides\MeasureEdit.pas' {MeasureEditForm: TParentForm},
  GoodsTypeEdit in '..\..\FormsBoat\Guides\GoodsTypeEdit.pas' {GoodsTypeEditForm: TParentForm},
  GoodsType in '..\..\FormsBoat\Guides\GoodsType.pas' {GoodsTypeForm: TParentForm},
  GoodsTag in '..\..\FormsBoat\Guides\GoodsTag.pas' {GoodsTagForm: TParentForm},
  GoodsTagEdit in '..\..\FormsBoat\Guides\GoodsTagEdit.pas' {GoodsTagEditForm: TParentForm},
  GoodsSize in '..\..\FormsBoat\Guides\GoodsSize.pas' {GoodsSizeForm: TParentForm},
  GoodsSizeEdit in '..\..\FormsBoat\Guides\GoodsSizeEdit.pas' {GoodsSizeEditForm: TParentForm},
  DiscountParner in '..\..\FormsBoat\Guides\DiscountParner.pas' {DiscountParnerForm: TParentForm},
  DiscountParnerEdit in '..\..\FormsBoat\Guides\DiscountParnerEdit.pas' {DiscountParnerEditForm: TParentForm},
  Goods in '..\..\FormsBoat\Guides\Goods.pas' {GoodsForm: TParentForm},
  GoodsEdit in '..\..\FormsBoat\Guides\GoodsEdit.pas' {GoodsEditForm: TParentForm},
  GoodsTree in '..\..\FormsBoat\Guides\GoodsTree.pas' {GoodsTreeForm: TParentForm},
  PriceList in '..\..\FormsBoat\Guides\PriceList.pas' {PriceListForm: TParentForm},
  PriceList_Object in '..\..\FormsBoat\Guides\PriceList_Object.pas' {PriceList_ObjectForm: TParentForm},
  PriceListEdit in '..\..\FormsBoat\Guides\PriceListEdit.pas' {PriceListEditForm: TParentForm},
  PriceListGoodsItem in '..\..\FormsBoat\Guides\PriceListGoodsItem.pas' {PriceListGoodsItemForm: TParentForm},
  PriceListGoodsItemEdit in '..\..\FormsBoat\Guides\PriceListGoodsItemEdit.pas' {PriceListGoodsItemEditForm: TParentForm},
  PriceListItem in '..\..\FormsBoat\Guides\PriceListItem.pas' {PriceListItemForm: TParentForm},
  TaxKind in '..\..\FormsBoat\Kind\TaxKind.pas' {TaxKindForm: TParentForm},
  dsdAddOn in '..\..\SOURCE\COMPONENT\dsdAddOn.pas',
  ReceiptProdModelEdit in '..\..\FormsBoat\Guides\ReceiptProdModelEdit.pas' {ReceiptProdModelEditForm: TParentForm},
  ReceiptGoodsEdit in '..\..\FormsBoat\Guides\ReceiptGoodsEdit.pas' {ReceiptGoodsEditForm: TParentForm},
  ReceiptGoods in '..\..\FormsBoat\Guides\ReceiptGoods.pas' {ReceiptGoodsForm: TParentForm},
  ProdColorKind in '..\..\FormsBoat\Kind\ProdColorKind.pas' {ProdColorKindForm: TParentForm},
  ColorPattern in '..\..\FormsBoat\Guides\ColorPattern.pas' {ColorPatternForm: TParentForm},
  ColorPatternEdit in '..\..\FormsBoat\Guides\ColorPatternEdit.pas' {ColorPatternEditForm: TParentForm},
  ReceiptLevel in '..\..\FormsBoat\Guides\ReceiptLevel.pas' {ReceiptLevelForm: TParentForm},
  ReceiptLevelEdit in '..\..\FormsBoat\Guides\ReceiptLevelEdit.pas' {ReceiptLevelEditForm: TParentForm},
  ReceiptService in '..\..\FormsBoat\Guides\ReceiptService.pas' {ReceiptServiceForm: TParentForm},
  ReceiptServiceEdit in '..\..\FormsBoat\Guides\ReceiptServiceEdit.pas' {ReceiptServiceEditForm: TParentForm},
  Union_Goods_ReceiptService in '..\..\FormsBoat\Guides\Union_Goods_ReceiptService.pas' {Union_Goods_ReceiptServiceForm: TParentForm},
  ReceiptProdModel in '..\..\FormsBoat\Guides\ReceiptProdModel.pas' {ReceiptProdModelForm: TParentForm},
  TranslateMessage in '..\..\FormsBoat\Guides\TranslateMessage.pas' {TranslateMessageForm: TParentForm},
  ProdColor in '..\..\FormsBoat\Guides\ProdColor.pas' {ProdColorForm: TParentForm},
  Movement_PeriodDialog in '..\..\FormsBoat\Document\Movement_PeriodDialog.pas' {Movement_PeriodDialogForm: TParentForm},
  Invoice in '..\..\FormsBoat\Document\Invoice.pas' {InvoiceForm: TParentForm},
  PaidKind in '..\..\FormsBoat\Kind\PaidKind.pas' {PaidKindForm: TParentForm},
  Union_ClientPartner in '..\..\FormsBoat\Guides\Union_ClientPartner.pas' {Union_ClientPartnerForm: TParentForm},
  BankAccount in '..\..\FormsBoat\Guides\BankAccount.pas' {BankAccountForm: TParentForm},
  BankAccountEdit in '..\..\FormsBoat\Guides\BankAccountEdit.pas' {BankAccountEditForm: TParentForm},
  Currency in '..\..\FormsBoat\Guides\Currency.pas' {CurrencyForm: TParentForm},
  Currency_Object in '..\..\FormsBoat\Guides\Currency_Object.pas' {Currency_ObjectForm: TParentForm},
  CurrencyEdit in '..\..\FormsBoat\Guides\CurrencyEdit.pas' {CurrencyEditForm: TParentForm},
  MoneyPlace_Object in '..\..\FormsBoat\Guides\MoneyPlace_Object.pas' {MoneyPlace_ObjectForm: TParentForm},
  BankAccountJournal in '..\..\FormsBoat\Document\BankAccountJournal.pas' {BankAccountJournalForm: TParentForm},
  BankAccountMovement in '..\..\FormsBoat\Document\BankAccountMovement.pas' {BankAccountMovementForm: TParentForm},
  InvoiceJournalChoice in '..\..\FormsBoat\Document\InvoiceJournalChoice.pas' {InvoiceJournalChoiceForm: TParentForm},
  Income in '..\..\FormsBoat\Document\Income.pas' {IncomeForm: TParentForm},
  IncomeJournal in '..\..\FormsBoat\Document\IncomeJournal.pas' {IncomeJournalForm: TParentForm},
  IncomeJournalChoice in '..\..\FormsBoat\Document\IncomeJournalChoice.pas' {IncomeJournalChoiceForm: TParentForm},
  TaxKindEdit in '..\..\FormsBoat\Kind\TaxKindEdit.pas' {TaxKindEditForm: TParentForm},
  OrderClientJournal in '..\..\FormsBoat\Document\OrderClientJournal.pas' {OrderClientJournalForm: TParentForm},
  Medoc_J1201011 in '..\..\SOURCE\MeDOC\Medoc_J1201011.pas',
  Medoc_J1201211 in '..\..\SOURCE\MeDOC\Medoc_J1201211.pas',
  IncomeCostJournal in '..\..\FormsBoat\Document\IncomeCostJournal.pas' {IncomeCostJournalForm: TParentForm},
  IncomeCost in '..\..\FormsBoat\Document\IncomeCost.pas' {IncomeCostForm: TParentForm},
  CostJournalChoice in '..\..\FormsBoat\Document\CostJournalChoice.pas' {CostJournalChoiceForm: TParentForm},
  Account in '..\..\FormsBoat\Guides\Account.pas' {AccountForm: TParentForm},
  AccountEdit in '..\..\FormsBoat\Guides\AccountEdit.pas' {AccountEditForm: TParentForm},
  AccountDirection in '..\..\FormsBoat\Guides\AccountDirection.pas' {AccountDirectionForm: TParentForm},
  AccountDirectionEdit in '..\..\FormsBoat\Guides\AccountDirectionEdit.pas' {AccountDirectionEditForm: TParentForm},
  AccountGroup in '..\..\FormsBoat\Guides\AccountGroup.pas' {AccountGroupForm: TParentForm},
  AccountGroupEdit in '..\..\FormsBoat\Guides\AccountGroupEdit.pas' {AccountGroupEditForm: TParentForm},
  MovementItemContainer in '..\..\FormsBoat\Document\MovementItemContainer.pas' {MovementItemContainerForm: TParentForm},
  Report_Balance in '..\..\FormsBoat\Report\Report_Balance.pas' {Report_BalanceForm: TParentForm},
  Report_BalanceDialog in '..\..\FormsBoat\Report\Report_BalanceDialog.pas' {Report_BalanceDialogForm: TParentForm},
  Report_Goods_RemainsCurrentDialog in '..\..\FormsBoat\Report\Report_Goods_RemainsCurrentDialog.pas' {Report_Goods_RemainsCurrentDialogForm: TParentForm},
  Report_Goods_RemainsCurrent in '..\..\FormsBoat\Report\Report_Goods_RemainsCurrent.pas' {Report_Goods_RemainsCurrentForm: TParentForm},
  InvoiceJournal in '..\..\FormsBoat\Document\InvoiceJournal.pas' {InvoiceJournalForm: TParentForm},
  BankAccountJournalByInvoice in '..\..\FormsBoat\Document\BankAccountJournalByInvoice.pas' {BankAccountJournalByInvoiceForm: TParentForm},
  OrderClient in '..\..\FormsBoat\Document\OrderClient.pas' {OrderClientForm: TParentForm},
  Medoc_J1201012 in '..\..\SOURCE\MeDOC\Medoc_J1201012.pas',
  Medoc_J1201212 in '..\..\SOURCE\MeDOC\Medoc_J1201212.pas',
  MovementProtocol in '..\..\FormsBoat\System\MovementProtocol.pas' {MovementProtocolForm: TParentForm},
  MovementItemProtocol in '..\..\FormsBoat\System\MovementItemProtocol.pas' {MovementItemProtocolForm: TParentForm},
  MovementProtocol_Info in '..\..\FormsBoat\System\MovementProtocol_Info.pas' {MovementProtocol_InfoForm: TParentForm},
  Report_MovementIncome in '..\..\FormsBoat\Report\Report_MovementIncome.pas' {Report_MovementIncomeForm: TParentForm},
  Report_MovementIncomeDialog in '..\..\FormsBoat\Report\Report_MovementIncomeDialog.pas' {Report_MovementIncomeDialogForm: TParentForm},
  Union_OrderJournalChoice in '..\..\FormsBoat\Document\Union_OrderJournalChoice.pas' {Union_OrderJournalChoiceForm: TParentForm},
  Report_GoodsDialog in '..\..\FormsBoat\Report\Report_GoodsDialog.pas' {Report_GoodsDialogForm: TParentForm},
  Report_Goods in '..\..\FormsBoat\Report\Report_Goods.pas' {Report_GoodsForm: TParentForm},
  PartionGoodsChoice in '..\..\FormsBoat\Guides\PartionGoodsChoice.pas' {PartionGoodsChoiceForm: TParentForm},
  OrderPartner in '..\..\FormsBoat\Document\OrderPartner.pas' {OrderPartnerForm: TParentForm},
  OrderPartnerJournal in '..\..\FormsBoat\Document\OrderPartnerJournal.pas' {OrderPartnerJournalForm: TParentForm},
  Report_OrderClientDialog in '..\..\FormsBoat\Report\Report_OrderClientDialog.pas' {Report_OrderClientDialogForm: TParentForm},
  Report_OrderClient in '..\..\FormsBoat\Report\Report_OrderClient.pas' {Report_OrderClientForm: TParentForm},
  OrderClientJournalChoice in '..\..\FormsBoat\Document\OrderClientJournalChoice.pas' {OrderClientJournalChoiceForm: TParentForm},
  DocTag in '..\..\FormsBoat\Guides\DocTag.pas' {DocTagForm: TParentForm},
  DocTagEdit in '..\..\FormsBoat\Guides\DocTagEdit.pas' {DocTagEditForm: TParentForm},
  ProductDocumentPhotoEdit in '..\..\FormsBoat\Guides\ProductDocumentPhotoEdit.pas' {ProductDocumentPhotoEditForm: TParentForm},
  IncomeCostJournalByInvoice in '..\..\FormsBoat\Document\IncomeCostJournalByInvoice.pas' {IncomeCostJournalByInvoiceForm: TParentForm},
  OrderClientJournalReserve in '..\..\FormsBoat\Document\OrderClientJournalReserve.pas' {OrderClientJournalReserveForm: TParentForm};

{$R *.res}
{$R DevExpressRus.res}

begin
  ConnectionPath := '..\INIT\Boat_init.php';
  EnumPath := '..\DATABASE\Boat\METADATA\Enum\';
  CreateStructurePath := '..\DATABASE\Boat\STRUCTURE\';
  LocalViewPath := '..\DATABASE\Boat\View\';
  LocalProcedurePath := '..\DATABASE\Boat\PROCEDURE\';
  LocalProcessPath := '..\DATABASE\Boat\PROCESS\';

  dsdProject := prBoat;
  //dsdProject := prProject;

  if FindCmdLineSwitch('realProjectBoat', true)
  then gc_AdminPassword := 'qsxqsxw1'
  else gc_AdminPassword := 'Админ';

  gc_ProgramName := 'ProjectBoat.exe';

  Application.Initialize;
  gc_isSetDefault := true;
  Application.CreateForm(TdmMain, dmMain);
  Application.Run;
  DUnitTestRunner.RunRegisteredTests;
end.
