-- Функции для определения метода суммирования в TPivotAddOn
CREATE OR REPLACE FUNCTION zc_PivotSummartType_None() RETURNS Integer AS $BODY$BEGIN RETURN (0); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Count() RETURNS Integer AS $BODY$BEGIN RETURN (1); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Sum() RETURNS Integer AS $BODY$BEGIN RETURN (2); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Min() RETURNS Integer AS $BODY$BEGIN RETURN (3); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Max() RETURNS Integer AS $BODY$BEGIN RETURN (4); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Average() RETURNS Integer AS $BODY$BEGIN RETURN (5); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_StdDev() RETURNS Integer AS $BODY$BEGIN RETURN (6); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_StdDevP() RETURNS Integer AS $BODY$BEGIN RETURN (7); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_Variance() RETURNS Integer AS $BODY$BEGIN RETURN (8); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
CREATE OR REPLACE FUNCTION zc_PivotSummartType_VarianceP() RETURNS Integer AS $BODY$BEGIN RETURN (9); END; $BODY$ LANGUAGE PLPGSQL IMMUTABLE;
